// Generated by gencpp from file deptrum_camera/GetBool.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_GETBOOL_H
#define DEPTRUM_CAMERA_MESSAGE_GETBOOL_H

#include <ros/service_traits.h>


#include <deptrum_camera/GetBoolRequest.h>
#include <deptrum_camera/GetBoolResponse.h>


namespace deptrum_camera
{

struct GetBool
{

typedef GetBoolRequest Request;
typedef GetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBool
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::GetBool > {
  static const char* value()
  {
    return "43f76a855b16e988566e147b692f2fab";
  }

  static const char* value(const ::deptrum_camera::GetBool&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::GetBool > {
  static const char* value()
  {
    return "deptrum_camera/GetBool";
  }

  static const char* value(const ::deptrum_camera::GetBool&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::GetBoolRequest> should match
// service_traits::MD5Sum< ::deptrum_camera::GetBool >
template<>
struct MD5Sum< ::deptrum_camera::GetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetBool >::value();
  }
  static const char* value(const ::deptrum_camera::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetBoolRequest> should match
// service_traits::DataType< ::deptrum_camera::GetBool >
template<>
struct DataType< ::deptrum_camera::GetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetBool >::value();
  }
  static const char* value(const ::deptrum_camera::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::GetBoolResponse> should match
// service_traits::MD5Sum< ::deptrum_camera::GetBool >
template<>
struct MD5Sum< ::deptrum_camera::GetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetBool >::value();
  }
  static const char* value(const ::deptrum_camera::GetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetBoolResponse> should match
// service_traits::DataType< ::deptrum_camera::GetBool >
template<>
struct DataType< ::deptrum_camera::GetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetBool >::value();
  }
  static const char* value(const ::deptrum_camera::GetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_GETBOOL_H
