// Generated by gencpp from file deptrum_camera/GetCameraInfo.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_GETCAMERAINFO_H
#define DEPTRUM_CAMERA_MESSAGE_GETCAMERAINFO_H

#include <ros/service_traits.h>


#include <deptrum_camera/GetCameraInfoRequest.h>
#include <deptrum_camera/GetCameraInfoResponse.h>


namespace deptrum_camera
{

struct GetCameraInfo
{

typedef GetCameraInfoRequest Request;
typedef GetCameraInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCameraInfo
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::GetCameraInfo > {
  static const char* value()
  {
    return "aacf7dfed1a501be45f34981291a5579";
  }

  static const char* value(const ::deptrum_camera::GetCameraInfo&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::GetCameraInfo > {
  static const char* value()
  {
    return "deptrum_camera/GetCameraInfo";
  }

  static const char* value(const ::deptrum_camera::GetCameraInfo&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::GetCameraInfoRequest> should match
// service_traits::MD5Sum< ::deptrum_camera::GetCameraInfo >
template<>
struct MD5Sum< ::deptrum_camera::GetCameraInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetCameraInfo >::value();
  }
  static const char* value(const ::deptrum_camera::GetCameraInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetCameraInfoRequest> should match
// service_traits::DataType< ::deptrum_camera::GetCameraInfo >
template<>
struct DataType< ::deptrum_camera::GetCameraInfoRequest>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetCameraInfo >::value();
  }
  static const char* value(const ::deptrum_camera::GetCameraInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::GetCameraInfoResponse> should match
// service_traits::MD5Sum< ::deptrum_camera::GetCameraInfo >
template<>
struct MD5Sum< ::deptrum_camera::GetCameraInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetCameraInfo >::value();
  }
  static const char* value(const ::deptrum_camera::GetCameraInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetCameraInfoResponse> should match
// service_traits::DataType< ::deptrum_camera::GetCameraInfo >
template<>
struct DataType< ::deptrum_camera::GetCameraInfoResponse>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetCameraInfo >::value();
  }
  static const char* value(const ::deptrum_camera::GetCameraInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_GETCAMERAINFO_H
