// Generated by gencpp from file deptrum_camera/GetCameraParams.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_GETCAMERAPARAMS_H
#define DEPTRUM_CAMERA_MESSAGE_GETCAMERAPARAMS_H

#include <ros/service_traits.h>


#include <deptrum_camera/GetCameraParamsRequest.h>
#include <deptrum_camera/GetCameraParamsResponse.h>


namespace deptrum_camera
{

struct GetCameraParams
{

typedef GetCameraParamsRequest Request;
typedef GetCameraParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCameraParams
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::GetCameraParams > {
  static const char* value()
  {
    return "06621ca772ba4ac96475002c209b1554";
  }

  static const char* value(const ::deptrum_camera::GetCameraParams&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::GetCameraParams > {
  static const char* value()
  {
    return "deptrum_camera/GetCameraParams";
  }

  static const char* value(const ::deptrum_camera::GetCameraParams&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::GetCameraParamsRequest> should match
// service_traits::MD5Sum< ::deptrum_camera::GetCameraParams >
template<>
struct MD5Sum< ::deptrum_camera::GetCameraParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetCameraParams >::value();
  }
  static const char* value(const ::deptrum_camera::GetCameraParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetCameraParamsRequest> should match
// service_traits::DataType< ::deptrum_camera::GetCameraParams >
template<>
struct DataType< ::deptrum_camera::GetCameraParamsRequest>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetCameraParams >::value();
  }
  static const char* value(const ::deptrum_camera::GetCameraParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::GetCameraParamsResponse> should match
// service_traits::MD5Sum< ::deptrum_camera::GetCameraParams >
template<>
struct MD5Sum< ::deptrum_camera::GetCameraParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetCameraParams >::value();
  }
  static const char* value(const ::deptrum_camera::GetCameraParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetCameraParamsResponse> should match
// service_traits::DataType< ::deptrum_camera::GetCameraParams >
template<>
struct DataType< ::deptrum_camera::GetCameraParamsResponse>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetCameraParams >::value();
  }
  static const char* value(const ::deptrum_camera::GetCameraParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_GETCAMERAPARAMS_H
