// Generated by gencpp from file deptrum_camera/GetDeviceInfo.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_GETDEVICEINFO_H
#define DEPTRUM_CAMERA_MESSAGE_GETDEVICEINFO_H

#include <ros/service_traits.h>


#include <deptrum_camera/GetDeviceInfoRequest.h>
#include <deptrum_camera/GetDeviceInfoResponse.h>


namespace deptrum_camera
{

struct GetDeviceInfo
{

typedef GetDeviceInfoRequest Request;
typedef GetDeviceInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDeviceInfo
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::GetDeviceInfo > {
  static const char* value()
  {
    return "a172c842ade7825e92d115b1aef6b0d1";
  }

  static const char* value(const ::deptrum_camera::GetDeviceInfo&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::GetDeviceInfo > {
  static const char* value()
  {
    return "deptrum_camera/GetDeviceInfo";
  }

  static const char* value(const ::deptrum_camera::GetDeviceInfo&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::GetDeviceInfoRequest> should match
// service_traits::MD5Sum< ::deptrum_camera::GetDeviceInfo >
template<>
struct MD5Sum< ::deptrum_camera::GetDeviceInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetDeviceInfo >::value();
  }
  static const char* value(const ::deptrum_camera::GetDeviceInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetDeviceInfoRequest> should match
// service_traits::DataType< ::deptrum_camera::GetDeviceInfo >
template<>
struct DataType< ::deptrum_camera::GetDeviceInfoRequest>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetDeviceInfo >::value();
  }
  static const char* value(const ::deptrum_camera::GetDeviceInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::GetDeviceInfoResponse> should match
// service_traits::MD5Sum< ::deptrum_camera::GetDeviceInfo >
template<>
struct MD5Sum< ::deptrum_camera::GetDeviceInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetDeviceInfo >::value();
  }
  static const char* value(const ::deptrum_camera::GetDeviceInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetDeviceInfoResponse> should match
// service_traits::DataType< ::deptrum_camera::GetDeviceInfo >
template<>
struct DataType< ::deptrum_camera::GetDeviceInfoResponse>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetDeviceInfo >::value();
  }
  static const char* value(const ::deptrum_camera::GetDeviceInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_GETDEVICEINFO_H
