// Generated by gencpp from file deptrum_camera/GetInt32TwoParamRequest.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_GETINT32TWOPARAMREQUEST_H
#define DEPTRUM_CAMERA_MESSAGE_GETINT32TWOPARAMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deptrum_camera
{
template <class ContainerAllocator>
struct GetInt32TwoParamRequest_
{
  typedef GetInt32TwoParamRequest_<ContainerAllocator> Type;

  GetInt32TwoParamRequest_()
    {
    }
  GetInt32TwoParamRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetInt32TwoParamRequest_

typedef ::deptrum_camera::GetInt32TwoParamRequest_<std::allocator<void> > GetInt32TwoParamRequest;

typedef boost::shared_ptr< ::deptrum_camera::GetInt32TwoParamRequest > GetInt32TwoParamRequestPtr;
typedef boost::shared_ptr< ::deptrum_camera::GetInt32TwoParamRequest const> GetInt32TwoParamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace deptrum_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deptrum_camera/GetInt32TwoParamRequest";
  }

  static const char* value(const ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInt32TwoParamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::deptrum_camera::GetInt32TwoParamRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_GETINT32TWOPARAMREQUEST_H
