// Generated by gencpp from file deptrum_camera/GetInt32.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_GETINT32_H
#define DEPTRUM_CAMERA_MESSAGE_GETINT32_H

#include <ros/service_traits.h>


#include <deptrum_camera/GetInt32Request.h>
#include <deptrum_camera/GetInt32Response.h>


namespace deptrum_camera
{

struct GetInt32
{

typedef GetInt32Request Request;
typedef GetInt32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInt32
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::GetInt32 > {
  static const char* value()
  {
    return "1e06c77f31583d55c01571a573d75b9f";
  }

  static const char* value(const ::deptrum_camera::GetInt32&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::GetInt32 > {
  static const char* value()
  {
    return "deptrum_camera/GetInt32";
  }

  static const char* value(const ::deptrum_camera::GetInt32&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::GetInt32Request> should match
// service_traits::MD5Sum< ::deptrum_camera::GetInt32 >
template<>
struct MD5Sum< ::deptrum_camera::GetInt32Request>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetInt32 >::value();
  }
  static const char* value(const ::deptrum_camera::GetInt32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetInt32Request> should match
// service_traits::DataType< ::deptrum_camera::GetInt32 >
template<>
struct DataType< ::deptrum_camera::GetInt32Request>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetInt32 >::value();
  }
  static const char* value(const ::deptrum_camera::GetInt32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::GetInt32Response> should match
// service_traits::MD5Sum< ::deptrum_camera::GetInt32 >
template<>
struct MD5Sum< ::deptrum_camera::GetInt32Response>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetInt32 >::value();
  }
  static const char* value(const ::deptrum_camera::GetInt32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetInt32Response> should match
// service_traits::DataType< ::deptrum_camera::GetInt32 >
template<>
struct DataType< ::deptrum_camera::GetInt32Response>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetInt32 >::value();
  }
  static const char* value(const ::deptrum_camera::GetInt32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_GETINT32_H
