// Generated by gencpp from file deptrum_camera/GetInt32TwoParam.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_GETINT32TWOPARAM_H
#define DEPTRUM_CAMERA_MESSAGE_GETINT32TWOPARAM_H

#include <ros/service_traits.h>


#include <deptrum_camera/GetInt32TwoParamRequest.h>
#include <deptrum_camera/GetInt32TwoParamResponse.h>


namespace deptrum_camera
{

struct GetInt32TwoParam
{

typedef GetInt32TwoParamRequest Request;
typedef GetInt32TwoParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInt32TwoParam
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::GetInt32TwoParam > {
  static const char* value()
  {
    return "de440921d13d18cca98fe886c3de143e";
  }

  static const char* value(const ::deptrum_camera::GetInt32TwoParam&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::GetInt32TwoParam > {
  static const char* value()
  {
    return "deptrum_camera/GetInt32TwoParam";
  }

  static const char* value(const ::deptrum_camera::GetInt32TwoParam&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::GetInt32TwoParamRequest> should match
// service_traits::MD5Sum< ::deptrum_camera::GetInt32TwoParam >
template<>
struct MD5Sum< ::deptrum_camera::GetInt32TwoParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetInt32TwoParam >::value();
  }
  static const char* value(const ::deptrum_camera::GetInt32TwoParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetInt32TwoParamRequest> should match
// service_traits::DataType< ::deptrum_camera::GetInt32TwoParam >
template<>
struct DataType< ::deptrum_camera::GetInt32TwoParamRequest>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetInt32TwoParam >::value();
  }
  static const char* value(const ::deptrum_camera::GetInt32TwoParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::GetInt32TwoParamResponse> should match
// service_traits::MD5Sum< ::deptrum_camera::GetInt32TwoParam >
template<>
struct MD5Sum< ::deptrum_camera::GetInt32TwoParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetInt32TwoParam >::value();
  }
  static const char* value(const ::deptrum_camera::GetInt32TwoParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetInt32TwoParamResponse> should match
// service_traits::DataType< ::deptrum_camera::GetInt32TwoParam >
template<>
struct DataType< ::deptrum_camera::GetInt32TwoParamResponse>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetInt32TwoParam >::value();
  }
  static const char* value(const ::deptrum_camera::GetInt32TwoParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_GETINT32TWOPARAM_H
