// Generated by gencpp from file deptrum_camera/GetString.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_GETSTRING_H
#define DEPTRUM_CAMERA_MESSAGE_GETSTRING_H

#include <ros/service_traits.h>


#include <deptrum_camera/GetStringRequest.h>
#include <deptrum_camera/GetStringResponse.h>


namespace deptrum_camera
{

struct GetString
{

typedef GetStringRequest Request;
typedef GetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetString
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::GetString > {
  static const char* value()
  {
    return "15baad3d82a7b70bfc4eb31d66322293";
  }

  static const char* value(const ::deptrum_camera::GetString&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::GetString > {
  static const char* value()
  {
    return "deptrum_camera/GetString";
  }

  static const char* value(const ::deptrum_camera::GetString&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::GetStringRequest> should match
// service_traits::MD5Sum< ::deptrum_camera::GetString >
template<>
struct MD5Sum< ::deptrum_camera::GetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetString >::value();
  }
  static const char* value(const ::deptrum_camera::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetStringRequest> should match
// service_traits::DataType< ::deptrum_camera::GetString >
template<>
struct DataType< ::deptrum_camera::GetStringRequest>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetString >::value();
  }
  static const char* value(const ::deptrum_camera::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::GetStringResponse> should match
// service_traits::MD5Sum< ::deptrum_camera::GetString >
template<>
struct MD5Sum< ::deptrum_camera::GetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::GetString >::value();
  }
  static const char* value(const ::deptrum_camera::GetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::GetStringResponse> should match
// service_traits::DataType< ::deptrum_camera::GetString >
template<>
struct DataType< ::deptrum_camera::GetStringResponse>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::GetString >::value();
  }
  static const char* value(const ::deptrum_camera::GetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_GETSTRING_H
