// Generated by gencpp from file deptrum_camera/SetArrays.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_SETARRAYS_H
#define DEPTRUM_CAMERA_MESSAGE_SETARRAYS_H

#include <ros/service_traits.h>


#include <deptrum_camera/SetArraysRequest.h>
#include <deptrum_camera/SetArraysResponse.h>


namespace deptrum_camera
{

struct SetArrays
{

typedef SetArraysRequest Request;
typedef SetArraysResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetArrays
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::SetArrays > {
  static const char* value()
  {
    return "5ec206645f78d76502a2effe3ab66933";
  }

  static const char* value(const ::deptrum_camera::SetArrays&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::SetArrays > {
  static const char* value()
  {
    return "deptrum_camera/SetArrays";
  }

  static const char* value(const ::deptrum_camera::SetArrays&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::SetArraysRequest> should match
// service_traits::MD5Sum< ::deptrum_camera::SetArrays >
template<>
struct MD5Sum< ::deptrum_camera::SetArraysRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::SetArrays >::value();
  }
  static const char* value(const ::deptrum_camera::SetArraysRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::SetArraysRequest> should match
// service_traits::DataType< ::deptrum_camera::SetArrays >
template<>
struct DataType< ::deptrum_camera::SetArraysRequest>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::SetArrays >::value();
  }
  static const char* value(const ::deptrum_camera::SetArraysRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::SetArraysResponse> should match
// service_traits::MD5Sum< ::deptrum_camera::SetArrays >
template<>
struct MD5Sum< ::deptrum_camera::SetArraysResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::SetArrays >::value();
  }
  static const char* value(const ::deptrum_camera::SetArraysResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::SetArraysResponse> should match
// service_traits::DataType< ::deptrum_camera::SetArrays >
template<>
struct DataType< ::deptrum_camera::SetArraysResponse>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::SetArrays >::value();
  }
  static const char* value(const ::deptrum_camera::SetArraysResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_SETARRAYS_H
