// Generated by gencpp from file deptrum_camera/SetBool.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_SETBOOL_H
#define DEPTRUM_CAMERA_MESSAGE_SETBOOL_H

#include <ros/service_traits.h>


#include <deptrum_camera/SetBoolRequest.h>
#include <deptrum_camera/SetBoolResponse.h>


namespace deptrum_camera
{

struct SetBool
{

typedef SetBoolRequest Request;
typedef SetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBool
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::SetBool > {
  static const char* value()
  {
    return "09fb03525b03e7ea1fd3992bafd87e16";
  }

  static const char* value(const ::deptrum_camera::SetBool&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::SetBool > {
  static const char* value()
  {
    return "deptrum_camera/SetBool";
  }

  static const char* value(const ::deptrum_camera::SetBool&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::SetBoolRequest> should match
// service_traits::MD5Sum< ::deptrum_camera::SetBool >
template<>
struct MD5Sum< ::deptrum_camera::SetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::SetBool >::value();
  }
  static const char* value(const ::deptrum_camera::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::SetBoolRequest> should match
// service_traits::DataType< ::deptrum_camera::SetBool >
template<>
struct DataType< ::deptrum_camera::SetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::SetBool >::value();
  }
  static const char* value(const ::deptrum_camera::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::SetBoolResponse> should match
// service_traits::MD5Sum< ::deptrum_camera::SetBool >
template<>
struct MD5Sum< ::deptrum_camera::SetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::SetBool >::value();
  }
  static const char* value(const ::deptrum_camera::SetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::SetBoolResponse> should match
// service_traits::DataType< ::deptrum_camera::SetBool >
template<>
struct DataType< ::deptrum_camera::SetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::SetBool >::value();
  }
  static const char* value(const ::deptrum_camera::SetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_SETBOOL_H
