// Generated by gencpp from file deptrum_camera/SetFilter.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_SETFILTER_H
#define DEPTRUM_CAMERA_MESSAGE_SETFILTER_H

#include <ros/service_traits.h>


#include <deptrum_camera/SetFilterRequest.h>
#include <deptrum_camera/SetFilterResponse.h>


namespace deptrum_camera
{

struct SetFilter
{

typedef SetFilterRequest Request;
typedef SetFilterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFilter
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::SetFilter > {
  static const char* value()
  {
    return "037b7c075b0fb69f649f20b878a7ce51";
  }

  static const char* value(const ::deptrum_camera::SetFilter&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::SetFilter > {
  static const char* value()
  {
    return "deptrum_camera/SetFilter";
  }

  static const char* value(const ::deptrum_camera::SetFilter&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::SetFilterRequest> should match
// service_traits::MD5Sum< ::deptrum_camera::SetFilter >
template<>
struct MD5Sum< ::deptrum_camera::SetFilterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::SetFilter >::value();
  }
  static const char* value(const ::deptrum_camera::SetFilterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::SetFilterRequest> should match
// service_traits::DataType< ::deptrum_camera::SetFilter >
template<>
struct DataType< ::deptrum_camera::SetFilterRequest>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::SetFilter >::value();
  }
  static const char* value(const ::deptrum_camera::SetFilterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::SetFilterResponse> should match
// service_traits::MD5Sum< ::deptrum_camera::SetFilter >
template<>
struct MD5Sum< ::deptrum_camera::SetFilterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::SetFilter >::value();
  }
  static const char* value(const ::deptrum_camera::SetFilterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::SetFilterResponse> should match
// service_traits::DataType< ::deptrum_camera::SetFilter >
template<>
struct DataType< ::deptrum_camera::SetFilterResponse>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::SetFilter >::value();
  }
  static const char* value(const ::deptrum_camera::SetFilterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_SETFILTER_H
