// Generated by gencpp from file deptrum_camera/SetInt32.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_SETINT32_H
#define DEPTRUM_CAMERA_MESSAGE_SETINT32_H

#include <ros/service_traits.h>


#include <deptrum_camera/SetInt32Request.h>
#include <deptrum_camera/SetInt32Response.h>


namespace deptrum_camera
{

struct SetInt32
{

typedef SetInt32Request Request;
typedef SetInt32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt32
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::SetInt32 > {
  static const char* value()
  {
    return "41a6318c88ca9d75d7a585e2aa4ca6ea";
  }

  static const char* value(const ::deptrum_camera::SetInt32&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::SetInt32 > {
  static const char* value()
  {
    return "deptrum_camera/SetInt32";
  }

  static const char* value(const ::deptrum_camera::SetInt32&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::SetInt32Request> should match
// service_traits::MD5Sum< ::deptrum_camera::SetInt32 >
template<>
struct MD5Sum< ::deptrum_camera::SetInt32Request>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::SetInt32 >::value();
  }
  static const char* value(const ::deptrum_camera::SetInt32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::SetInt32Request> should match
// service_traits::DataType< ::deptrum_camera::SetInt32 >
template<>
struct DataType< ::deptrum_camera::SetInt32Request>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::SetInt32 >::value();
  }
  static const char* value(const ::deptrum_camera::SetInt32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::SetInt32Response> should match
// service_traits::MD5Sum< ::deptrum_camera::SetInt32 >
template<>
struct MD5Sum< ::deptrum_camera::SetInt32Response>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::SetInt32 >::value();
  }
  static const char* value(const ::deptrum_camera::SetInt32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::SetInt32Response> should match
// service_traits::DataType< ::deptrum_camera::SetInt32 >
template<>
struct DataType< ::deptrum_camera::SetInt32Response>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::SetInt32 >::value();
  }
  static const char* value(const ::deptrum_camera::SetInt32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_SETINT32_H
