// Generated by gencpp from file deptrum_camera/SetInt32TwoParamRequest.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_SETINT32TWOPARAMREQUEST_H
#define DEPTRUM_CAMERA_MESSAGE_SETINT32TWOPARAMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deptrum_camera
{
template <class ContainerAllocator>
struct SetInt32TwoParamRequest_
{
  typedef SetInt32TwoParamRequest_<ContainerAllocator> Type;

  SetInt32TwoParamRequest_()
    : data(0)
    , data_two(0)  {
    }
  SetInt32TwoParamRequest_(const ContainerAllocator& _alloc)
    : data(0)
    , data_two(0)  {
  (void)_alloc;
    }



   typedef int32_t _data_type;
  _data_type data;

   typedef int32_t _data_two_type;
  _data_two_type data_two;





  typedef boost::shared_ptr< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetInt32TwoParamRequest_

typedef ::deptrum_camera::SetInt32TwoParamRequest_<std::allocator<void> > SetInt32TwoParamRequest;

typedef boost::shared_ptr< ::deptrum_camera::SetInt32TwoParamRequest > SetInt32TwoParamRequestPtr;
typedef boost::shared_ptr< ::deptrum_camera::SetInt32TwoParamRequest const> SetInt32TwoParamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator1> & lhs, const ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.data_two == rhs.data_two;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator1> & lhs, const ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deptrum_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e58b1a58dcf04102c497c0d49be55f01";
  }

  static const char* value(const ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe58b1a58dcf04102ULL;
  static const uint64_t static_value2 = 0xc497c0d49be55f01ULL;
};

template<class ContainerAllocator>
struct DataType< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deptrum_camera/SetInt32TwoParamRequest";
  }

  static const char* value(const ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 data\n"
"int32 data_two\n"
;
  }

  static const char* value(const ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.data_two);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInt32TwoParamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deptrum_camera::SetInt32TwoParamRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data_two: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data_two);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_SETINT32TWOPARAMREQUEST_H
