// Generated by gencpp from file deptrum_camera/SetInt32TwoParam.msg
// DO NOT EDIT!


#ifndef DEPTRUM_CAMERA_MESSAGE_SETINT32TWOPARAM_H
#define DEPTRUM_CAMERA_MESSAGE_SETINT32TWOPARAM_H

#include <ros/service_traits.h>


#include <deptrum_camera/SetInt32TwoParamRequest.h>
#include <deptrum_camera/SetInt32TwoParamResponse.h>


namespace deptrum_camera
{

struct SetInt32TwoParam
{

typedef SetInt32TwoParamRequest Request;
typedef SetInt32TwoParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt32TwoParam
} // namespace deptrum_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deptrum_camera::SetInt32TwoParam > {
  static const char* value()
  {
    return "bc6de20a6c902412675c277e90267ae2";
  }

  static const char* value(const ::deptrum_camera::SetInt32TwoParam&) { return value(); }
};

template<>
struct DataType< ::deptrum_camera::SetInt32TwoParam > {
  static const char* value()
  {
    return "deptrum_camera/SetInt32TwoParam";
  }

  static const char* value(const ::deptrum_camera::SetInt32TwoParam&) { return value(); }
};


// service_traits::MD5Sum< ::deptrum_camera::SetInt32TwoParamRequest> should match
// service_traits::MD5Sum< ::deptrum_camera::SetInt32TwoParam >
template<>
struct MD5Sum< ::deptrum_camera::SetInt32TwoParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::SetInt32TwoParam >::value();
  }
  static const char* value(const ::deptrum_camera::SetInt32TwoParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::SetInt32TwoParamRequest> should match
// service_traits::DataType< ::deptrum_camera::SetInt32TwoParam >
template<>
struct DataType< ::deptrum_camera::SetInt32TwoParamRequest>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::SetInt32TwoParam >::value();
  }
  static const char* value(const ::deptrum_camera::SetInt32TwoParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deptrum_camera::SetInt32TwoParamResponse> should match
// service_traits::MD5Sum< ::deptrum_camera::SetInt32TwoParam >
template<>
struct MD5Sum< ::deptrum_camera::SetInt32TwoParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deptrum_camera::SetInt32TwoParam >::value();
  }
  static const char* value(const ::deptrum_camera::SetInt32TwoParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deptrum_camera::SetInt32TwoParamResponse> should match
// service_traits::DataType< ::deptrum_camera::SetInt32TwoParam >
template<>
struct DataType< ::deptrum_camera::SetInt32TwoParamResponse>
{
  static const char* value()
  {
    return DataType< ::deptrum_camera::SetInt32TwoParam >::value();
  }
  static const char* value(const ::deptrum_camera::SetInt32TwoParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTRUM_CAMERA_MESSAGE_SETINT32TWOPARAM_H
