# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hipnuc_imu/Ins_0x81_package.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Ins_0x81_package(genpy.Message):
  _md5sum = "4551f87534527c807c5576a40dab6bfe"
  _type = "hipnuc_imu/Ins_0x81_package"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 frame_rate
uint8  tag
uint16 status
uint8 ins_status
uint16 gpst_wn   
uint32 gpst_tow
int16 gyr_b_x
int16 gyr_b_y
int16 gyr_b_z
int16 acc_b_x
int16 acc_b_y
int16 acc_b_z
int16 mag_b_x
int16 mag_b_y
int16 mag_b_z
int16 air_pressure
uint8 reserved_1
uint8 reserved_2
int8 temperature
uint8 utc_year
uint8 utc_mouth
uint8 utc_day
uint8 utc_hour
uint8 utc_min
uint16 utc_sec
int16 roll
int16 pitch
uint16 yaw
int16 quat_w
int16 quat_x
int16 quat_y
int16 quat_z
int32 ins_lon
int32 ins_lat
int32 ins_msl
uint8 pdop
uint8 hdop
uint8 solq_pos
uint8 nv_pos
uint8 solq_heading
uint8 nv_heading
uint8 diff_age
int16 undulation
uint8 reserved_3
int16 vel_enu_1
int16 vel_enu_2
int16 vel_enu_3
int16 acc_enu_1
int16 acc_enu_2
int16 acc_enu_3
uint32 reserved_4
uint32 reserved_5
uint32 reserved_6
uint16 reserved_7"""
  __slots__ = ['frame_rate','tag','status','ins_status','gpst_wn','gpst_tow','gyr_b_x','gyr_b_y','gyr_b_z','acc_b_x','acc_b_y','acc_b_z','mag_b_x','mag_b_y','mag_b_z','air_pressure','reserved_1','reserved_2','temperature','utc_year','utc_mouth','utc_day','utc_hour','utc_min','utc_sec','roll','pitch','yaw','quat_w','quat_x','quat_y','quat_z','ins_lon','ins_lat','ins_msl','pdop','hdop','solq_pos','nv_pos','solq_heading','nv_heading','diff_age','undulation','reserved_3','vel_enu_1','vel_enu_2','vel_enu_3','acc_enu_1','acc_enu_2','acc_enu_3','reserved_4','reserved_5','reserved_6','reserved_7']
  _slot_types = ['uint32','uint8','uint16','uint8','uint16','uint32','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16','uint8','uint8','int8','uint8','uint8','uint8','uint8','uint8','uint16','int16','int16','uint16','int16','int16','int16','int16','int32','int32','int32','uint8','uint8','uint8','uint8','uint8','uint8','uint8','int16','uint8','int16','int16','int16','int16','int16','int16','uint32','uint32','uint32','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frame_rate,tag,status,ins_status,gpst_wn,gpst_tow,gyr_b_x,gyr_b_y,gyr_b_z,acc_b_x,acc_b_y,acc_b_z,mag_b_x,mag_b_y,mag_b_z,air_pressure,reserved_1,reserved_2,temperature,utc_year,utc_mouth,utc_day,utc_hour,utc_min,utc_sec,roll,pitch,yaw,quat_w,quat_x,quat_y,quat_z,ins_lon,ins_lat,ins_msl,pdop,hdop,solq_pos,nv_pos,solq_heading,nv_heading,diff_age,undulation,reserved_3,vel_enu_1,vel_enu_2,vel_enu_3,acc_enu_1,acc_enu_2,acc_enu_3,reserved_4,reserved_5,reserved_6,reserved_7

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Ins_0x81_package, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.frame_rate is None:
        self.frame_rate = 0
      if self.tag is None:
        self.tag = 0
      if self.status is None:
        self.status = 0
      if self.ins_status is None:
        self.ins_status = 0
      if self.gpst_wn is None:
        self.gpst_wn = 0
      if self.gpst_tow is None:
        self.gpst_tow = 0
      if self.gyr_b_x is None:
        self.gyr_b_x = 0
      if self.gyr_b_y is None:
        self.gyr_b_y = 0
      if self.gyr_b_z is None:
        self.gyr_b_z = 0
      if self.acc_b_x is None:
        self.acc_b_x = 0
      if self.acc_b_y is None:
        self.acc_b_y = 0
      if self.acc_b_z is None:
        self.acc_b_z = 0
      if self.mag_b_x is None:
        self.mag_b_x = 0
      if self.mag_b_y is None:
        self.mag_b_y = 0
      if self.mag_b_z is None:
        self.mag_b_z = 0
      if self.air_pressure is None:
        self.air_pressure = 0
      if self.reserved_1 is None:
        self.reserved_1 = 0
      if self.reserved_2 is None:
        self.reserved_2 = 0
      if self.temperature is None:
        self.temperature = 0
      if self.utc_year is None:
        self.utc_year = 0
      if self.utc_mouth is None:
        self.utc_mouth = 0
      if self.utc_day is None:
        self.utc_day = 0
      if self.utc_hour is None:
        self.utc_hour = 0
      if self.utc_min is None:
        self.utc_min = 0
      if self.utc_sec is None:
        self.utc_sec = 0
      if self.roll is None:
        self.roll = 0
      if self.pitch is None:
        self.pitch = 0
      if self.yaw is None:
        self.yaw = 0
      if self.quat_w is None:
        self.quat_w = 0
      if self.quat_x is None:
        self.quat_x = 0
      if self.quat_y is None:
        self.quat_y = 0
      if self.quat_z is None:
        self.quat_z = 0
      if self.ins_lon is None:
        self.ins_lon = 0
      if self.ins_lat is None:
        self.ins_lat = 0
      if self.ins_msl is None:
        self.ins_msl = 0
      if self.pdop is None:
        self.pdop = 0
      if self.hdop is None:
        self.hdop = 0
      if self.solq_pos is None:
        self.solq_pos = 0
      if self.nv_pos is None:
        self.nv_pos = 0
      if self.solq_heading is None:
        self.solq_heading = 0
      if self.nv_heading is None:
        self.nv_heading = 0
      if self.diff_age is None:
        self.diff_age = 0
      if self.undulation is None:
        self.undulation = 0
      if self.reserved_3 is None:
        self.reserved_3 = 0
      if self.vel_enu_1 is None:
        self.vel_enu_1 = 0
      if self.vel_enu_2 is None:
        self.vel_enu_2 = 0
      if self.vel_enu_3 is None:
        self.vel_enu_3 = 0
      if self.acc_enu_1 is None:
        self.acc_enu_1 = 0
      if self.acc_enu_2 is None:
        self.acc_enu_2 = 0
      if self.acc_enu_3 is None:
        self.acc_enu_3 = 0
      if self.reserved_4 is None:
        self.reserved_4 = 0
      if self.reserved_5 is None:
        self.reserved_5 = 0
      if self.reserved_6 is None:
        self.reserved_6 = 0
      if self.reserved_7 is None:
        self.reserved_7 = 0
    else:
      self.frame_rate = 0
      self.tag = 0
      self.status = 0
      self.ins_status = 0
      self.gpst_wn = 0
      self.gpst_tow = 0
      self.gyr_b_x = 0
      self.gyr_b_y = 0
      self.gyr_b_z = 0
      self.acc_b_x = 0
      self.acc_b_y = 0
      self.acc_b_z = 0
      self.mag_b_x = 0
      self.mag_b_y = 0
      self.mag_b_z = 0
      self.air_pressure = 0
      self.reserved_1 = 0
      self.reserved_2 = 0
      self.temperature = 0
      self.utc_year = 0
      self.utc_mouth = 0
      self.utc_day = 0
      self.utc_hour = 0
      self.utc_min = 0
      self.utc_sec = 0
      self.roll = 0
      self.pitch = 0
      self.yaw = 0
      self.quat_w = 0
      self.quat_x = 0
      self.quat_y = 0
      self.quat_z = 0
      self.ins_lon = 0
      self.ins_lat = 0
      self.ins_msl = 0
      self.pdop = 0
      self.hdop = 0
      self.solq_pos = 0
      self.nv_pos = 0
      self.solq_heading = 0
      self.nv_heading = 0
      self.diff_age = 0
      self.undulation = 0
      self.reserved_3 = 0
      self.vel_enu_1 = 0
      self.vel_enu_2 = 0
      self.vel_enu_3 = 0
      self.acc_enu_1 = 0
      self.acc_enu_2 = 0
      self.acc_enu_3 = 0
      self.reserved_4 = 0
      self.reserved_5 = 0
      self.reserved_6 = 0
      self.reserved_7 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH().pack(_x.frame_rate, _x.tag, _x.status, _x.ins_status, _x.gpst_wn, _x.gpst_tow, _x.gyr_b_x, _x.gyr_b_y, _x.gyr_b_z, _x.acc_b_x, _x.acc_b_y, _x.acc_b_z, _x.mag_b_x, _x.mag_b_y, _x.mag_b_z, _x.air_pressure, _x.reserved_1, _x.reserved_2, _x.temperature, _x.utc_year, _x.utc_mouth, _x.utc_day, _x.utc_hour, _x.utc_min, _x.utc_sec, _x.roll, _x.pitch, _x.yaw, _x.quat_w, _x.quat_x, _x.quat_y, _x.quat_z, _x.ins_lon, _x.ins_lat, _x.ins_msl, _x.pdop, _x.hdop, _x.solq_pos, _x.nv_pos, _x.solq_heading, _x.nv_heading, _x.diff_age, _x.undulation, _x.reserved_3, _x.vel_enu_1, _x.vel_enu_2, _x.vel_enu_3, _x.acc_enu_1, _x.acc_enu_2, _x.acc_enu_3, _x.reserved_4, _x.reserved_5, _x.reserved_6, _x.reserved_7))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 106
      (_x.frame_rate, _x.tag, _x.status, _x.ins_status, _x.gpst_wn, _x.gpst_tow, _x.gyr_b_x, _x.gyr_b_y, _x.gyr_b_z, _x.acc_b_x, _x.acc_b_y, _x.acc_b_z, _x.mag_b_x, _x.mag_b_y, _x.mag_b_z, _x.air_pressure, _x.reserved_1, _x.reserved_2, _x.temperature, _x.utc_year, _x.utc_mouth, _x.utc_day, _x.utc_hour, _x.utc_min, _x.utc_sec, _x.roll, _x.pitch, _x.yaw, _x.quat_w, _x.quat_x, _x.quat_y, _x.quat_z, _x.ins_lon, _x.ins_lat, _x.ins_msl, _x.pdop, _x.hdop, _x.solq_pos, _x.nv_pos, _x.solq_heading, _x.nv_heading, _x.diff_age, _x.undulation, _x.reserved_3, _x.vel_enu_1, _x.vel_enu_2, _x.vel_enu_3, _x.acc_enu_1, _x.acc_enu_2, _x.acc_enu_3, _x.reserved_4, _x.reserved_5, _x.reserved_6, _x.reserved_7,) = _get_struct_IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH().pack(_x.frame_rate, _x.tag, _x.status, _x.ins_status, _x.gpst_wn, _x.gpst_tow, _x.gyr_b_x, _x.gyr_b_y, _x.gyr_b_z, _x.acc_b_x, _x.acc_b_y, _x.acc_b_z, _x.mag_b_x, _x.mag_b_y, _x.mag_b_z, _x.air_pressure, _x.reserved_1, _x.reserved_2, _x.temperature, _x.utc_year, _x.utc_mouth, _x.utc_day, _x.utc_hour, _x.utc_min, _x.utc_sec, _x.roll, _x.pitch, _x.yaw, _x.quat_w, _x.quat_x, _x.quat_y, _x.quat_z, _x.ins_lon, _x.ins_lat, _x.ins_msl, _x.pdop, _x.hdop, _x.solq_pos, _x.nv_pos, _x.solq_heading, _x.nv_heading, _x.diff_age, _x.undulation, _x.reserved_3, _x.vel_enu_1, _x.vel_enu_2, _x.vel_enu_3, _x.acc_enu_1, _x.acc_enu_2, _x.acc_enu_3, _x.reserved_4, _x.reserved_5, _x.reserved_6, _x.reserved_7))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 106
      (_x.frame_rate, _x.tag, _x.status, _x.ins_status, _x.gpst_wn, _x.gpst_tow, _x.gyr_b_x, _x.gyr_b_y, _x.gyr_b_z, _x.acc_b_x, _x.acc_b_y, _x.acc_b_z, _x.mag_b_x, _x.mag_b_y, _x.mag_b_z, _x.air_pressure, _x.reserved_1, _x.reserved_2, _x.temperature, _x.utc_year, _x.utc_mouth, _x.utc_day, _x.utc_hour, _x.utc_min, _x.utc_sec, _x.roll, _x.pitch, _x.yaw, _x.quat_w, _x.quat_x, _x.quat_y, _x.quat_z, _x.ins_lon, _x.ins_lat, _x.ins_msl, _x.pdop, _x.hdop, _x.solq_pos, _x.nv_pos, _x.solq_heading, _x.nv_heading, _x.diff_age, _x.undulation, _x.reserved_3, _x.vel_enu_1, _x.vel_enu_2, _x.vel_enu_3, _x.acc_enu_1, _x.acc_enu_2, _x.acc_enu_3, _x.reserved_4, _x.reserved_5, _x.reserved_6, _x.reserved_7,) = _get_struct_IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH = None
def _get_struct_IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH():
    global _struct_IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH
    if _struct_IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH is None:
        _struct_IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH = struct.Struct("<IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH")
    return _struct_IBHBHI10h2Bb5BH2hH4h3i7BhB6h3IH
