// Generated by gencpp from file hipnuc_imu/hipnuc_imu_msg.msg
// DO NOT EDIT!


#ifndef HIPNUC_IMU_MESSAGE_HIPNUC_IMU_MSG_H
#define HIPNUC_IMU_MESSAGE_HIPNUC_IMU_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hipnuc_imu/Imu_0x91_package.h>
#include <hipnuc_imu/Imu_0x92_package.h>
#include <hipnuc_imu/Ins_0x81_package.h>

namespace hipnuc_imu
{
template <class ContainerAllocator>
struct hipnuc_imu_msg_
{
  typedef hipnuc_imu_msg_<ContainerAllocator> Type;

  hipnuc_imu_msg_()
    : header()
    , hi91_data()
    , hi92_data()
    , hi81_data()  {
    }
  hipnuc_imu_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , hi91_data(_alloc)
    , hi92_data(_alloc)
    , hi81_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::hipnuc_imu::Imu_0x91_package_<ContainerAllocator>  _hi91_data_type;
  _hi91_data_type hi91_data;

   typedef  ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator>  _hi92_data_type;
  _hi92_data_type hi92_data;

   typedef  ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator>  _hi81_data_type;
  _hi81_data_type hi81_data;





  typedef boost::shared_ptr< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> const> ConstPtr;

}; // struct hipnuc_imu_msg_

typedef ::hipnuc_imu::hipnuc_imu_msg_<std::allocator<void> > hipnuc_imu_msg;

typedef boost::shared_ptr< ::hipnuc_imu::hipnuc_imu_msg > hipnuc_imu_msgPtr;
typedef boost::shared_ptr< ::hipnuc_imu::hipnuc_imu_msg const> hipnuc_imu_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator1> & lhs, const ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.hi91_data == rhs.hi91_data &&
    lhs.hi92_data == rhs.hi92_data &&
    lhs.hi81_data == rhs.hi81_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator1> & lhs, const ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hipnuc_imu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb9f1cc5f720d9cd4bf3b0cab56ae7c9";
  }

  static const char* value(const ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb9f1cc5f720d9cdULL;
  static const uint64_t static_value2 = 0x4bf3b0cab56ae7c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hipnuc_imu/hipnuc_imu_msg";
  }

  static const char* value(const ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Imu_0x91_package hi91_data\n"
"Imu_0x92_package hi92_data\n"
"Ins_0x81_package hi81_data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: hipnuc_imu/Imu_0x91_package\n"
"uint32 frame_rate\n"
"uint8 tag\n"
"int8 temperature\n"
"float32 air_pressure\n"
"uint32 system_time\n"
"float32 acc_x\n"
"float32 acc_y\n"
"float32 acc_z\n"
"float32 gyr_x\n"
"float32 gyr_y\n"
"float32 gyr_z\n"
"float32 mag_x\n"
"float32 mag_y\n"
"float32 mag_z\n"
"float32 eul_r\n"
"float32 eul_p\n"
"float32 eul_y\n"
"float32 quat_w\n"
"float32 quat_x\n"
"float32 quat_y\n"
"float32 quat_z\n"
"================================================================================\n"
"MSG: hipnuc_imu/Imu_0x92_package\n"
"uint32 frame_rate\n"
"uint8 tag\n"
"int8 temperature\n"
"float32 air_pressure\n"
"uint32 system_time\n"
"float32 acc_x\n"
"float32 acc_y\n"
"float32 acc_z\n"
"float32 gyr_x\n"
"float32 gyr_y\n"
"float32 gyr_z\n"
"float32 mag_x\n"
"float32 mag_y\n"
"float32 mag_z\n"
"float32 eul_r\n"
"float32 eul_p\n"
"float32 eul_y\n"
"float32 quat_w\n"
"float32 quat_x\n"
"float32 quat_y\n"
"float32 quat_z\n"
"================================================================================\n"
"MSG: hipnuc_imu/Ins_0x81_package\n"
"uint32 frame_rate\n"
"uint8  tag\n"
"uint16 status\n"
"uint8 ins_status\n"
"uint16 gpst_wn   \n"
"uint32 gpst_tow\n"
"int16 gyr_b_x\n"
"int16 gyr_b_y\n"
"int16 gyr_b_z\n"
"int16 acc_b_x\n"
"int16 acc_b_y\n"
"int16 acc_b_z\n"
"int16 mag_b_x\n"
"int16 mag_b_y\n"
"int16 mag_b_z\n"
"int16 air_pressure\n"
"uint8 reserved_1\n"
"uint8 reserved_2\n"
"int8 temperature\n"
"uint8 utc_year\n"
"uint8 utc_mouth\n"
"uint8 utc_day\n"
"uint8 utc_hour\n"
"uint8 utc_min\n"
"uint16 utc_sec\n"
"int16 roll\n"
"int16 pitch\n"
"uint16 yaw\n"
"int16 quat_w\n"
"int16 quat_x\n"
"int16 quat_y\n"
"int16 quat_z\n"
"int32 ins_lon\n"
"int32 ins_lat\n"
"int32 ins_msl\n"
"uint8 pdop\n"
"uint8 hdop\n"
"uint8 solq_pos\n"
"uint8 nv_pos\n"
"uint8 solq_heading\n"
"uint8 nv_heading\n"
"uint8 diff_age\n"
"int16 undulation\n"
"uint8 reserved_3\n"
"int16 vel_enu_1\n"
"int16 vel_enu_2\n"
"int16 vel_enu_3\n"
"int16 acc_enu_1\n"
"int16 acc_enu_2\n"
"int16 acc_enu_3\n"
"uint32 reserved_4\n"
"uint32 reserved_5\n"
"uint32 reserved_6\n"
"uint16 reserved_7\n"
;
  }

  static const char* value(const ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.hi91_data);
      stream.next(m.hi92_data);
      stream.next(m.hi81_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hipnuc_imu_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hipnuc_imu::hipnuc_imu_msg_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hi91_data: ";
    Printer< ::hipnuc_imu::Imu_0x91_package_<ContainerAllocator> >::stream(s, indent + "  ", v.hi91_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hi92_data: ";
    Printer< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> >::stream(s, indent + "  ", v.hi92_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hi81_data: ";
    Printer< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> >::stream(s, indent + "  ", v.hi81_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIPNUC_IMU_MESSAGE_HIPNUC_IMU_MSG_H
