// Generated by gencpp from file hipnuc_imu/Imu_0x92_package.msg
// DO NOT EDIT!


#ifndef HIPNUC_IMU_MESSAGE_IMU_0X92_PACKAGE_H
#define HIPNUC_IMU_MESSAGE_IMU_0X92_PACKAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hipnuc_imu
{
template <class ContainerAllocator>
struct Imu_0x92_package_
{
  typedef Imu_0x92_package_<ContainerAllocator> Type;

  Imu_0x92_package_()
    : frame_rate(0)
    , tag(0)
    , temperature(0)
    , air_pressure(0.0)
    , system_time(0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , gyr_x(0.0)
    , gyr_y(0.0)
    , gyr_z(0.0)
    , mag_x(0.0)
    , mag_y(0.0)
    , mag_z(0.0)
    , eul_r(0.0)
    , eul_p(0.0)
    , eul_y(0.0)
    , quat_w(0.0)
    , quat_x(0.0)
    , quat_y(0.0)
    , quat_z(0.0)  {
    }
  Imu_0x92_package_(const ContainerAllocator& _alloc)
    : frame_rate(0)
    , tag(0)
    , temperature(0)
    , air_pressure(0.0)
    , system_time(0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , gyr_x(0.0)
    , gyr_y(0.0)
    , gyr_z(0.0)
    , mag_x(0.0)
    , mag_y(0.0)
    , mag_z(0.0)
    , eul_r(0.0)
    , eul_p(0.0)
    , eul_y(0.0)
    , quat_w(0.0)
    , quat_x(0.0)
    , quat_y(0.0)
    , quat_z(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _frame_rate_type;
  _frame_rate_type frame_rate;

   typedef uint8_t _tag_type;
  _tag_type tag;

   typedef int8_t _temperature_type;
  _temperature_type temperature;

   typedef float _air_pressure_type;
  _air_pressure_type air_pressure;

   typedef uint32_t _system_time_type;
  _system_time_type system_time;

   typedef float _acc_x_type;
  _acc_x_type acc_x;

   typedef float _acc_y_type;
  _acc_y_type acc_y;

   typedef float _acc_z_type;
  _acc_z_type acc_z;

   typedef float _gyr_x_type;
  _gyr_x_type gyr_x;

   typedef float _gyr_y_type;
  _gyr_y_type gyr_y;

   typedef float _gyr_z_type;
  _gyr_z_type gyr_z;

   typedef float _mag_x_type;
  _mag_x_type mag_x;

   typedef float _mag_y_type;
  _mag_y_type mag_y;

   typedef float _mag_z_type;
  _mag_z_type mag_z;

   typedef float _eul_r_type;
  _eul_r_type eul_r;

   typedef float _eul_p_type;
  _eul_p_type eul_p;

   typedef float _eul_y_type;
  _eul_y_type eul_y;

   typedef float _quat_w_type;
  _quat_w_type quat_w;

   typedef float _quat_x_type;
  _quat_x_type quat_x;

   typedef float _quat_y_type;
  _quat_y_type quat_y;

   typedef float _quat_z_type;
  _quat_z_type quat_z;





  typedef boost::shared_ptr< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> const> ConstPtr;

}; // struct Imu_0x92_package_

typedef ::hipnuc_imu::Imu_0x92_package_<std::allocator<void> > Imu_0x92_package;

typedef boost::shared_ptr< ::hipnuc_imu::Imu_0x92_package > Imu_0x92_packagePtr;
typedef boost::shared_ptr< ::hipnuc_imu::Imu_0x92_package const> Imu_0x92_packageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator1> & lhs, const ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator2> & rhs)
{
  return lhs.frame_rate == rhs.frame_rate &&
    lhs.tag == rhs.tag &&
    lhs.temperature == rhs.temperature &&
    lhs.air_pressure == rhs.air_pressure &&
    lhs.system_time == rhs.system_time &&
    lhs.acc_x == rhs.acc_x &&
    lhs.acc_y == rhs.acc_y &&
    lhs.acc_z == rhs.acc_z &&
    lhs.gyr_x == rhs.gyr_x &&
    lhs.gyr_y == rhs.gyr_y &&
    lhs.gyr_z == rhs.gyr_z &&
    lhs.mag_x == rhs.mag_x &&
    lhs.mag_y == rhs.mag_y &&
    lhs.mag_z == rhs.mag_z &&
    lhs.eul_r == rhs.eul_r &&
    lhs.eul_p == rhs.eul_p &&
    lhs.eul_y == rhs.eul_y &&
    lhs.quat_w == rhs.quat_w &&
    lhs.quat_x == rhs.quat_x &&
    lhs.quat_y == rhs.quat_y &&
    lhs.quat_z == rhs.quat_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator1> & lhs, const ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hipnuc_imu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fa204fc91ba06d4f14d0b3976c76670";
  }

  static const char* value(const ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fa204fc91ba06d4ULL;
  static const uint64_t static_value2 = 0xf14d0b3976c76670ULL;
};

template<class ContainerAllocator>
struct DataType< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hipnuc_imu/Imu_0x92_package";
  }

  static const char* value(const ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 frame_rate\n"
"uint8 tag\n"
"int8 temperature\n"
"float32 air_pressure\n"
"uint32 system_time\n"
"float32 acc_x\n"
"float32 acc_y\n"
"float32 acc_z\n"
"float32 gyr_x\n"
"float32 gyr_y\n"
"float32 gyr_z\n"
"float32 mag_x\n"
"float32 mag_y\n"
"float32 mag_z\n"
"float32 eul_r\n"
"float32 eul_p\n"
"float32 eul_y\n"
"float32 quat_w\n"
"float32 quat_x\n"
"float32 quat_y\n"
"float32 quat_z\n"
;
  }

  static const char* value(const ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_rate);
      stream.next(m.tag);
      stream.next(m.temperature);
      stream.next(m.air_pressure);
      stream.next(m.system_time);
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
      stream.next(m.gyr_x);
      stream.next(m.gyr_y);
      stream.next(m.gyr_z);
      stream.next(m.mag_x);
      stream.next(m.mag_y);
      stream.next(m.mag_z);
      stream.next(m.eul_r);
      stream.next(m.eul_p);
      stream.next(m.eul_y);
      stream.next(m.quat_w);
      stream.next(m.quat_x);
      stream.next(m.quat_y);
      stream.next(m.quat_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Imu_0x92_package_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hipnuc_imu::Imu_0x92_package_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "frame_rate: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frame_rate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "temperature: ";
    Printer<int8_t>::stream(s, indent + "  ", v.temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "air_pressure: ";
    Printer<float>::stream(s, indent + "  ", v.air_pressure);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "system_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.system_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_x: ";
    Printer<float>::stream(s, indent + "  ", v.acc_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_y: ";
    Printer<float>::stream(s, indent + "  ", v.acc_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_z: ";
    Printer<float>::stream(s, indent + "  ", v.acc_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyr_x: ";
    Printer<float>::stream(s, indent + "  ", v.gyr_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyr_y: ";
    Printer<float>::stream(s, indent + "  ", v.gyr_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyr_z: ";
    Printer<float>::stream(s, indent + "  ", v.gyr_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mag_x: ";
    Printer<float>::stream(s, indent + "  ", v.mag_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mag_y: ";
    Printer<float>::stream(s, indent + "  ", v.mag_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mag_z: ";
    Printer<float>::stream(s, indent + "  ", v.mag_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "eul_r: ";
    Printer<float>::stream(s, indent + "  ", v.eul_r);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "eul_p: ";
    Printer<float>::stream(s, indent + "  ", v.eul_p);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "eul_y: ";
    Printer<float>::stream(s, indent + "  ", v.eul_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat_w: ";
    Printer<float>::stream(s, indent + "  ", v.quat_w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat_x: ";
    Printer<float>::stream(s, indent + "  ", v.quat_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat_y: ";
    Printer<float>::stream(s, indent + "  ", v.quat_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat_z: ";
    Printer<float>::stream(s, indent + "  ", v.quat_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIPNUC_IMU_MESSAGE_IMU_0X92_PACKAGE_H
