// Generated by gencpp from file hipnuc_imu/Ins_0x81_package.msg
// DO NOT EDIT!


#ifndef HIPNUC_IMU_MESSAGE_INS_0X81_PACKAGE_H
#define HIPNUC_IMU_MESSAGE_INS_0X81_PACKAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hipnuc_imu
{
template <class ContainerAllocator>
struct Ins_0x81_package_
{
  typedef Ins_0x81_package_<ContainerAllocator> Type;

  Ins_0x81_package_()
    : frame_rate(0)
    , tag(0)
    , status(0)
    , ins_status(0)
    , gpst_wn(0)
    , gpst_tow(0)
    , gyr_b_x(0)
    , gyr_b_y(0)
    , gyr_b_z(0)
    , acc_b_x(0)
    , acc_b_y(0)
    , acc_b_z(0)
    , mag_b_x(0)
    , mag_b_y(0)
    , mag_b_z(0)
    , air_pressure(0)
    , reserved_1(0)
    , reserved_2(0)
    , temperature(0)
    , utc_year(0)
    , utc_mouth(0)
    , utc_day(0)
    , utc_hour(0)
    , utc_min(0)
    , utc_sec(0)
    , roll(0)
    , pitch(0)
    , yaw(0)
    , quat_w(0)
    , quat_x(0)
    , quat_y(0)
    , quat_z(0)
    , ins_lon(0)
    , ins_lat(0)
    , ins_msl(0)
    , pdop(0)
    , hdop(0)
    , solq_pos(0)
    , nv_pos(0)
    , solq_heading(0)
    , nv_heading(0)
    , diff_age(0)
    , undulation(0)
    , reserved_3(0)
    , vel_enu_1(0)
    , vel_enu_2(0)
    , vel_enu_3(0)
    , acc_enu_1(0)
    , acc_enu_2(0)
    , acc_enu_3(0)
    , reserved_4(0)
    , reserved_5(0)
    , reserved_6(0)
    , reserved_7(0)  {
    }
  Ins_0x81_package_(const ContainerAllocator& _alloc)
    : frame_rate(0)
    , tag(0)
    , status(0)
    , ins_status(0)
    , gpst_wn(0)
    , gpst_tow(0)
    , gyr_b_x(0)
    , gyr_b_y(0)
    , gyr_b_z(0)
    , acc_b_x(0)
    , acc_b_y(0)
    , acc_b_z(0)
    , mag_b_x(0)
    , mag_b_y(0)
    , mag_b_z(0)
    , air_pressure(0)
    , reserved_1(0)
    , reserved_2(0)
    , temperature(0)
    , utc_year(0)
    , utc_mouth(0)
    , utc_day(0)
    , utc_hour(0)
    , utc_min(0)
    , utc_sec(0)
    , roll(0)
    , pitch(0)
    , yaw(0)
    , quat_w(0)
    , quat_x(0)
    , quat_y(0)
    , quat_z(0)
    , ins_lon(0)
    , ins_lat(0)
    , ins_msl(0)
    , pdop(0)
    , hdop(0)
    , solq_pos(0)
    , nv_pos(0)
    , solq_heading(0)
    , nv_heading(0)
    , diff_age(0)
    , undulation(0)
    , reserved_3(0)
    , vel_enu_1(0)
    , vel_enu_2(0)
    , vel_enu_3(0)
    , acc_enu_1(0)
    , acc_enu_2(0)
    , acc_enu_3(0)
    , reserved_4(0)
    , reserved_5(0)
    , reserved_6(0)
    , reserved_7(0)  {
  (void)_alloc;
    }



   typedef uint32_t _frame_rate_type;
  _frame_rate_type frame_rate;

   typedef uint8_t _tag_type;
  _tag_type tag;

   typedef uint16_t _status_type;
  _status_type status;

   typedef uint8_t _ins_status_type;
  _ins_status_type ins_status;

   typedef uint16_t _gpst_wn_type;
  _gpst_wn_type gpst_wn;

   typedef uint32_t _gpst_tow_type;
  _gpst_tow_type gpst_tow;

   typedef int16_t _gyr_b_x_type;
  _gyr_b_x_type gyr_b_x;

   typedef int16_t _gyr_b_y_type;
  _gyr_b_y_type gyr_b_y;

   typedef int16_t _gyr_b_z_type;
  _gyr_b_z_type gyr_b_z;

   typedef int16_t _acc_b_x_type;
  _acc_b_x_type acc_b_x;

   typedef int16_t _acc_b_y_type;
  _acc_b_y_type acc_b_y;

   typedef int16_t _acc_b_z_type;
  _acc_b_z_type acc_b_z;

   typedef int16_t _mag_b_x_type;
  _mag_b_x_type mag_b_x;

   typedef int16_t _mag_b_y_type;
  _mag_b_y_type mag_b_y;

   typedef int16_t _mag_b_z_type;
  _mag_b_z_type mag_b_z;

   typedef int16_t _air_pressure_type;
  _air_pressure_type air_pressure;

   typedef uint8_t _reserved_1_type;
  _reserved_1_type reserved_1;

   typedef uint8_t _reserved_2_type;
  _reserved_2_type reserved_2;

   typedef int8_t _temperature_type;
  _temperature_type temperature;

   typedef uint8_t _utc_year_type;
  _utc_year_type utc_year;

   typedef uint8_t _utc_mouth_type;
  _utc_mouth_type utc_mouth;

   typedef uint8_t _utc_day_type;
  _utc_day_type utc_day;

   typedef uint8_t _utc_hour_type;
  _utc_hour_type utc_hour;

   typedef uint8_t _utc_min_type;
  _utc_min_type utc_min;

   typedef uint16_t _utc_sec_type;
  _utc_sec_type utc_sec;

   typedef int16_t _roll_type;
  _roll_type roll;

   typedef int16_t _pitch_type;
  _pitch_type pitch;

   typedef uint16_t _yaw_type;
  _yaw_type yaw;

   typedef int16_t _quat_w_type;
  _quat_w_type quat_w;

   typedef int16_t _quat_x_type;
  _quat_x_type quat_x;

   typedef int16_t _quat_y_type;
  _quat_y_type quat_y;

   typedef int16_t _quat_z_type;
  _quat_z_type quat_z;

   typedef int32_t _ins_lon_type;
  _ins_lon_type ins_lon;

   typedef int32_t _ins_lat_type;
  _ins_lat_type ins_lat;

   typedef int32_t _ins_msl_type;
  _ins_msl_type ins_msl;

   typedef uint8_t _pdop_type;
  _pdop_type pdop;

   typedef uint8_t _hdop_type;
  _hdop_type hdop;

   typedef uint8_t _solq_pos_type;
  _solq_pos_type solq_pos;

   typedef uint8_t _nv_pos_type;
  _nv_pos_type nv_pos;

   typedef uint8_t _solq_heading_type;
  _solq_heading_type solq_heading;

   typedef uint8_t _nv_heading_type;
  _nv_heading_type nv_heading;

   typedef uint8_t _diff_age_type;
  _diff_age_type diff_age;

   typedef int16_t _undulation_type;
  _undulation_type undulation;

   typedef uint8_t _reserved_3_type;
  _reserved_3_type reserved_3;

   typedef int16_t _vel_enu_1_type;
  _vel_enu_1_type vel_enu_1;

   typedef int16_t _vel_enu_2_type;
  _vel_enu_2_type vel_enu_2;

   typedef int16_t _vel_enu_3_type;
  _vel_enu_3_type vel_enu_3;

   typedef int16_t _acc_enu_1_type;
  _acc_enu_1_type acc_enu_1;

   typedef int16_t _acc_enu_2_type;
  _acc_enu_2_type acc_enu_2;

   typedef int16_t _acc_enu_3_type;
  _acc_enu_3_type acc_enu_3;

   typedef uint32_t _reserved_4_type;
  _reserved_4_type reserved_4;

   typedef uint32_t _reserved_5_type;
  _reserved_5_type reserved_5;

   typedef uint32_t _reserved_6_type;
  _reserved_6_type reserved_6;

   typedef uint16_t _reserved_7_type;
  _reserved_7_type reserved_7;





  typedef boost::shared_ptr< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> const> ConstPtr;

}; // struct Ins_0x81_package_

typedef ::hipnuc_imu::Ins_0x81_package_<std::allocator<void> > Ins_0x81_package;

typedef boost::shared_ptr< ::hipnuc_imu::Ins_0x81_package > Ins_0x81_packagePtr;
typedef boost::shared_ptr< ::hipnuc_imu::Ins_0x81_package const> Ins_0x81_packageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator1> & lhs, const ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator2> & rhs)
{
  return lhs.frame_rate == rhs.frame_rate &&
    lhs.tag == rhs.tag &&
    lhs.status == rhs.status &&
    lhs.ins_status == rhs.ins_status &&
    lhs.gpst_wn == rhs.gpst_wn &&
    lhs.gpst_tow == rhs.gpst_tow &&
    lhs.gyr_b_x == rhs.gyr_b_x &&
    lhs.gyr_b_y == rhs.gyr_b_y &&
    lhs.gyr_b_z == rhs.gyr_b_z &&
    lhs.acc_b_x == rhs.acc_b_x &&
    lhs.acc_b_y == rhs.acc_b_y &&
    lhs.acc_b_z == rhs.acc_b_z &&
    lhs.mag_b_x == rhs.mag_b_x &&
    lhs.mag_b_y == rhs.mag_b_y &&
    lhs.mag_b_z == rhs.mag_b_z &&
    lhs.air_pressure == rhs.air_pressure &&
    lhs.reserved_1 == rhs.reserved_1 &&
    lhs.reserved_2 == rhs.reserved_2 &&
    lhs.temperature == rhs.temperature &&
    lhs.utc_year == rhs.utc_year &&
    lhs.utc_mouth == rhs.utc_mouth &&
    lhs.utc_day == rhs.utc_day &&
    lhs.utc_hour == rhs.utc_hour &&
    lhs.utc_min == rhs.utc_min &&
    lhs.utc_sec == rhs.utc_sec &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.quat_w == rhs.quat_w &&
    lhs.quat_x == rhs.quat_x &&
    lhs.quat_y == rhs.quat_y &&
    lhs.quat_z == rhs.quat_z &&
    lhs.ins_lon == rhs.ins_lon &&
    lhs.ins_lat == rhs.ins_lat &&
    lhs.ins_msl == rhs.ins_msl &&
    lhs.pdop == rhs.pdop &&
    lhs.hdop == rhs.hdop &&
    lhs.solq_pos == rhs.solq_pos &&
    lhs.nv_pos == rhs.nv_pos &&
    lhs.solq_heading == rhs.solq_heading &&
    lhs.nv_heading == rhs.nv_heading &&
    lhs.diff_age == rhs.diff_age &&
    lhs.undulation == rhs.undulation &&
    lhs.reserved_3 == rhs.reserved_3 &&
    lhs.vel_enu_1 == rhs.vel_enu_1 &&
    lhs.vel_enu_2 == rhs.vel_enu_2 &&
    lhs.vel_enu_3 == rhs.vel_enu_3 &&
    lhs.acc_enu_1 == rhs.acc_enu_1 &&
    lhs.acc_enu_2 == rhs.acc_enu_2 &&
    lhs.acc_enu_3 == rhs.acc_enu_3 &&
    lhs.reserved_4 == rhs.reserved_4 &&
    lhs.reserved_5 == rhs.reserved_5 &&
    lhs.reserved_6 == rhs.reserved_6 &&
    lhs.reserved_7 == rhs.reserved_7;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator1> & lhs, const ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hipnuc_imu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4551f87534527c807c5576a40dab6bfe";
  }

  static const char* value(const ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4551f87534527c80ULL;
  static const uint64_t static_value2 = 0x7c5576a40dab6bfeULL;
};

template<class ContainerAllocator>
struct DataType< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hipnuc_imu/Ins_0x81_package";
  }

  static const char* value(const ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 frame_rate\n"
"uint8  tag\n"
"uint16 status\n"
"uint8 ins_status\n"
"uint16 gpst_wn   \n"
"uint32 gpst_tow\n"
"int16 gyr_b_x\n"
"int16 gyr_b_y\n"
"int16 gyr_b_z\n"
"int16 acc_b_x\n"
"int16 acc_b_y\n"
"int16 acc_b_z\n"
"int16 mag_b_x\n"
"int16 mag_b_y\n"
"int16 mag_b_z\n"
"int16 air_pressure\n"
"uint8 reserved_1\n"
"uint8 reserved_2\n"
"int8 temperature\n"
"uint8 utc_year\n"
"uint8 utc_mouth\n"
"uint8 utc_day\n"
"uint8 utc_hour\n"
"uint8 utc_min\n"
"uint16 utc_sec\n"
"int16 roll\n"
"int16 pitch\n"
"uint16 yaw\n"
"int16 quat_w\n"
"int16 quat_x\n"
"int16 quat_y\n"
"int16 quat_z\n"
"int32 ins_lon\n"
"int32 ins_lat\n"
"int32 ins_msl\n"
"uint8 pdop\n"
"uint8 hdop\n"
"uint8 solq_pos\n"
"uint8 nv_pos\n"
"uint8 solq_heading\n"
"uint8 nv_heading\n"
"uint8 diff_age\n"
"int16 undulation\n"
"uint8 reserved_3\n"
"int16 vel_enu_1\n"
"int16 vel_enu_2\n"
"int16 vel_enu_3\n"
"int16 acc_enu_1\n"
"int16 acc_enu_2\n"
"int16 acc_enu_3\n"
"uint32 reserved_4\n"
"uint32 reserved_5\n"
"uint32 reserved_6\n"
"uint16 reserved_7\n"
;
  }

  static const char* value(const ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_rate);
      stream.next(m.tag);
      stream.next(m.status);
      stream.next(m.ins_status);
      stream.next(m.gpst_wn);
      stream.next(m.gpst_tow);
      stream.next(m.gyr_b_x);
      stream.next(m.gyr_b_y);
      stream.next(m.gyr_b_z);
      stream.next(m.acc_b_x);
      stream.next(m.acc_b_y);
      stream.next(m.acc_b_z);
      stream.next(m.mag_b_x);
      stream.next(m.mag_b_y);
      stream.next(m.mag_b_z);
      stream.next(m.air_pressure);
      stream.next(m.reserved_1);
      stream.next(m.reserved_2);
      stream.next(m.temperature);
      stream.next(m.utc_year);
      stream.next(m.utc_mouth);
      stream.next(m.utc_day);
      stream.next(m.utc_hour);
      stream.next(m.utc_min);
      stream.next(m.utc_sec);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.quat_w);
      stream.next(m.quat_x);
      stream.next(m.quat_y);
      stream.next(m.quat_z);
      stream.next(m.ins_lon);
      stream.next(m.ins_lat);
      stream.next(m.ins_msl);
      stream.next(m.pdop);
      stream.next(m.hdop);
      stream.next(m.solq_pos);
      stream.next(m.nv_pos);
      stream.next(m.solq_heading);
      stream.next(m.nv_heading);
      stream.next(m.diff_age);
      stream.next(m.undulation);
      stream.next(m.reserved_3);
      stream.next(m.vel_enu_1);
      stream.next(m.vel_enu_2);
      stream.next(m.vel_enu_3);
      stream.next(m.acc_enu_1);
      stream.next(m.acc_enu_2);
      stream.next(m.acc_enu_3);
      stream.next(m.reserved_4);
      stream.next(m.reserved_5);
      stream.next(m.reserved_6);
      stream.next(m.reserved_7);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ins_0x81_package_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hipnuc_imu::Ins_0x81_package_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "frame_rate: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frame_rate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ins_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ins_status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gpst_wn: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.gpst_wn);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gpst_tow: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.gpst_tow);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyr_b_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyr_b_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyr_b_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyr_b_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyr_b_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyr_b_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_b_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_b_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_b_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_b_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_b_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_b_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mag_b_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mag_b_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mag_b_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mag_b_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mag_b_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mag_b_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "air_pressure: ";
    Printer<int16_t>::stream(s, indent + "  ", v.air_pressure);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reserved_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reserved_1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reserved_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reserved_2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "temperature: ";
    Printer<int8_t>::stream(s, indent + "  ", v.temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "utc_year: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.utc_year);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "utc_mouth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.utc_mouth);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "utc_day: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.utc_day);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "utc_hour: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.utc_hour);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "utc_min: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.utc_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "utc_sec: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.utc_sec);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll: ";
    Printer<int16_t>::stream(s, indent + "  ", v.roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat_w: ";
    Printer<int16_t>::stream(s, indent + "  ", v.quat_w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.quat_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.quat_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.quat_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ins_lon: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ins_lon);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ins_lat: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ins_lat);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ins_msl: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ins_msl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pdop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pdop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hdop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hdop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "solq_pos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solq_pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "nv_pos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nv_pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "solq_heading: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solq_heading);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "nv_heading: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nv_heading);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diff_age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.diff_age);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "undulation: ";
    Printer<int16_t>::stream(s, indent + "  ", v.undulation);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reserved_3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reserved_3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_enu_1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vel_enu_1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_enu_2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vel_enu_2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_enu_3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vel_enu_3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_enu_1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_enu_1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_enu_2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_enu_2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_enu_3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_enu_3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reserved_4: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserved_4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reserved_5: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserved_5);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reserved_6: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserved_6);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reserved_7: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.reserved_7);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIPNUC_IMU_MESSAGE_INS_0X81_PACKAGE_H
