(cl:in-package hipnuc_imu-msg)
(cl:export '(FRAME_RATE-VAL
          FRAME_RATE
          TAG-VAL
          TAG
          STATUS-VAL
          STATUS
          INS_STATUS-VAL
          INS_STATUS
          GPST_WN-VAL
          GPST_WN
          GPST_TOW-VAL
          GPST_TOW
          GYR_B_X-VAL
          GYR_B_X
          GYR_B_Y-VAL
          GYR_B_Y
          GYR_B_Z-VAL
          GYR_B_Z
          ACC_B_X-VAL
          ACC_B_X
          ACC_B_Y-VAL
          ACC_B_Y
          ACC_B_Z-VAL
          ACC_B_Z
          MAG_B_X-VAL
          MAG_B_X
          MAG_B_Y-VAL
          MAG_B_Y
          MAG_B_Z-VAL
          MAG_B_Z
          AIR_PRESSURE-VAL
          AIR_PRESSURE
          RESERVED_1-VAL
          RESERVED_1
          RESERVED_2-VAL
          RESERVED_2
          TEMPERATURE-VAL
          TEMPERATURE
          UTC_YEAR-VAL
          UTC_YEAR
          UTC_MOUTH-VAL
          UTC_MOUTH
          UTC_DAY-VAL
          UTC_DAY
          UTC_HOUR-VAL
          UTC_HOUR
          UTC_MIN-VAL
          UTC_MIN
          UTC_SEC-VAL
          UTC_SEC
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          QUAT_W-VAL
          QUAT_W
          QUAT_X-VAL
          QUAT_X
          QUAT_Y-VAL
          QUAT_Y
          QUAT_Z-VAL
          QUAT_Z
          INS_LON-VAL
          INS_LON
          INS_LAT-VAL
          INS_LAT
          INS_MSL-VAL
          INS_MSL
          PDOP-VAL
          PDOP
          HDOP-VAL
          HDOP
          SOLQ_POS-VAL
          SOLQ_POS
          NV_POS-VAL
          NV_POS
          SOLQ_HEADING-VAL
          SOLQ_HEADING
          NV_HEADING-VAL
          NV_HEADING
          DIFF_AGE-VAL
          DIFF_AGE
          UNDULATION-VAL
          UNDULATION
          RESERVED_3-VAL
          RESERVED_3
          VEL_ENU_1-VAL
          VEL_ENU_1
          VEL_ENU_2-VAL
          VEL_ENU_2
          VEL_ENU_3-VAL
          VEL_ENU_3
          ACC_ENU_1-VAL
          ACC_ENU_1
          ACC_ENU_2-VAL
          ACC_ENU_2
          ACC_ENU_3-VAL
          ACC_ENU_3
          RESERVED_4-VAL
          RESERVED_4
          RESERVED_5-VAL
          RESERVED_5
          RESERVED_6-VAL
          RESERVED_6
          RESERVED_7-VAL
          RESERVED_7
))