deptrum: dt::Error Class Reference
dt::Error Class Reference
#include <dt_error.hpp>
Public Member Functions
~Error () override
Destroy the Error object.
const char * what () const noexceptoverride
Returns the error message of the exception.
const char * What () const noexcept
Returns the error message of the exception.
DtExceptionType GetExceptionType () const noexcept
Returns the exception type of the exception.
const char * GetFunction () const noexcept
Returns the name of the function where the exception occurred.
const char * GetArgs () const noexcept
Returns the arguments of the function where the exception occurred.
const char * GetMessage () const noexcept
Returns the error message of the exception.
Static Public Member Functions
static void Handle (dt_error **error, bool throw_exception=true)
A static function to handle the dt_error and throw an exception if needed.
Friends
std::ostream & operator<< (std::ostream &os, const Error &e)
Output the exception information to the stream.
Detailed Description
Definition at line 18 of file dt_error.hpp.
Constructor & Destructor Documentation
dt::Error::~Error () inline override
Destroy the Error object.
Definition at line 43 of file dt_error.hpp.
Member Function Documentation
static void dt::Error::Handle (dt_error ** error, bool throw_exception = true) inline static
A static function to handle the dt_error and throw an exception if needed.
Parameters
[in] error The dt_error pointer to be handled.
[in] throw_exception A boolean value to indicate whether to throw an exception or not, the default value is true.
Definition at line 27 of file dt_error.hpp.
Referenced by dt::Align::Align(), dt::Frame::As(), dt::StreamProfile::BindExtrinsicTo(), dt::Visualizer::ColorizeDepth(), dt::Config::Config(), dt::Context::Context(), dt::StreamProfileFactory::Create(), dt::FilterFactory::CreateFilter(), dt::FrameFactory::CreateFrame(), dt::FrameFactory::CreateFrameFromBuffer(), dt::FrameFactory::CreateFrameFromOtherFrame(), dt::FrameFactory::CreateFrameFromStreamProfile(), dt::FrameFactory::CreateFrameSet(), dt::Context::CreateNetDevice(), dt::Sensor::CreateRecommendedFilters(), dt::FrameFactory::CreateVideoFrame(), dt::FrameFactory::CreateVideoFrameFromBuffer(), dt::DecimationFilter::DecimationFilter(), dt::Config::DisableAllStream(), dt::Pipeline::DisableFrameSync(), dt::Config::DisableStream(), dt::Filter::Enable(), dt::Config::EnableAccelStream(), dt::Config::EnableAllStream(), dt::Context::EnableDeviceClockSync(), dt::Pipeline::EnableFrameSync(), dt::Device::EnableGlobalTimestamp(), dt::Config::EnableGyroStream(), dt::Device::EnableHeartbeat(), dt::Context::EnableNetDeviceEnumeration(), dt::Config::EnablePalmStream(), dt::Config::EnableStream(), dt::Config::EnableVideoStream(), dt::FormatConvertFilter::FormatConvertFilter(), dt::StreamProfileList::GetAccelStreamProfile(), dt::DeviceInfo::GetAsicName(), dt::Device::GetBoolOption(), dt::Device::GetBoolOptionRange(), dt::Device::GetCalibrationCameraParamList(), dt::Pipeline::GetCameraParam(), dt::CameraParamList::GetCameraParam(), dt::Pipeline::GetConfig(), dt::Filter::GetConfigSchema(), dt::Filter::GetConfigValue(), dt::DeviceInfo::GetConnectionType(), dt::DeviceList::GetConnectionType(), dt::PointsFrame::GetCoordinateValueScale(), dt::SensorList::GetCount(), dt::StreamProfileList::GetCount(), dt::FrameSet::GetCount(), dt::DtFilterList::GetCount(), dt::DeviceList::GetCount(), dt::CameraParamList::GetCount(), dt::Frame::GetData(), dt::Frame::GetDataSize(), dt::Frame::GetDevice(), dt::Pipeline::GetDevice(), dt::DeviceList::GetDevice(), dt::DeviceList::GetDeviceBySN(), dt::DeviceList::GetDeviceByUid(), dt::Device::GetDeviceState(), dt::VideoStreamProfile::GetDistortion(), dt::PlaybackDevice::GetDuration(), dt::Config::GetEnabledStreamProfileList(), dt::StreamProfile::GetExtrinsicTo(), dt::DtFilterList::GetFilter(), dt::DeviceInfo::GetFirmwareVersion(), dt::Device::GetFloatOption(), dt::Device::GetFloatOptionRange(), dt::StreamProfile::GetFormat(), dt::Frame::GetFormat(), dt::VideoStreamProfile::GetFps(), dt::FrameSet::GetFrame(), dt::FrameSet::GetFrameByIndex(), dt::FrameSet::GetFrameByName(), dt::AccelStreamProfile::GetFullScaleRange(), dt::GyroStreamProfile::GetFullScaleRange(), dt::Frame::GetGlobalTimeStampUs(), dt::StreamProfileList::GetGyroStreamProfile(), dt::DeviceInfo::GetHardwareVersion(), dt::VideoStreamProfile::GetHeight(), dt::VideoFrame::GetHeight(), dt::PointsFrame::GetHeight(), dt::Frame::GetIndex(), dt::Device::GetIntOption(), dt::Device::GetIntOptionRange(), dt::VideoStreamProfile::GetIntrinsic(), dt::AccelStreamProfile::GetIntrinsic(), dt::GyroStreamProfile::GetIntrinsic(), dt::DeviceInfo::GetIpAddress(), dt::DeviceList::GetIpAddress(), dt::DeviceList::GetLocalMacAddress(), dt::DeviceInfo::GetMacAddress(), dt::Frame::GetMetadata(), dt::Frame::GetMetadataSize(), dt::Frame::GetMetadataValue(), dt::Frame::GetName(), dt::DeviceInfo::GetName(), dt::DeviceList::GetName(), dt::StreamProfileList::GetPalmStreamProfile(), dt::DeviceInfo::GetPid(), dt::DeviceList::GetPid(), dt::VideoFrame::GetPixelAvailableBitSize(), dt::PlaybackDevice::GetPlaybackStatus(), dt::PlaybackDevice::GetPosition(), dt::StreamProfileList::GetProfile(), dt::AccelStreamProfile::GetSampleRate(), dt::GyroStreamProfile::GetSampleRate(), dt::Device::GetSensor(), dt::SensorList::GetSensor(), dt::Frame::GetSensor(), dt::Device::GetSensorList(), dt::SensorList::GetSensorType(), dt::DeviceInfo::GetSerialNumber(), dt::DeviceList::GetSerialNumber(), dt::Frame::GetStreamProfile(), dt::Sensor::GetStreamProfileList(), dt::Pipeline::GetStreamProfileList(), dt::Device::GetStructuredData(), dt::DeviceInfo::GetSupportedMinSdkVersion(), dt::Device::GetSupportedOption(), dt::Device::GetSupportedOptionCount(), dt::Frame::GetSystemTimeStampUs(), dt::AccelFrame::GetTemperature(), dt::GyroFrame::GetTemperature(), dt::Frame::GetTimeStampUs(), dt::StreamProfile::GetType(), dt::Frame::GetType(), dt::Sensor::GetType(), dt::DeviceInfo::GetUid(), dt::DeviceList::GetUid(), dt::AccelFrame::GetValue(), dt::GyroFrame::GetValue(), dt::DepthFrame::GetValueScale(), dt::DeviceInfo::GetVid(), dt::DeviceList::GetVid(), dt::StreamProfileList::GetVideoStreamProfile(), dt::VideoStreamProfile::GetWidth(), dt::VideoFrame::GetWidth(), dt::PointsFrame::GetWidth(), dt::Frame::HasMetadata(), dt::Filter::Init(), dt::Filter::IsEnabled(), dt::Device::IsGlobalTimestampSupported(), dt::Device::IsOptionSupported(), dt::RecordDevice::Pause(), dt::PlaybackDevice::Pause(), dt::Pipeline::Pipeline(), dt::PlaybackDevice::PlaybackDevice(), dt::PointCloudFilter::PointCloudFilter(), dt::Filter::Process(), dt::Filter::PushFrame(), dt::FrameSet::PushFrame(), dt::Context::QueryDeviceList(), dt::Device::ReadFlash(), dt::Device::Reboot(), dt::Device::ReceiveFileFromDevice(), dt::RecordDevice::RecordDevice(), dt::Filter::Reset(), dt::RecordDevice::Resume(), dt::PlaybackDevice::Resume(), dt::PointCloudHelper::SavePointcloudToPly(), dt::PlaybackDevice::Seek(), dt::Device::SendAndReceiveData(), dt::Device::SendFileToDevice(), dt::Align::SetAlignToStreamProfile(), dt::Device::SetBoolOption(), dt::Filter::SetCallBack(), dt::Filter::SetConfigValue(), dt::Context::SetDeviceChangedCallback(), dt::Device::SetDeviceStateChangedCallback(), dt::VideoStreamProfile::SetDistortion(), dt::Device::SetFloatOption(), dt::FrameHelper::SetFrameDeviceTimestampUs(), dt::Device::SetIntOption(), dt::VideoStreamProfile::SetIntrinsic(), dt::Logger::SetLoggerSeverity(), dt::Logger::SetLoggerToCallback(), dt::Logger::SetLoggerToConsole(), dt::Logger::SetLoggerToFile(), dt::PlaybackDevice::SetPlaybackRate(), dt::PlaybackDevice::SetPlaybackStatusChangeCallback(), dt::Device::SetStructuredData(), dt::Context::SetUvcBackendType(), dt::Sensor::Start(), dt::Pipeline::Start(), dt::Sensor::Stop(), dt::Pipeline::Stop(), dt::Sensor::SwitchProfile(), dt::ThresholdFilter::ThresholdFilter(), dt::Device::TimerSyncWithHost(), dt::CoordinateTransformHelper::Transform2dto2d(), dt::CoordinateTransformHelper::Transform2dto3d(), dt::CoordinateTransformHelper::Transform3dto2d(), dt::CoordinateTransformHelper::Transform3dto3d(), dt::Device::UpdateFirmware(), dt::Device::UpdateFirmwareFromData(), dt::Pipeline::WaitForFrames(), and dt::Device::WriteFlash().
const char* dt::Error::what () const inline override noexcept
Returns the error message of the exception.
Returns
const char* The error message.
Definition at line 55 of file dt_error.hpp.
Referenced by What().
const char* dt::Error::What () const inline noexcept
Returns the error message of the exception.
Returns
const char* The error message.
Definition at line 62 of file dt_error.hpp.
DtExceptionType dt::Error::GetExceptionType () const inline noexcept
Returns the exception type of the exception.
Read the comments of the DtExceptionType enum in the deptrum/h/dt_types.h file for more information.
Returns
DtExceptionType The exception type.
Definition at line 71 of file dt_error.hpp.
const char* dt::Error::GetFunction () const inline noexcept
Returns the name of the function where the exception occurred.
Returns
const char* The function name.
Definition at line 78 of file dt_error.hpp.
const char* dt::Error::GetArgs () const inline noexcept
Returns the arguments of the function where the exception occurred.
Returns
const char* The arguments.
Definition at line 85 of file dt_error.hpp.
const char* dt::Error::GetMessage () const inline noexcept
Returns the error message of the exception.
It is recommended to use the what() function instead.
Returns
const char* The error message.
Definition at line 93 of file dt_error.hpp.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Error & e) friend
Output the exception information to the stream.
Parameters
[in] os The output stream.
[in] e The exception object.
Returns
std::ostream& The output stream.
Definition at line 102 of file dt_error.hpp.
The documentation for this class was generated from the following file:
/home/deptrum/deptrum-stream-v3/include/deptrum/hpp/dt_error.hpp