deptrum: dt::Config Class Reference
dt::Config Class Reference
Configuration manager for pipeline stream parameters.
#include <dt_pipeline.hpp>
Public Member Functions
Config ()
Constructs a new pipeline configuration instance.
Config (dt_config_t *impl)
~Config () noexcept
Destroys the configuration instance.
dt_config_t * GetImpl () const
void EnableStream (DtStreamType stream_type) const
Enables a stream by its stream type.
void EnableStream (DtSensorType sensor_type) const
Enables a stream by its sensor type.
void EnableStream (std::shared_ptr< const StreamProfile > stream_profile) const
Enables a stream with specific profile settings.
void EnableAllStream ()
Enables all available streams.
void EnableVideoStream (DtStreamType stream_type, uint32_t width=kDtWidthAny, uint32_t height=kDtHeightAny, uint32_t fps=kDtFpsAny, DtFormat format=kDtFormatAny) const
Enables a video stream with configurable parameters.
void EnableVideoStream (DtSensorType sensor_type, uint32_t width=kDtWidthAny, uint32_t height=kDtHeightAny, uint32_t fps=kDtFpsAny, DtFormat format=kDtFormatAny) const
Enables a video stream by sensor type.
void EnableAccelStream (DtAccelFullScaleRange full_scale_range=kDtAccelFullScaleRangeAny, DtAccelSampleRate sample_rate=kDtAccelSampleRateAny) const
Enables an accelerometer stream.
void EnableGyroStream (DtGyroFullScaleRange full_scale_range=kDtGyroFullScaleRangeAny, DtGyroSampleRate sample_rate=kDtGyroSampleRateAny) const
Enables a gyroscope stream.
void EnablePalmStream () const
Enables a palm stream.
void DisableStream (DtStreamType stream_type) const
Disables a specific stream.
void DisableStream (DtSensorType sensor_type) const
Disables a specific sensor stream.
void DisableAllStream () const
Disables all configured streams.
std::shared_ptr< StreamProfileList > GetEnabledStreamProfileList () const
Retrieves the list of enabled stream profiles.
Detailed Description
Configuration manager for pipeline stream parameters.
Definition at line 26 of file dt_pipeline.hpp.
Constructor & Destructor Documentation
dt::Config::Config () inline
Constructs a new pipeline configuration instance.
Definition at line 31 of file dt_pipeline.hpp.
dt::Config::Config (dt_config_t * impl) inline explicit
Definition at line 37 of file dt_pipeline.hpp.
dt::Config::~Config () inline noexcept
Destroys the configuration instance.
Definition at line 42 of file dt_pipeline.hpp.
Member Function Documentation
dt_config_t* dt::Config::GetImpl () const inline
Definition at line 44 of file dt_pipeline.hpp.
void dt::Config::EnableStream (DtStreamType stream_type) const inline
Enables a stream by its stream type.
Parameters
[in] stream_type Stream type to enable.
Definition at line 51 of file dt_pipeline.hpp.
Referenced by EnableStream().
void dt::Config::EnableStream (DtSensorType sensor_type) const inline
Enables a stream by its sensor type.
Parameters
[in] sensor_type Sensor type to enable.
Definition at line 62 of file dt_pipeline.hpp.
void dt::Config::EnableStream (std::shared_ptr< const StreamProfile > stream_profile) const inline
Enables a stream with specific profile settings.
Parameters
[in] stream_profile Preconfigured stream profile.
Definition at line 72 of file dt_pipeline.hpp.
void dt::Config::EnableAllStream () inline
Enables all available streams.
Deprecated:
Use EnableStream with profile instead.
Definition at line 83 of file dt_pipeline.hpp.
void dt::Config::EnableVideoStream (DtStreamType stream_type, uint32_t width = kDtWidthAny, uint32_t height = kDtHeightAny, uint32_t fps = kDtFpsAny, DtFormat format = kDtFormatAny) const inline
Enables a video stream with configurable parameters.
Parameters
[in] stream_type Video stream type.
[in] width Video width (default: kDtWidthAny).
[in] height Video height (default: kDtHeightAny).
[in] fps Frame rate (default: kDtFpsAny).
[in] format Pixel format (default: kDtFormatAny).
Definition at line 98 of file dt_pipeline.hpp.
Referenced by EnableVideoStream().
void dt::Config::EnableVideoStream (DtSensorType sensor_type, uint32_t width = kDtWidthAny, uint32_t height = kDtHeightAny, uint32_t fps = kDtFpsAny, DtFormat format = kDtFormatAny) const inline
Enables a video stream by sensor type.
Parameters
[in] sensor_type Sensor type to enable.
[in] width Video width (default: kDtWidthAny).
[in] height Video height (default: kDtHeightAny).
[in] fps Frame rate (default: kDtFpsAny).
[in] format Pixel format (default: kDtFormatAny).
Definition at line 117 of file dt_pipeline.hpp.
void dt::Config::EnableAccelStream (DtAccelFullScaleRange full_scale_range = kDtAccelFullScaleRangeAny, DtAccelSampleRate sample_rate = kDtAccelSampleRateAny) const inline
Enables an accelerometer stream.
Parameters
[in] full_scale_range Measurement range (default: kDtAccelFullScaleRangeAny).
[in] sample_rate Sampling rate (default: kDtAccelSampleRateAny).
Definition at line 132 of file dt_pipeline.hpp.
void dt::Config::EnableGyroStream (DtGyroFullScaleRange full_scale_range = kDtGyroFullScaleRangeAny, DtGyroSampleRate sample_rate = kDtGyroSampleRateAny) const inline
Enables a gyroscope stream.
Parameters
[in] full_scale_range Measurement range (default: kDtGyroFullScaleRangeAny).
[in] sample_rate Sampling rate (default: kDtGyroSampleRateAny).
Definition at line 145 of file dt_pipeline.hpp.
void dt::Config::EnablePalmStream () const inline
Enables a palm stream.
Definition at line 155 of file dt_pipeline.hpp.
void dt::Config::DisableStream (DtStreamType stream_type) const inline
Disables a specific stream.
Parameters
[in] stream_type Stream type to disable.
Definition at line 166 of file dt_pipeline.hpp.
Referenced by DisableStream().
void dt::Config::DisableStream (DtSensorType sensor_type) const inline
Disables a specific sensor stream.
Parameters
[in] sensor_type Sensor type to disable.
Definition at line 177 of file dt_pipeline.hpp.
void dt::Config::DisableAllStream () const inline
Disables all configured streams.
Definition at line 185 of file dt_pipeline.hpp.
std::shared_ptr<StreamProfileList> dt::Config::GetEnabledStreamProfileList () const inline
Retrieves the list of enabled stream profiles.
Returns
std::shared_ptr<StreamProfileList> Active stream configurations.
Definition at line 196 of file dt_pipeline.hpp.
The documentation for this class was generated from the following file:
/home/deptrum/deptrum-stream-v3/include/deptrum/hpp/dt_pipeline.hpp