deptrum: dt::TypeHelper Class Reference
dt::TypeHelper Class Reference
Provides utilities for converting enumerated types to strings and checking type categories.
#include <dt_type_helper.hpp>
Static Public Member Functions
static DtStreamType ConvertSensorTypeToStreamType (DtSensorType sensor_type)
Converts a sensor type to its corresponding stream type.
static bool IsVideoSensorType (DtSensorType type)
Checks if a sensor type is classified as a video sensor.
static bool IsVideoStreamType (DtStreamType type)
Checks if a stream type is classified as a video stream.
Detailed Description
Provides utilities for converting enumerated types to strings and checking type categories.
Definition at line 24 of file dt_type_helper.hpp.
Member Function Documentation
static DtStreamType dt::TypeHelper::ConvertSensorTypeToStreamType (DtSensorType sensor_type) inline static
Converts a sensor type to its corresponding stream type.
Parameters
[in] sensor_type Sensor type to convert.
Returns
Corresponding stream type enumeration value.
Definition at line 31 of file dt_type_helper.hpp.
Referenced by dt::Config::DisableStream(), dt::Config::EnableStream(), and dt::Config::EnableVideoStream().
static bool dt::TypeHelper::IsVideoSensorType (DtSensorType type) inline static
Checks if a sensor type is classified as a video sensor.
Parameters
[in] type Sensor type to check.
Returns
True if the sensor is a video sensor, false otherwise.
Definition at line 40 of file dt_type_helper.hpp.
static bool dt::TypeHelper::IsVideoStreamType (DtStreamType type) inline static
Checks if a stream type is classified as a video stream.
Parameters
[in] type Stream type to check.
Returns
True if the stream is a video stream, false otherwise.
Definition at line 47 of file dt_type_helper.hpp.
The documentation for this class was generated from the following file:
/home/deptrum/deptrum-stream-v3/include/deptrum/hpp/dt_type_helper.hpp