deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_frame.h File Reference
dt_frame.h File Reference
Functions for frame data and information management.
#include "dt_types.h"
Functions
DT_EXPORT dt_frame * dt_create_frame (dt_frame_type frame_type, dt_format format, uint32_t data_size, dt_error **error)
Creates a generic frame object.
DT_EXPORT dt_frame * dt_create_video_frame (dt_frame_type frame_type, dt_format format, uint32_t width, uint32_t height, uint32_t stride_bytes, dt_error **error)
Creates a video frame with specified dimensions.
DT_EXPORT dt_frame * dt_create_frame_from_buffer (dt_frame_type frame_type, dt_format format, uint8_t *buffer, uint32_t buffer_size, dt_frame_destroy_callback *buffer_destroy_cb, void *buffer_destroy_context, dt_error **error)
Creates a frame from an external buffer.
DT_EXPORT dt_frame * dt_create_video_frame_from_buffer (dt_frame_type frame_type, dt_format format, uint32_t width, uint32_t height, uint32_t stride_bytes, uint8_t *buffer, uint32_t buffer_size, dt_frame_destroy_callback *buffer_destroy_cb, void *buffer_destroy_context, dt_error **error)
Creates a video frame from an external buffer.
DT_EXPORT dt_frame * dt_create_frame_from_other_frame (const dt_frame *other_frame, bool should_copy_data, dt_error **error)
Clones a frame with optional data copy.
DT_EXPORT dt_frame * dt_create_frame_from_stream_profile (const dt_stream_profile *stream_profile, dt_error **error)
Creates a frame based on stream profile specifications.
DT_EXPORT dt_frame * dt_create_frameset (dt_error **error)
Creates an empty frameset container.
DT_EXPORT void dt_delete_frame (const dt_frame *frame)
Decrements frame reference count and destroys if unreferenced.
DT_EXPORT void dt_frame_add_ref (const dt_frame *frame, dt_error **error)
Increases frame reference count.
DT_EXPORT uint8_t * dt_frame_get_metadata (const dt_frame *frame, dt_error **error)
Retrieves frame metadata buffer.
DT_EXPORT uint32_t dt_frame_get_metadata_size (const dt_frame *frame, dt_error **error)
Gets size of frame metadata.
DT_EXPORT bool dt_frame_has_metadata (const dt_frame *frame, dt_frame_metadata_type type, dt_error **error)
Checks for existence of specified metadata type.
DT_EXPORT int64_t dt_frame_get_metadata_value (const dt_frame *frame, dt_frame_metadata_type type, dt_error **error)
Retrieves integer value of specified metadata.
DT_EXPORT void dt_frame_update_metadata (dt_frame *frame, const uint8_t *metadata, uint32_t metadata_size, dt_error **error)
Replaces frame metadata content.
DT_EXPORT uint64_t dt_frame_get_index (const dt_frame *frame, dt_error **error)
Retrieves frame index identifier.
DT_EXPORT uint8_t * dt_frame_get_data (const dt_frame *frame, dt_error **error)
Retrieves frame data buffer.
DT_EXPORT uint32_t dt_frame_get_data_size (const dt_frame *frame, dt_error **error)
Gets size of frame data buffer.
DT_EXPORT dt_frame_type dt_frame_get_type (const dt_frame *frame, dt_error **error)
Retrieves frame type classification.
DT_EXPORT dt_format dt_frame_get_format (const dt_frame *frame, dt_error **error)
Retrieves frame data format.
DT_EXPORT const char * dt_frame_get_name (const dt_frame *frame, dt_error **error)
Retrieves frame name string.
DT_EXPORT void dt_frame_set_timestamp_us (dt_frame *frame, uint64_t timestamp_us, dt_error **error)
Sets device/hardware timestamp (microseconds).
DT_EXPORT uint64_t dt_frame_get_timestamp_us (const dt_frame *frame, dt_error **error)
Retrieves device/hardware timestamp (microseconds).
DT_EXPORT void dt_frame_set_system_timestamp_us (dt_frame *frame, uint64_t system_timestamp_us, dt_error **error)
Sets host reception timestamp (microseconds).
DT_EXPORT uint64_t dt_frame_get_system_timestamp_us (const dt_frame *frame, dt_error **error)
Retrieves host reception timestamp (microseconds).
DT_EXPORT uint64_t dt_frame_get_global_timestamp_us (const dt_frame *frame, dt_error **error)
Retrieves drift-corrected global timestamp (microseconds).
DT_EXPORT void dt_frame_update_data (dt_frame *frame, const uint8_t *data, uint32_t data_size, dt_error **error)
Replaces frame data content.
DT_EXPORT void dt_frame_copy_info (const dt_frame *src_frame, dt_frame *dst_frame, dt_error **error)
Copies informational fields between frames.
DT_EXPORT void dt_frame_set_stream_profile (dt_frame *frame, const dt_stream_profile *stream_profile, dt_error **error)
Assigns stream profile to frame.
DT_EXPORT dt_stream_profile * dt_frame_get_stream_profile (const dt_frame *frame, dt_error **error)
Retrieves associated stream profile.
DT_EXPORT dt_sensor * dt_frame_get_sensor (const dt_frame *frame, dt_error **error)
Retrieves source sensor object.
DT_EXPORT dt_device * dt_frame_get_device (const dt_frame *frame, dt_error **error)
Retrieves source device object.
DT_EXPORT uint32_t dt_video_frame_get_width (const dt_frame *frame, dt_error **error)
Retrieves video frame width.
DT_EXPORT uint32_t dt_video_frame_get_height (const dt_frame *frame, dt_error **error)
Retrieves video frame height.
DT_EXPORT uint8_t dt_video_frame_get_pixel_available_bit_size (const dt_frame *frame, dt_error **error)
Retrieves effective bits per pixel.
DT_EXPORT void dt_video_frame_set_pixel_available_bit_size (dt_frame *frame, uint8_t bit_size, dt_error **error)
Sets effective bits per pixel.
DT_EXPORT dt_sensor_type dt_ir_frame_get_source_sensor_type (const dt_frame *frame, dt_error **dt_error)
Identifies IR sensor source.
DT_EXPORT float dt_depth_frame_get_value_scale (const dt_frame *frame, dt_error **error)
Retrieves depth value scaling factor.
DT_EXPORT void dt_depth_frame_set_value_scale (dt_frame *frame, float value_scale, dt_error **error)
Sets depth value scaling factor.
DT_EXPORT float dt_points_frame_get_coordinate_value_scale (const dt_frame *frame, dt_error **error)
Retrieves coordinate scaling factor.
DT_EXPORT dt_accel_value dt_accel_frame_get_value (const dt_frame *frame, dt_error **error)
Retrieves accelerometer data.
DT_EXPORT float dt_accel_frame_get_temperature (const dt_frame *frame, dt_error **error)
Retrieves accelerometer temperature.
DT_EXPORT dt_gyro_value dt_gyro_frame_get_value (const dt_frame *frame, dt_error **error)
Retrieves gyroscope data.
DT_EXPORT float dt_gyro_frame_get_temperature (const dt_frame *frame, dt_error **error)
Retrieves gyroscope temperature.
DT_EXPORT uint32_t dt_point_cloud_frame_get_width (const dt_frame *frame, dt_error **error)
Retrieves the width dimension of a point cloud frame.
DT_EXPORT uint32_t dt_point_cloud_frame_get_height (const dt_frame *frame, dt_error **error)
Retrieves the height dimension of a point cloud frame.
DT_EXPORT dt_frame * dt_frameset_get_frame (const dt_frame *frameset, dt_frame_type frame_type, dt_error **error)
Retrieves frame by type from frameset.
DT_EXPORT dt_frame * dt_frameset_get_frame_by_index (const dt_frame *frameset, uint32_t index, dt_error **error)
Retrieves frame by index from frameset.
DT_EXPORT dt_frame * dt_frameset_get_frame_by_name (const dt_frame *frameset, const char *name, dt_error **error)
Retrieves frame by name from frameset.
DT_EXPORT void dt_frameset_push_frame (dt_frame *frameset, const dt_frame *frame, dt_error **error)
Adds frame to frameset container.
DT_EXPORT uint32_t dt_frameset_get_count (const dt_frame *frameset, dt_error **error)
Retrieves the number of frames contained in a frameset.
DT_EXPORT dt_frame * dt_frameset_get_depth_frame (const dt_frame *frameset, dt_error **error)
Extracts the depth frame from a frameset.
DT_EXPORT dt_frame * dt_frameset_get_color_frame (const dt_frame *frameset, dt_error **error)
Extracts the color frame from a frameset.
DT_EXPORT dt_frame * dt_frameset_get_ir_frame (const dt_frame *frameset, dt_error **error)
Extracts the infrared frame from a frameset.
DT_EXPORT dt_frame * dt_frameset_get_points_frame (const dt_frame *frameset, dt_error **error)
Extracts the point cloud frame from a frameset.
Detailed Description
Functions for frame data and information management.
Definition in file dt_frame.h.
Function Documentation
DT_EXPORT dt_frame* dt_create_frame (dt_frame_type frame_type, dt_format format, uint32_t data_size, dt_error ** error)
Creates a generic frame object.
Attention
Created frame has reference count=1. Decrease via dt_delete_frame() after use.
Parameters
[in] frame_type Type of the frame object.
[in] format Data format of the frame.
[in] data_size Size of frame data buffer in bytes.
[out] error Receives detailed error information if operation fails.
Returns
dt_frame* Pointer to created frame object.
Referenced by dt::FrameFactory::CreateFrame().
DT_EXPORT dt_frame* dt_create_video_frame (dt_frame_type frame_type, dt_format format, uint32_t width, uint32_t height, uint32_t stride_bytes, dt_error ** error)
Creates a video frame with specified dimensions.
Attention
Created frame has reference count=1. Decrease via dt_delete_frame() after use.
Parameters
[in] frame_type Type of the frame object.
[in] format Pixel format of the frame.
[in] width Frame width in pixels.
[in] height Frame height in pixels.
[in] stride_bytes Row stride in bytes (0=auto-calculate).
[out] error Receives detailed error information if operation fails.
Returns
dt_frame* Pointer to created video frame.
Referenced by dt::FrameFactory::CreateVideoFrame().
DT_EXPORT dt_frame* dt_create_frame_from_buffer (dt_frame_type frame_type, dt_format format, uint8_t * buffer, uint32_t buffer_size, dt_frame_destroy_callback * buffer_destroy_cb, void * buffer_destroy_context, dt_error ** error)
Creates a frame from an external buffer.
Attention
User retains ownership of buffer. Destroy callback will be invoked on frame deletion.
Created frame has reference count=1. Decrease via dt_delete_frame() after use.
Parameters
[in] frame_type Type of the frame object.
[in] format Data format of the frame.
[in] buffer External data buffer.
[in] buffer_size Size of buffer in bytes.
[in] buffer_destroy_cb Callback invoked when frame is destroyed.
[in] buffer_destroy_context User context for destroy callback.
[out] error Receives detailed error information if operation fails.
Returns
dt_frame* Pointer to created frame object.
Referenced by dt::FrameFactory::CreateFrameFromBuffer().
DT_EXPORT dt_frame* dt_create_video_frame_from_buffer (dt_frame_type frame_type, dt_format format, uint32_t width, uint32_t height, uint32_t stride_bytes, uint8_t * buffer, uint32_t buffer_size, dt_frame_destroy_callback * buffer_destroy_cb, void * buffer_destroy_context, dt_error ** error)
Creates a video frame from an external buffer.
Attention
User retains ownership of buffer. Destroy callback will be invoked on frame deletion.
Created frame has reference count=1. Decrease via dt_delete_frame() after use.
Parameters
[in] frame_type Type of the frame object.
[in] format Pixel format of the frame.
[in] width Frame width in pixels.
[in] height Frame height in pixels.
[in] stride_bytes Row stride in bytes (0=auto-calculate).
[in] buffer External data buffer.
[in] buffer_size Size of buffer in bytes.
[in] buffer_destroy_cb Callback invoked when frame is destroyed.
[in] buffer_destroy_context User context for destroy callback.
[out] error Receives detailed error information if operation fails.
Returns
dt_frame* Pointer to created video frame.
Referenced by dt::FrameFactory::CreateVideoFrameFromBuffer().
DT_EXPORT dt_frame* dt_create_frame_from_other_frame (const dt_frame * other_frame, bool should_copy_data, dt_error ** error)
Clones a frame with optional data copy.
Attention
Created frame has reference count=1. Decrease via dt_delete_frame() after use.
Parameters
[in] other_frame Source frame to clone.
[in] should_copy_data True to copy data, false for uninitialized buffer.
[out] error Receives detailed error information if operation fails.
Returns
dt_frame* New frame with duplicated properties.
Referenced by dt::FrameFactory::CreateFrameFromOtherFrame().
DT_EXPORT dt_frame* dt_create_frame_from_stream_profile (const dt_stream_profile * stream_profile, dt_error ** error)
Creates a frame based on stream profile specifications.
Attention
Created frame has reference count=1. Decrease via dt_delete_frame() after use.
Parameters
[in] stream_profile Stream profile defining frame parameters.
[out] error Receives detailed error information if operation fails.
Returns
dt_frame* Newly created frame object.
Referenced by dt::FrameFactory::CreateFrameFromStreamProfile().
DT_EXPORT dt_frame* dt_create_frameset (dt_error ** error)
Creates an empty frameset container.
Attention
Created frameset has reference count=1. Decrease via dt_delete_frame() after use.
Parameters
[out] error Receives detailed error information if operation fails.
Returns
dt_frame* Pointer to new frameset object.
Referenced by dt::FrameFactory::CreateFrameSet().
DT_EXPORT void dt_delete_frame (const dt_frame * frame)
Decrements frame reference count and destroys if unreferenced.
Parameters
[in] frame Frame to release references to.
Referenced by dt::Frame::~Frame().
DT_EXPORT void dt_frame_add_ref (const dt_frame * frame, dt_error ** error)
Increases frame reference count.
Attention
Each call requires matching dt_delete_frame() to release.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Frame::As().
DT_EXPORT uint8_t* dt_frame_get_metadata (const dt_frame * frame, dt_error ** error)
Retrieves frame metadata buffer.
Warning
Modifying buffer during multi-threaded use causes undefined behavior.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
uint8_t* Mutable pointer to metadata buffer.
Referenced by dt::Frame::GetMetadata().
DT_EXPORT uint32_t dt_frame_get_metadata_size (const dt_frame * frame, dt_error ** error)
Gets size of frame metadata.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
uint32_t Metadata size in bytes.
Referenced by dt::Frame::GetMetadataSize().
DT_EXPORT bool dt_frame_has_metadata (const dt_frame * frame, dt_frame_metadata_type type, dt_error ** error)
Checks for existence of specified metadata type.
Parameters
[in] frame Target frame object.
[in] type Metadata type to query.
[out] error Receives detailed error information if operation fails.
Returns
bool True if metadata type exists.
Referenced by dt::Frame::HasMetadata().
DT_EXPORT int64_t dt_frame_get_metadata_value (const dt_frame * frame, dt_frame_metadata_type type, dt_error ** error)
Retrieves integer value of specified metadata.
Parameters
[in] frame Target frame object.
[in] type Metadata type to retrieve.
[out] error Receives detailed error information if operation fails.
Returns
int64_t Value of requested metadata.
Referenced by dt::Frame::GetMetadataValue().
DT_EXPORT void dt_frame_update_metadata (dt_frame * frame, const uint8_t * metadata, uint32_t metadata_size, dt_error ** error)
Replaces frame metadata content.
Warning
Buffer must not exceed 256 bytes to prevent memory exceptions.
Parameters
[in] frame Target frame object.
[in] metadata New metadata buffer.
[in] metadata_size Size of new metadata in bytes.
[out] error Receives detailed error information if operation fails.
DT_EXPORT uint64_t dt_frame_get_index (const dt_frame * frame, dt_error ** error)
Retrieves frame index identifier.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
uint64_t Unique frame index.
Referenced by dt::Frame::GetIndex().
DT_EXPORT uint8_t* dt_frame_get_data (const dt_frame * frame, dt_error ** error)
Retrieves frame data buffer.
Warning
Direct modification during multi-threaded use causes undefined behavior.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
uint8_t* Mutable pointer to frame data.
Referenced by dt::Frame::GetData().
DT_EXPORT uint32_t dt_frame_get_data_size (const dt_frame * frame, dt_error ** error)
Gets size of frame data buffer.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
uint32_t Size of data buffer in bytes.
Referenced by dt::Frame::GetDataSize().
DT_EXPORT dt_frame_type dt_frame_get_type (const dt_frame * frame, dt_error ** error)
Retrieves frame type classification.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
dt_frame_type Frame type identifier.
Referenced by dt::Frame::GetType().
DT_EXPORT dt_format dt_frame_get_format (const dt_frame * frame, dt_error ** error)
Retrieves frame data format.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
dt_format Data format identifier.
Referenced by dt::Frame::GetFormat().
DT_EXPORT const char* dt_frame_get_name (const dt_frame * frame, dt_error ** error)
Retrieves frame name string.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
const char* Frame name (NULL if unset).
Referenced by dt::Frame::GetName().
DT_EXPORT void dt_frame_set_timestamp_us (dt_frame * frame, uint64_t timestamp_us, dt_error ** error)
Sets device/hardware timestamp (microseconds).
Parameters
[in] frame Target frame object.
[in] timestamp_us Timestamp in microseconds.
[out] error Receives detailed error information if operation fails.
Referenced by dt::FrameHelper::SetFrameDeviceTimestampUs().
DT_EXPORT uint64_t dt_frame_get_timestamp_us (const dt_frame * frame, dt_error ** error)
Retrieves device/hardware timestamp (microseconds).
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
uint64_t Captured timestamp in microseconds.
Referenced by dt::Frame::GetTimeStampUs().
DT_EXPORT void dt_frame_set_system_timestamp_us (dt_frame * frame, uint64_t system_timestamp_us, dt_error ** error)
Sets host reception timestamp (microseconds).
Parameters
[in] frame Target frame object.
[in] system_timestamp_us Host timestamp in microseconds.
[out] error Receives detailed error information if operation fails.
DT_EXPORT uint64_t dt_frame_get_system_timestamp_us (const dt_frame * frame, dt_error ** error)
Retrieves host reception timestamp (microseconds).
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
uint64_t Host timestamp in microseconds.
Referenced by dt::Frame::GetSystemTimeStampUs().
DT_EXPORT uint64_t dt_frame_get_global_timestamp_us (const dt_frame * frame, dt_error ** error)
Retrieves drift-corrected global timestamp (microseconds).
Attention
Requires prior call to dt_device_enable_global_timestamp().
Functionality depends on device capabilities.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
uint64_t Global timestamp in microseconds (0 if unsupported).
Referenced by dt::Frame::GetGlobalTimeStampUs().
DT_EXPORT void dt_frame_update_data (dt_frame * frame, const uint8_t * data, uint32_t data_size, dt_error ** error)
Replaces frame data content.
Warning
Input size must not exceed original frame data size.
Parameters
[in] frame Target frame object.
[in] data New data buffer.
[in] data_size Size of new data in bytes.
[out] error Receives detailed error information if operation fails.
DT_EXPORT void dt_frame_copy_info (const dt_frame * src_frame, dt_frame * dst_frame, dt_error ** error)
Copies informational fields between frames.
Copies index, timestamps, and metadata.
Parameters
[in] src_frame Source frame for copying.
[in] dst_frame Destination frame for copying.
[out] error Receives detailed error information if operation fails.
DT_EXPORT void dt_frame_set_stream_profile (dt_frame * frame, const dt_stream_profile * stream_profile, dt_error ** error)
Assigns stream profile to frame.
Parameters
[in] frame Target frame object.
[in] stream_profile Stream profile to associate.
[out] error Receives detailed error information if operation fails.
DT_EXPORT dt_stream_profile* dt_frame_get_stream_profile (const dt_frame * frame, dt_error ** error)
Retrieves associated stream profile.
Attention
Returned object requires dt_delete_stream_profile() for cleanup.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* Associated stream profile (NULL if unset).
Referenced by dt::Frame::GetStreamProfile().
DT_EXPORT dt_sensor* dt_frame_get_sensor (const dt_frame * frame, dt_error ** error)
Retrieves source sensor object.
Attention
Returned object requires dt_delete_sensor() for cleanup.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
dt_sensor* Source sensor object (NULL if unavailable).
Referenced by dt::Frame::GetSensor().
DT_EXPORT dt_device* dt_frame_get_device (const dt_frame * frame, dt_error ** error)
Retrieves source device object.
Attention
Returned object requires dt_delete_device() for cleanup.
Parameters
[in] frame Target frame object.
[out] error Receives detailed error information if operation fails.
Returns
dt_device* Source device object (NULL if unavailable).
Referenced by dt::Frame::GetDevice().
DT_EXPORT uint32_t dt_video_frame_get_width (const dt_frame * frame, dt_error ** error)
Retrieves video frame width.
Parameters
[in] frame Target video frame.
[out] error Receives detailed error information if operation fails.
Returns
uint32_t Frame width in pixels.
Referenced by dt::VideoFrame::GetWidth().
DT_EXPORT uint32_t dt_video_frame_get_height (const dt_frame * frame, dt_error ** error)
Retrieves video frame height.
Parameters
[in] frame Target video frame.
[out] error Receives detailed error information if operation fails.
Returns
uint32_t Frame height in pixels.
Referenced by dt::VideoFrame::GetHeight().
DT_EXPORT uint8_t dt_video_frame_get_pixel_available_bit_size (const dt_frame * frame, dt_error ** error)
Retrieves effective bits per pixel.
Attention
Only valid for Y8/Y10/Y11/Y12/Y14/Y16 formats.
Parameters
[in] frame Target video frame.
[out] error Receives detailed error information if operation fails.
Returns
uint8_t Effective bits per pixel (0 if unsupported).
Referenced by dt::VideoFrame::GetPixelAvailableBitSize().
DT_EXPORT void dt_video_frame_set_pixel_available_bit_size (dt_frame * frame, uint8_t bit_size, dt_error ** error)
Sets effective bits per pixel.
Attention
Only valid for Y8/Y10/Y11/Y12/Y14/Y16 formats.
Parameters
[in] frame Target video frame.
[in] bit_size Effective bits to assign.
[out] error Receives detailed error information if operation fails.
DT_EXPORT dt_sensor_type dt_ir_frame_get_source_sensor_type (const dt_frame * frame, dt_error ** dt_error)
Identifies IR sensor source.
Parameters
[in] frame Target IR frame.
[out] dt_error Receives detailed error information if operation fails.
Returns
dt_sensor_type Source sensor identifier.
DT_EXPORT float dt_depth_frame_get_value_scale (const dt_frame * frame, dt_error ** error)
Retrieves depth value scaling factor.
Depth in mm = pixel_value * scale.
Parameters
[in] frame Target depth frame.
[out] error Receives detailed error information if operation fails.
Returns
float Current scaling factor.
Referenced by dt::DepthFrame::GetValueScale().
DT_EXPORT void dt_depth_frame_set_value_scale (dt_frame * frame, float value_scale, dt_error ** error)
Sets depth value scaling factor.
Depth in mm = pixel_value * scale.
Parameters
[in] frame Target depth frame.
[in] value_scale Scaling factor to apply.
[out] error Receives detailed error information if operation fails.
DT_EXPORT float dt_points_frame_get_coordinate_value_scale (const dt_frame * frame, dt_error ** error)
Retrieves coordinate scaling factor.
Position in mm = coordinate_value * scale.
Parameters
[in] frame Target points frame.
[out] error Receives detailed error information if operation fails.
Returns
float Current coordinate scaling factor.
Referenced by dt::PointsFrame::GetCoordinateValueScale().
DT_EXPORT dt_accel_value dt_accel_frame_get_value (const dt_frame * frame, dt_error ** error)
Retrieves accelerometer data.
Parameters
[in] frame Target accelerometer frame.
[out] error Receives detailed error information if operation fails.
Returns
dt_accel_value Accelerometer data values.
Referenced by dt::AccelFrame::GetValue().
DT_EXPORT float dt_accel_frame_get_temperature (const dt_frame * frame, dt_error ** error)
Retrieves accelerometer temperature.
Parameters
[in] frame Target accelerometer frame.
[out] error Receives detailed error information if operation fails.
Returns
float Temperature value in Celsius.
Referenced by dt::AccelFrame::GetTemperature().
DT_EXPORT dt_gyro_value dt_gyro_frame_get_value (const dt_frame * frame, dt_error ** error)
Retrieves gyroscope data.
Parameters
[in] frame Target gyroscope frame.
[out] error Receives detailed error information if operation fails.
Returns
dt_gyro_value Gyroscope data values.
Referenced by dt::GyroFrame::GetValue().
DT_EXPORT float dt_gyro_frame_get_temperature (const dt_frame * frame, dt_error ** error)
Retrieves gyroscope temperature.
Parameters
[in] frame Target gyroscope frame.
[out] error Receives detailed error information if operation fails.
Returns
float Temperature value in Celsius.
Referenced by dt::GyroFrame::GetTemperature().
DT_EXPORT uint32_t dt_point_cloud_frame_get_width (const dt_frame * frame, dt_error ** error)
Retrieves the width dimension of a point cloud frame.
Parameters
[in] frame Point cloud frame instance (must be DT_FRAME_TYPE_POINTS).
[out] error Receives detailed error information if operation fails.
Returns
Horizontal resolution (number of points per row).
Referenced by dt::PointsFrame::GetWidth().
DT_EXPORT uint32_t dt_point_cloud_frame_get_height (const dt_frame * frame, dt_error ** error)
Retrieves the height dimension of a point cloud frame.
Parameters
[in] frame Point cloud frame instance (must be DT_FRAME_TYPE_POINTS).
[out] error Receives detailed error information if operation fails.
Returns
Vertical resolution (number of point rows).
Referenced by dt::PointsFrame::GetHeight().
DT_EXPORT dt_frame* dt_frameset_get_frame (const dt_frame * frameset, dt_frame_type frame_type, dt_error ** error)
Retrieves frame by type from frameset.
Attention
Returned frame requires dt_delete_frame() for cleanup.
Parameters
[in] frameset Target frameset container.
[in] frame_type Type of frame to retrieve.
[out] error Receives detailed error information if operation fails.
Returns
dt_frame* Requested frame (NULL if not found).
Referenced by dt::FrameSet::GetFrame().
DT_EXPORT dt_frame* dt_frameset_get_frame_by_index (const dt_frame * frameset, uint32_t index, dt_error ** error)
Retrieves frame by index from frameset.
Parameters
[in] frameset Target frameset container.
[in] index Position index in frameset.
[out] error Receives detailed error information if operation fails.
Returns
dt_frame* Requested frame (NULL if index invalid).
Referenced by dt::FrameSet::GetFrameByIndex().
DT_EXPORT dt_frame* dt_frameset_get_frame_by_name (const dt_frame * frameset, const char * name, dt_error ** error)
Retrieves frame by name from frameset.
Parameters
[in] frameset Target frameset container.
[in] name Name identifier of frame.
[out] error Receives detailed error information if operation fails.
Returns
dt_frame* Requested frame (NULL if not found).
Referenced by dt::FrameSet::GetFrameByName().
DT_EXPORT void dt_frameset_push_frame (dt_frame * frameset, const dt_frame * frame, dt_error ** error)
Adds frame to frameset container.
Attention
Replaces existing frames with same type.
Increments frame's reference count.
Parameters
[in] frameset Target frameset container.
[in] frame Frame to add.
[out] error Receives detailed error information if operation fails.
Referenced by dt::FrameSet::PushFrame().
DT_EXPORT uint32_t dt_frameset_get_count (const dt_frame * frameset, dt_error ** error)
Retrieves the number of frames contained in a frameset.
Parameters
[in] frameset Frameset container instance.
[out] error Receives detailed error information if operation fails.
Returns
Frame count within the frameset.
Referenced by dt::FrameSet::GetCount().
DT_EXPORT dt_frame* dt_frameset_get_depth_frame (const dt_frame * frameset, dt_error ** error)
Extracts the depth frame from a frameset.
Increases frame reference count automatically. Caller must release with dt_frame_release().
Parameters
[in] frameset Frameset container instance.
[out] error Receives detailed error information if operation fails.
Returns
Depth frame handle. Valid until explicitly released.
DT_EXPORT dt_frame* dt_frameset_get_color_frame (const dt_frame * frameset, dt_error ** error)
Extracts the color frame from a frameset.
Increases frame reference count automatically. Caller must release with dt_frame_release().
Parameters
[in] frameset Frameset container instance.
[out] error Receives detailed error information if operation fails.
Returns
Color frame handle. Valid until explicitly released.
DT_EXPORT dt_frame* dt_frameset_get_ir_frame (const dt_frame * frameset, dt_error ** error)
Extracts the infrared frame from a frameset.
Increases frame reference count automatically. Caller must release with dt_frame_release().
Parameters
[in] frameset Frameset container instance.
[out] error Receives detailed error information if operation fails.
Returns
Infrared frame handle. Valid until explicitly released.
DT_EXPORT dt_frame* dt_frameset_get_points_frame (const dt_frame * frameset, dt_error ** error)
Extracts the point cloud frame from a frameset.
Increases frame reference count automatically. Caller must release with dt_frame_release().
Parameters
[in] frameset Frameset container instance.
[out] error Receives detailed error information if operation fails.
Returns
Point cloud frame handle. Valid until explicitly released.