deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_pipeline.h File Reference
dt_pipeline.h File Reference
Unified interface for device control and computer vision processing.
#include "dt_types.h"
Functions
DT_EXPORT dt_pipeline * dt_create_pipeline (dt_error **error)
Creates a pipeline instance with default configuration.
DT_EXPORT dt_pipeline * dt_create_pipeline_with_device (const dt_device *dev, dt_error **error)
Creates a pipeline instance pre-configured with a specific device.
DT_EXPORT void dt_delete_pipeline (dt_pipeline *pipeline)
Releases all resources associated with a pipeline instance.
DT_EXPORT void dt_pipeline_start (dt_pipeline *pipeline, dt_error **error)
Starts streaming pipeline with default configuration.
DT_EXPORT void dt_pipeline_start_with_config (dt_pipeline *pipeline, const dt_config *config, dt_error **error)
Starts streaming pipeline with custom configuration.
DT_EXPORT void dt_pipeline_start_with_callback (dt_pipeline *pipeline, dt_frameset_callback callback, void *user_data, dt_error **error)
Starts pipeline with frame callback using default configuration.
DT_EXPORT void dt_pipeline_start_with_config_and_callback (dt_pipeline *pipeline, const dt_config *config, dt_frameset_callback callback, void *user_data, dt_error **error)
Starts pipeline with custom configuration and frame callback.
DT_EXPORT void dt_pipeline_stop (dt_pipeline *pipeline, dt_error **error)
Gracefully stops pipeline streaming and processing.
DT_EXPORT dt_config * dt_pipeline_get_config (const dt_pipeline *pipeline, dt_error **error)
Retrieves current pipeline configuration.
DT_EXPORT dt_frame * dt_pipeline_wait_for_frames (dt_pipeline *pipeline, uint32_t timeout_ms, dt_error **error)
Blocks until synchronized frameset is available or timeout occurs.
DT_EXPORT dt_device * dt_pipeline_get_device (const dt_pipeline *pipeline, dt_error **error)
Retrieves device bound to the pipeline.
DT_EXPORT dt_stream_profile_list * dt_pipeline_get_stream_profile_list (const dt_pipeline *pipeline, dt_sensor_type sensor_type, dt_error **error)
Retrieves active stream profiles for a sensor type.
DT_EXPORT dt_camera_param dt_pipeline_get_camera_param (dt_pipeline *pipeline, dt_error **error)
Retrieves current camera intrinsic parameters.
DT_EXPORT void dt_pipeline_enable_frame_sync (dt_pipeline *pipeline, dt_error **error)
Enables hardware-level frame synchronization across streams.
DT_EXPORT void dt_pipeline_disable_frame_sync (dt_pipeline *pipeline, dt_error **error)
Disables hardware-level frame synchronization.
Detailed Description
Unified interface for device control and computer vision processing.
Abstracts camera configuration, streaming, and vision module orchestration. Manages processing blocks that implement computer vision algorithms. Applications consume vision outputs while the pipeline handles threading and synchronization.
Definition in file dt_pipeline.h.
Function Documentation
DT_EXPORT dt_pipeline* dt_create_pipeline (dt_error ** error)
Creates a pipeline instance with default configuration.
Allocates resources for device management and vision processing modules.
Parameters
[out] error Receives detailed error information if operation fails.
Returns
New pipeline instance handle.
Referenced by dt::Pipeline::Pipeline().
DT_EXPORT dt_pipeline* dt_create_pipeline_with_device (const dt_device * dev, dt_error ** error)
Creates a pipeline instance pre-configured with a specific device.
Parameters
[in] dev Device instance to bind to the pipeline (must be valid and open).
[out] error Receives detailed error information if operation fails.
Returns
New pipeline instance handle.
Referenced by dt::Pipeline::Pipeline().
DT_EXPORT void dt_delete_pipeline (dt_pipeline * pipeline)
Releases all resources associated with a pipeline instance.
Stops active streams if running and deallocates internal resources.
Parameters
[in] pipeline Pipeline instance to destroy. Handle becomes invalid after call.
Referenced by dt::Pipeline::~Pipeline().
DT_EXPORT void dt_pipeline_start (dt_pipeline * pipeline, dt_error ** error)
Starts streaming pipeline with default configuration.
Initiates frame capture and processing loop. Captured frames are dispatched to:
Attached vision modules
Processing blocks
Frame consumers via dt_pipeline_wait_for_frames().
Parameters
[in] pipeline Initialized pipeline instance.
[out] error Receives detailed error information if operation fails.
DT_EXPORT void dt_pipeline_start_with_config (dt_pipeline * pipeline, const dt_config * config, dt_error ** error)
Starts streaming pipeline with custom configuration.
Parameters
[in] pipeline Initialized pipeline instance.
[in] config Runtime parameters for stream configuration (resolution, Fps, etc).
[out] error Receives detailed error information if operation fails.
Referenced by dt::Pipeline::Start().
DT_EXPORT void dt_pipeline_start_with_callback (dt_pipeline * pipeline, dt_frameset_callback callback, void * user_data, dt_error ** error)
Starts pipeline with frame callback using default configuration.
Note
Enabling callbacks disables dt_pipeline_wait_for_frames() for this pipeline.
Parameters
[in] pipeline Initialized pipeline instance.
[in] callback Function to invoke when complete frameset is available.
[in] user_data Context pointer passed to callback (may be NULL).
[out] error Receives detailed error information if operation fails.
DT_EXPORT void dt_pipeline_start_with_config_and_callback (dt_pipeline * pipeline, const dt_config * config, dt_frameset_callback callback, void * user_data, dt_error ** error)
Starts pipeline with custom configuration and frame callback.
Parameters
[in] pipeline Initialized pipeline instance.
[in] config Runtime parameters for stream configuration.
[in] callback Function to invoke when complete frameset is available.
[in] user_data Context pointer passed to callback (may be NULL).
[out] error Receives detailed error information if operation fails.
Referenced by dt::Pipeline::Start().
DT_EXPORT void dt_pipeline_stop (dt_pipeline * pipeline, dt_error ** error)
Gracefully stops pipeline streaming and processing.
Ensures in-flight frames are processed before shutdown.
Parameters
[in] pipeline Running pipeline instance.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Pipeline::Stop().
DT_EXPORT dt_config* dt_pipeline_get_config (const dt_pipeline * pipeline, dt_error ** error)
Retrieves current pipeline configuration.
Returns default configuration if no custom configuration was applied.
Parameters
[in] pipeline Initialized pipeline instance.
[out] error Receives detailed error information if operation fails.
Returns
Current configuration handle. Ownership remains with pipeline.
Referenced by dt::Pipeline::GetConfig().
DT_EXPORT dt_frame* dt_pipeline_wait_for_frames (dt_pipeline * pipeline, uint32_t timeout_ms, dt_error ** error)
Blocks until synchronized frameset is available or timeout occurs.
Returns time-aligned frames from all enabled streams. Drops frames if called slower than production rate. Maintain frame handles minimally to avoid resource exhaustion.
Parameters
[in] pipeline Running pipeline instance.
[in] timeout_ms Maximum wait time in milliseconds (0 = non-blocking).
[out] error Receives detailed error information if operation fails.
Returns
Frameset container handle. Release with dt_frame_release().
Referenced by dt::Pipeline::WaitForFrames().
DT_EXPORT dt_device* dt_pipeline_get_device (const dt_pipeline * pipeline, dt_error ** error)
Retrieves device bound to the pipeline.
Parameters
[in] pipeline Initialized pipeline instance.
[out] error Receives detailed error information if operation fails.
Returns
Bound device handle. Ownership remains with pipeline.
Referenced by dt::Pipeline::GetDevice().
DT_EXPORT dt_stream_profile_list* dt_pipeline_get_stream_profile_list (const dt_pipeline * pipeline, dt_sensor_type sensor_type, dt_error ** error)
Retrieves active stream profiles for a sensor type.
Parameters
[in] pipeline Initialized pipeline instance.
[in] sensor_type Target sensor (use dt_device_get_sensor_list() for valid types).
[out] error Receives detailed error information if operation fails.
Returns
List of active stream profiles. Release with dt_delete_stream_profile_list().
Referenced by dt::Pipeline::GetStreamProfileList().
DT_EXPORT dt_camera_param dt_pipeline_get_camera_param (dt_pipeline * pipeline, dt_error ** error)
Retrieves current camera intrinsic parameters.
Applies depth-to-color (D2C) adjustments if enabled in pipeline configuration.
Parameters
[in] pipeline Running pipeline instance.
[out] error Receives detailed error information if operation fails.
Returns
Camera intrinsic parameters. Returned structure is self-contained.
Referenced by dt::Pipeline::GetCameraParam().
DT_EXPORT void dt_pipeline_enable_frame_sync (dt_pipeline * pipeline, dt_error ** error)
Enables hardware-level frame synchronization across streams.
Uses frame timestamps for temporal alignment. Can be toggled dynamically during streaming.
Parameters
[in] pipeline Running pipeline instance.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Pipeline::EnableFrameSync().
DT_EXPORT void dt_pipeline_disable_frame_sync (dt_pipeline * pipeline, dt_error ** error)
Disables hardware-level frame synchronization.
Parameters
[in] pipeline Running pipeline instance.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Pipeline::DisableFrameSync().