deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_utils.h File Reference
dt_utils.h File Reference
Utility functions for coordinate transformations.
#include "dt_types.h"
Functions
DT_EXPORT bool dt_save_pointcloud_to_ply (const char *file_name, dt_frame *frame, bool save_binary, bool use_mesh, float mesh_threshold, dt_error **error)
Saves point cloud data to PLY file format.
DT_EXPORT bool dt_transform_3d_to_3d (const DtPoint3f source_point3f, DtExtrinsic extrinsic, DtPoint3f *target_point3f, dt_error **error)
Transforms a 3D point from source coordinate system to target coordinate system.
DT_EXPORT bool dt_transform_2d_to_3d (const DtPoint2f source_point2f, const float source_depth_pixel_value, const DtCameraIntrinsic source_intrinsic, DtExtrinsic extrinsic, DtPoint3f *target_point3f, dt_error **error)
Projects a 2D pixel with depth value to 3D point in target coordinate system.
DT_EXPORT bool dt_transform_3d_to_2d (const DtPoint3f source_point3f, const DtCameraIntrinsic target_intrinsic, const DtCameraDistortion target_distortion, DtExtrinsic extrinsic, DtPoint2f *target_point2f, dt_error **error)
Projects a 3D point to 2D pixel coordinates in target camera.
DT_EXPORT bool dt_transform_2d_to_2d (const DtPoint2f source_point2f, const float source_depth_pixel_value, const DtCameraIntrinsic source_intrinsic, const DtCameraDistortion source_distortion, const DtCameraIntrinsic target_intrinsic, const DtCameraDistortion target_distortion, DtExtrinsic extrinsic, DtPoint2f *target_point2f, dt_error **error)
Transforms a 2D pixel with depth to 2D pixel in target camera.
DT_EXPORT bool dt_colorize_depth (uint8_t *colored_depth, int rows, int cols, int range_min, int range_mid, int range_max, const uint16_t *depth_map, dt_error **error)
Detailed Description
Utility functions for coordinate transformations.
Definition in file dt_utils.h.
Function Documentation
DT_EXPORT bool dt_save_pointcloud_to_ply (const char * file_name, dt_frame * frame, bool save_binary, bool use_mesh, float mesh_threshold, dt_error ** error)
Saves point cloud data to PLY file format.
Parameters
[in] file_name Output file path for PLY file.
[in] frame Frame containing point cloud data.
[in] save_binary Use binary format (true) or ASCII format (false).
[in] use_mesh Generate mesh faces (true) or save as point cloud only (false).
[in] mesh_threshold Distance threshold for mesh generation (in millimeters).
[out] error Optional error object for capturing operation status.
Returns
bool True if save operation succeeded, false otherwise.
Referenced by dt::PointCloudHelper::SavePointcloudToPly().
DT_EXPORT bool dt_transform_3d_to_3d (const DtPoint3f source_point3f, DtExtrinsic extrinsic, DtPoint3f * target_point3f, dt_error ** error)
Transforms a 3D point from source coordinate system to target coordinate system.
Parameters
[in] source_point3f 3D point in source coordinate system.
[in] extrinsic Transform matrix from source to target coordinate system.
[out] target_point3f Output transformed 3D point in target coordinate system.
[out] error Optional error object for capturing operation status.
Returns
bool True if transform succeeded, false otherwise.
Referenced by dt::CoordinateTransformHelper::Transform3dto3d().
DT_EXPORT bool dt_transform_2d_to_3d (const DtPoint2f source_point2f, const float source_depth_pixel_value, const DtCameraIntrinsic source_intrinsic, DtExtrinsic extrinsic, DtPoint3f * target_point3f, dt_error ** error)
Projects a 2D pixel with depth value to 3D point in target coordinate system.
Parameters
[in] source_point2f 2D pixel coordinates in source camera.
[in] source_depth_pixel_value Depth value at pixel location (in millimeters).
[in] source_intrinsic Intrinsic parameters of source camera.
[in] extrinsic Transform from source to target coordinate system.
[out] target_point3f Output 3D point in target coordinate system.
[out] error Optional error object for capturing operation status.
Returns
bool True if projection succeeded, false otherwise.
Referenced by dt::CoordinateTransformHelper::Transform2dto3d().
DT_EXPORT bool dt_transform_3d_to_2d (const DtPoint3f source_point3f, const DtCameraIntrinsic target_intrinsic, const DtCameraDistortion target_distortion, DtExtrinsic extrinsic, DtPoint2f * target_point2f, dt_error ** error)
Projects a 3D point to 2D pixel coordinates in target camera.
Parameters
[in] source_point3f 3D point in source coordinate system.
[in] target_intrinsic Intrinsic parameters of target camera.
[in] target_distortion Distortion parameters of target camera.
[in] extrinsic Transform from source to target coordinate system.
[out] target_point2f Output 2D pixel coordinates in target camera.
[out] error Optional error object for capturing operation status.
Returns
bool True if projection succeeded, false otherwise.
Referenced by dt::CoordinateTransformHelper::Transform3dto2d().
DT_EXPORT bool dt_transform_2d_to_2d (const DtPoint2f source_point2f, const float source_depth_pixel_value, const DtCameraIntrinsic source_intrinsic, const DtCameraDistortion source_distortion, const DtCameraIntrinsic target_intrinsic, const DtCameraDistortion target_distortion, DtExtrinsic extrinsic, DtPoint2f * target_point2f, dt_error ** error)
Transforms a 2D pixel with depth to 2D pixel in target camera.
Parameters
[in] source_point2f 2D pixel coordinates in source camera.
[in] source_depth_pixel_value Depth value at pixel location (in millimeters).
[in] source_intrinsic Intrinsic parameters of source camera.
[in] source_distortion Distortion parameters of source camera.
[in] target_intrinsic Intrinsic parameters of target camera.
[in] target_distortion Distortion parameters of target camera.
[in] extrinsic Transform from source to target coordinate system.
[out] target_point2f Output 2D pixel coordinates in target camera.
[out] error Optional error object for capturing operation status.
Returns
bool True if transform succeeded, false otherwise.
Referenced by dt::CoordinateTransformHelper::Transform2dto2d().
DT_EXPORT bool dt_colorize_depth (uint8_t * colored_depth, int rows, int cols, int range_min, int range_mid, int range_max, const uint16_t * depth_map, dt_error ** error)
Colormap the depth map on given colormap_table Function referenced from Stellar Visualizer
Parameters
[out] colored_depth Colored depth map, memory needs to be applied externally.
[in] rows Rows of depth map.
[in] cols Columns of depth map.
[in] range_min Minimum mapping range of depth map.
[in] range_mid Middle value of mapping range of depth map.
[in] range_max Maximum mapping range of depth map.
[in] depth_map Depth map to be color mapped.
[out] error Optional error object for capturing operation status.
Returns
bool True if transformation succeeded, false otherwise.
Referenced by dt::Visualizer::ColorizeDepth().