deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_error.h File Reference
dt_error.h File Reference
Defines error handling functions and structures for the SDK. Provides interfaces to create, query, and manage error objects.
#include "dt_types.h"
Functions
DT_EXPORT dt_error * dt_create_error (dt_status status, const char *message, const char *function, const char *args, dt_exception_type exception_type)
Creates a new error object with detailed diagnostic information.
DT_EXPORT void dt_delete_error (dt_error *error)
Releases resources associated with an error object.
DT_EXPORT dt_status dt_error_get_status (const dt_error *error)
Retrieves the status code from an error object.
DT_EXPORT const char * dt_error_get_message (const dt_error *error)
Retrieves the descriptive message from an error object.
DT_EXPORT const char * dt_error_get_function (const dt_error *error)
Identifies the function where error originated.
DT_EXPORT const char * dt_error_get_args (const dt_error *error)
Retrieves arguments present during function failure.
DT_EXPORT dt_exception_type dt_error_get_exception_type (const dt_error *error)
Identifies the exception category causing the error.
Detailed Description
Defines error handling functions and structures for the SDK. Provides interfaces to create, query, and manage error objects.
Definition in file dt_error.h.
Function Documentation
DT_EXPORT dt_error* dt_create_error (dt_status status, const char * message, const char * function, const char * args, dt_exception_type exception_type)
Creates a new error object with detailed diagnostic information.
Parameters
[in] status Error status code indicating failure type.
[in] message Human-readable error description.
[in] function Name of the API function where error occurred.
[in] args Arguments passed to the function when error occurred.
[in] exception_type Specific exception category triggering the error.
Returns
Pointer to newly created error object. Caller assumes ownership.
Referenced by dt::StreamProfileFactory::Create().
DT_EXPORT void dt_delete_error (dt_error * error)
Releases resources associated with an error object.
Parameters
[in] error Target error object to destroy. Caller must set pointer to NULL after deletion.
Referenced by dt::Error::Handle(), and dt::Error::~Error().
DT_EXPORT dt_status dt_error_get_status (const dt_error * error)
Retrieves the status code from an error object.
Parameters
[in] error Target error object to query.
Returns
Error status code indicating failure type.
DT_EXPORT const char* dt_error_get_message (const dt_error * error)
Retrieves the descriptive message from an error object.
Parameters
[in] error Target error object to query.
Returns
Human-readable error description (null-terminated string).
DT_EXPORT const char* dt_error_get_function (const dt_error * error)
Identifies the function where error originated.
Parameters
[in] error Target error object to query.
Returns
Name of the API function where failure occurred.
DT_EXPORT const char* dt_error_get_args (const dt_error * error)
Retrieves arguments present during function failure.
Parameters
[in] error Target error object to query.
Returns
Arguments passed to the function when error occurred.
DT_EXPORT dt_exception_type dt_error_get_exception_type (const dt_error * error)
Identifies the exception category causing the error.
Parameters
[in] error Target error object to query.
Returns
Specific exception type triggering the failure.