deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_sensor.h File Reference
dt_sensor.h File Reference
Sensor management interfaces for configuring, controlling, and monitoring sensor streams.
#include "dt_types.h"
Functions
DT_EXPORT uint32_t dt_sensor_list_get_count (const dt_sensor_list *sensor_list, dt_error **error)
Retrieves the number of sensors in a sensor list.
DT_EXPORT dt_sensor_type dt_sensor_list_get_sensor_type (const dt_sensor_list *sensor_list, uint32_t index, dt_error **error)
Retrieves sensor type at specified index in sensor list.
DT_EXPORT dt_sensor * dt_sensor_list_get_sensor_by_type (const dt_sensor_list *sensor_list, dt_sensor_type sensor_type, dt_error **error)
Retrieves sensor by type from sensor list.
DT_EXPORT dt_sensor * dt_sensor_list_get_sensor (const dt_sensor_list *sensor_list, uint32_t index, dt_error **error)
Retrieves sensor by index from sensor list.
DT_EXPORT void dt_delete_sensor_list (dt_sensor_list *sensor_list)
Releases resources associated with a sensor list.
DT_EXPORT dt_sensor_type dt_sensor_get_type (const dt_sensor *sensor, dt_error **error)
Retrieves type identifier of a sensor.
DT_EXPORT dt_stream_profile_list * dt_sensor_get_stream_profile_list (const dt_sensor *sensor, dt_error **error)
Retrieves available streaming configurations for a sensor.
DT_EXPORT dt_filter_list * dt_sensor_create_recommended_filter_list (const dt_sensor *sensor, dt_error **error)
Generates recommended processing filters for a sensor.
DT_EXPORT void dt_sensor_start (dt_sensor *sensor, const dt_stream_profile *profile, dt_frame_callback callback, void *user_data, dt_error **error)
Starts sensor streaming with specified configuration and data callback.
DT_EXPORT void dt_sensor_switch_profile (dt_sensor *sensor, dt_stream_profile *profile, dt_error **error)
Dynamically changes streaming configuration.
DT_EXPORT void dt_sensor_stop (dt_sensor *sensor, dt_error **error)
Stops active sensor streaming.
DT_EXPORT void dt_delete_sensor (dt_sensor *sensor)
Releases resources associated with a sensor.
Detailed Description
Sensor management interfaces for configuring, controlling, and monitoring sensor streams.
Provides functionality to query sensor capabilities, manage streaming profiles, control data flow, and obtain recommended processing filters. Supports multiple sensor types and configurations.
Definition in file dt_sensor.h.
Function Documentation
DT_EXPORT uint32_t dt_sensor_list_get_count (const dt_sensor_list * sensor_list, dt_error ** error)
Retrieves the number of sensors in a sensor list.
Parameters
[in] sensor_list Sensor list container instance.
[out] error Receives detailed error information if operation fails.
Returns
Number of sensors contained in the list.
Referenced by dt::SensorList::GetCount().
DT_EXPORT dt_sensor_type dt_sensor_list_get_sensor_type (const dt_sensor_list * sensor_list, uint32_t index, dt_error ** error)
Retrieves sensor type at specified index in sensor list.
Parameters
[in] sensor_list Sensor list container instance.
[in] index Zero-based position in sensor list (must be < list count).
[out] error Receives detailed error information if operation fails.
Returns
Sensor type identifier.
Referenced by dt::SensorList::GetSensorType().
DT_EXPORT dt_sensor* dt_sensor_list_get_sensor_by_type (const dt_sensor_list * sensor_list, dt_sensor_type sensor_type, dt_error ** error)
Retrieves sensor by type from sensor list.
Parameters
[in] sensor_list Sensor list container instance.
[in] sensor_type Target sensor type to locate.
[out] error Receives detailed error information if operation fails.
Returns
Sensor handle if found, NULL if not present.
Referenced by dt::SensorList::GetSensor().
DT_EXPORT dt_sensor* dt_sensor_list_get_sensor (const dt_sensor_list * sensor_list, uint32_t index, dt_error ** error)
Retrieves sensor by index from sensor list.
Parameters
[in] sensor_list Sensor list container instance.
[in] index Zero-based position in sensor list (must be < list count).
[out] error Receives detailed error information if operation fails.
Returns
Sensor handle at specified position.
Referenced by dt::SensorList::GetSensor().
DT_EXPORT void dt_delete_sensor_list (dt_sensor_list * sensor_list)
Releases resources associated with a sensor list.
Parameters
[in] sensor_list Sensor list instance to destroy.
Referenced by dt::SensorList::~SensorList().
DT_EXPORT dt_sensor_type dt_sensor_get_type (const dt_sensor * sensor, dt_error ** error)
Retrieves type identifier of a sensor.
Parameters
[in] sensor Sensor instance.
[out] error Receives detailed error information if operation fails.
Returns
Sensor type identifier.
Referenced by dt::Sensor::GetType().
DT_EXPORT dt_stream_profile_list* dt_sensor_get_stream_profile_list (const dt_sensor * sensor, dt_error ** error)
Retrieves available streaming configurations for a sensor.
Parameters
[in] sensor Sensor instance.
[out] error Receives detailed error information if operation fails.
Returns
List of supported stream profiles. Release with dt_delete_stream_profile_list().
Referenced by dt::Sensor::GetStreamProfileList().
DT_EXPORT dt_filter_list* dt_sensor_create_recommended_filter_list (const dt_sensor * sensor, dt_error ** error)
Generates recommended processing filters for a sensor.
Parameters
[in] sensor Sensor instance.
[out] error Receives detailed error information if operation fails.
Returns
Filter list handle. Release with dt_delete_filter_list().
Referenced by dt::Sensor::CreateRecommendedFilters().
DT_EXPORT void dt_sensor_start (dt_sensor * sensor, const dt_stream_profile * profile, dt_frame_callback callback, void * user_data, dt_error ** error)
Starts sensor streaming with specified configuration and data callback.
Parameters
[in] sensor Sensor instance to activate.
[in] profile Streaming configuration to apply.
[in] callback Frame data notification callback (may not be NULL).
[in] user_data Context pointer passed to callback (may be NULL).
[out] error Receives detailed error information if operation fails.
Referenced by dt::Sensor::Start().
DT_EXPORT void dt_sensor_switch_profile (dt_sensor * sensor, dt_stream_profile * profile, dt_error ** error)
Dynamically changes streaming configuration.
Precondition
Sensor must be in active streaming state.
Parameters
[in] sensor Sensor instance to reconfigure.
[in] profile New streaming configuration to apply.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Sensor::SwitchProfile().
DT_EXPORT void dt_sensor_stop (dt_sensor * sensor, dt_error ** error)
Stops active sensor streaming.
Parameters
[in] sensor Sensor instance to deactivate.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Sensor::Stop().
DT_EXPORT void dt_delete_sensor (dt_sensor * sensor)
Releases resources associated with a sensor.
Parameters
[in] sensor Sensor instance to destroy.
Referenced by dt::Sensor::operator=(), and dt::Sensor::~Sensor().