deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_logger.h File Reference
dt_logger.h File Reference
Log management interface for configuring global logging behavior.
#include "dt_types.h"
Functions
DT_EXPORT void dt_set_logger_severity (dt_log_severity severity, dt_error **error)
Sets the global minimum severity threshold for all log outputs.
DT_EXPORT void dt_set_logger_to_console (dt_log_severity severity, dt_error **error)
Configures logging output to the system console/terminal.
DT_EXPORT void dt_set_logger_to_file (dt_log_severity severity, const char *directory, dt_error **error)
Configures logging output to disk files in specified directory.
DT_EXPORT void dt_set_logger_to_callback (dt_log_severity severity, dt_log_callback callback, void *user_data, dt_error **error)
Registers a custom callback handler for log processing.
Detailed Description
Log management interface for configuring global logging behavior.
Provides functions to control log output destinations and severity thresholds.
Definition in file dt_logger.h.
Function Documentation
DT_EXPORT void dt_set_logger_severity (dt_log_severity severity, dt_error ** error)
Sets the global minimum severity threshold for all log outputs.
This setting affects console, file, and callback outputs simultaneously. Messages below the specified severity level will be discarded globally.
Parameters
[in] severity Minimum severity level to enforce globally.
[out] error Pointer to receive error details. Initialized to NULL before call, populated with error object on failure. Caller must release memory.
Referenced by dt::Logger::SetLoggerSeverity().
DT_EXPORT void dt_set_logger_to_console (dt_log_severity severity, dt_error ** error)
Configures logging output to the system console/terminal.
Enables real-time log display in the terminal with severity-based filtering. Has no effect if the severity level is below the global minimum threshold.
Parameters
[in] severity Minimum severity level for console output.
[out] error Pointer to receive error details. Initialized to NULL before call, populated with error object on failure. Caller must release memory.
Referenced by dt::Logger::SetLoggerToConsole().
DT_EXPORT void dt_set_logger_to_file (dt_log_severity severity, const char * directory, dt_error ** error)
Configures logging output to disk files in specified directory.
Creates daily rotating log files with automatic timestamp naming. Retains existing directory path if empty string is provided.
Parameters
[in] severity Minimum severity level for file output.
[in] directory Target directory for log files. Empty string preserves current setting.
[out] error Pointer to receive error details. Initialized to NULL before call, populated with error object on failure. Caller must release memory.
Referenced by dt::Logger::SetLoggerToFile().
DT_EXPORT void dt_set_logger_to_callback (dt_log_severity severity, dt_log_callback callback, void * user_data, dt_error ** error)
Registers a custom callback handler for log processing.
The callback receives formatted log messages matching the specified severity. User-defined context data is passed through to the callback invocation.
Parameters
[in] severity Minimum severity level to trigger callback.
[in] callback Function pointer to the log handler implementation.
[in] user_data Context pointer passed through to callback (may be NULL).
[out] error Pointer to receive error details. Initialized to NULL before call, populated with error object on failure. Caller must release memory.
Referenced by dt::Logger::SetLoggerToCallback().