deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_context.h File Reference
dt_context.h File Reference
Manages SDK runtime environment, handles resource allocation/release, and coordinates multi-device operations including enumeration and monitoring.
#include "dt_types.h"
Functions
DT_EXPORT dt_context * dt_create_context (dt_error **error)
Creates a context object using the default configuration file.
DT_EXPORT dt_context * dt_create_context_with_config (const char *config_file_path, dt_error **error)
Creates a context object with a specified configuration file.
DT_EXPORT void dt_delete_context (dt_context *context)
Releases all resources associated with a context object.
DT_EXPORT dt_device_list * dt_query_device_list (dt_context *context, dt_error **error)
Retrieves a list of enumerated devices.
DT_EXPORT dt_device * dt_create_net_device (dt_context *context, const char *address, uint16_t port, dt_error **error)
Creates a network device instance for communication.
DT_EXPORT void dt_enable_net_device_enumeration (dt_context *context, bool enable, dt_error **error)
Enables/disables automatic network device discovery.
DT_EXPORT void dt_set_device_changed_callback (dt_context *context, dt_device_changed_callback callback, void *user_data, dt_error **error)
Registers a callback for device connection/disconnection events.
DT_EXPORT void dt_enable_device_clock_sync (dt_context *context, uint64_t repeat_interval_msec, dt_error **error)
Synchronizes host-device clocks across all created devices.
DT_EXPORT void dt_set_uvc_backend_type (dt_context *context, dt_uvc_backend_type backend_type, dt_error **error)
Selects UVC backend implementation for Linux environments.
Detailed Description
Manages SDK runtime environment, handles resource allocation/release, and coordinates multi-device operations including enumeration and monitoring.
Definition in file dt_context.h.
Function Documentation
DT_EXPORT dt_context* dt_create_context (dt_error ** error)
Creates a context object using the default configuration file.
Parameters
[out] error Receives detailed error information if operation fails.
Returns
Pointer to the initialized context object. Returns NULL on failure.
DT_EXPORT dt_context* dt_create_context_with_config (const char * config_file_path, dt_error ** error)
Creates a context object with a specified configuration file.
Parameters
[in] config_file_path Path to custom configuration file. If NULL, uses default configuration.
[out] error Receives detailed error information if operation fails.
Returns
Pointer to the initialized context object. Returns NULL on failure.
Referenced by dt::Context::Context().
DT_EXPORT void dt_delete_context (dt_context * context)
Releases all resources associated with a context object.
Parameters
[in] context Target context object to destroy. If NULL, no operation is performed.
Referenced by dt::Context::~Context().
DT_EXPORT dt_device_list* dt_query_device_list (dt_context * context, dt_error ** error)
Retrieves a list of enumerated devices.
Parameters
[in] context Initialized context object.
[out] error Receives detailed error information if operation fails.
Returns
Pointer to device list. Must be released by caller. Returns NULL on failure.
Referenced by dt::Context::QueryDeviceList().
DT_EXPORT dt_device* dt_create_net_device (dt_context * context, const char * address, uint16_t port, dt_error ** error)
Creates a network device instance for communication.
Parameters
[in] context Initialized context object.
[in] address IP address of the target device.
[in] port Network port of the target device.
[out] error Receives detailed error information if operation fails.
Returns
Pointer to created device object. Returns NULL on failure.
Referenced by dt::Context::CreateNetDevice().
DT_EXPORT void dt_enable_net_device_enumeration (dt_context * context, bool enable, dt_error ** error)
Enables/disables automatic network device discovery.
Attention
Discovered devices require host-subnet alignment for connectivity.
Default behavior can be configured via settings.
Parameters
[in] context Initialized context object.
[in] enable true activates discovery, false disables it.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Context::EnableNetDeviceEnumeration().
DT_EXPORT void dt_set_device_changed_callback (dt_context * context, dt_device_changed_callback callback, void * user_data, dt_error ** error)
Registers a callback for device connection/disconnection events.
Attention
Supports multiple callbacks. Each call adds a new callback.
Caller must release returned device lists in callback parameters.
Parameters
[in] context Initialized context object.
[in] callback Function pointer to event handler.
[in] user_data Custom user data passed to callback function.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Context::SetDeviceChangedCallback().
DT_EXPORT void dt_enable_device_clock_sync (dt_context * context, uint64_t repeat_interval_msec, dt_error ** error)
Synchronizes host-device clocks across all created devices.
Parameters
[in] context Initialized context object.
[in] repeat_interval_msec Resynchronization interval in milliseconds. Value 0 performs single synchronization.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Context::EnableDeviceClockSync().
DT_EXPORT void dt_set_uvc_backend_type (dt_context * context, dt_uvc_backend_type backend_type, dt_error ** error)
Selects UVC backend implementation for Linux environments.
Attention
Linux exclusive feature. Affects subsequently created devices.
Parameters
[in] context Initialized context object.
[in] backend_type Preferred backend implementation type.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Context::SetUvcBackendType().