deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_stream_profile.h File Reference
dt_stream_profile.h File Reference
Defines stream profile types and operations for retrieving stream characteristics including dimensions, frame rates, and data formats.
#include "dt_types.h"
Functions
DT_EXPORT dt_stream_profile * dt_create_stream_profile (dt_stream_type type, dt_format format, dt_error **error)
Creates a generic stream profile object.
DT_EXPORT dt_stream_profile * dt_create_video_stream_profile (dt_stream_type type, dt_format format, uint32_t width, uint32_t height, uint32_t fps, dt_error **error)
Creates a video-specific stream profile.
DT_EXPORT dt_stream_profile * dt_create_accel_stream_profile (dt_accel_full_scale_range full_scale_range, dt_accel_sample_rate sample_rate, dt_error **error)
Creates an accelerometer-specific stream profile.
DT_EXPORT dt_stream_profile * dt_create_gyro_stream_profile (dt_gyro_full_scale_range full_scale_range, dt_gyro_sample_rate sample_rate, dt_error **error)
Creates a gyroscope-specific stream profile.
DT_EXPORT dt_stream_profile * dt_create_palm_stream_profile (dt_error **error)
Creates a palm-specific stream profile.
DT_EXPORT dt_stream_profile * dt_create_stream_profile_from_other_stream_profile (const dt_stream_profile *src_profile, dt_error **error)
Creates a stream profile by copying an existing profile.
DT_EXPORT dt_stream_profile * dt_create_stream_profile_with_new_format (const dt_stream_profile *profile, dt_format new_format, dt_error **error)
Creates a new stream profile by modifying the format of an existing profile.
DT_EXPORT void dt_delete_stream_profile (const dt_stream_profile *profile)
Releases resources associated with a stream profile.
DT_EXPORT dt_format dt_stream_profile_get_format (const dt_stream_profile *profile, dt_error **error)
Retrieves the data format of a stream profile.
DT_EXPORT void dt_stream_profile_set_format (dt_stream_profile *profile, dt_format format, dt_error **error)
Updates the data format of a stream profile.
DT_EXPORT dt_stream_type dt_stream_profile_get_type (const dt_stream_profile *profile, dt_error **error)
Retrieves the stream type identifier.
DT_EXPORT void dt_stream_profile_set_type (const dt_stream_profile *profile, dt_stream_type type, dt_error **error)
Updates the stream type identifier.
DT_EXPORT dt_extrinsic dt_stream_profile_get_extrinsic_to (const dt_stream_profile *source, dt_stream_profile *target, dt_error **error)
Retrieves the extrinsic transformation between two sensor streams.
DT_EXPORT void dt_stream_profile_set_extrinsic_to (dt_stream_profile *source, const dt_stream_profile *target, dt_extrinsic extrinsic, dt_error **error)
Configures the extrinsic transformation between two sensor streams.
DT_EXPORT void dt_stream_profile_set_extrinsic_to_type (dt_stream_profile *source, const dt_stream_type type, dt_extrinsic extrinsic, dt_error **error)
Configures the extrinsic transformation to a stream type.
DT_EXPORT uint32_t dt_video_stream_profile_get_fps (const dt_stream_profile *profile, dt_error **error)
Retrieves frame rate for video streams.
DT_EXPORT uint32_t dt_video_stream_profile_get_width (const dt_stream_profile *profile, dt_error **error)
Retrieves frame width for video streams.
DT_EXPORT void dt_video_stream_profile_set_width (dt_stream_profile *profile, uint32_t width, dt_error **error)
Updates frame width for video streams.
DT_EXPORT uint32_t dt_video_stream_profile_get_height (const dt_stream_profile *profile, dt_error **error)
Retrieves frame height for video streams.
DT_EXPORT void dt_video_stream_profile_set_height (dt_stream_profile *profile, uint32_t height, dt_error **error)
Updates frame height for video streams.
DT_EXPORT dt_camera_intrinsic dt_video_stream_profile_get_intrinsic (const dt_stream_profile *profile, dt_error **error)
Retrieves camera intrinsic parameters.
DT_EXPORT void dt_video_stream_profile_set_intrinsic (dt_stream_profile *profile, dt_camera_intrinsic intrinsic, dt_error **error)
Configures camera intrinsic parameters.
DT_EXPORT dt_camera_distortion dt_video_stream_profile_get_distortion (const dt_stream_profile *profile, dt_error **error)
Retrieves lens distortion parameters.
DT_EXPORT void dt_video_stream_profile_set_distortion (dt_stream_profile *profile, dt_camera_distortion distortion, dt_error **error)
Configures lens distortion parameters.
DT_EXPORT dt_accel_full_scale_range dt_accel_stream_profile_get_full_scale_range (const dt_stream_profile *profile, dt_error **error)
Retrieves full-scale measurement range.
DT_EXPORT dt_accel_sample_rate dt_accel_stream_profile_get_sample_rate (const dt_stream_profile *profile, dt_error **error)
Retrieves data sampling rate.
DT_EXPORT dt_accel_intrinsic dt_accel_stream_profile_get_intrinsic (const dt_stream_profile *profile, dt_error **error)
Retrieves sensor intrinsic calibration.
DT_EXPORT void dt_accel_stream_profile_set_intrinsic (dt_stream_profile *profile, dt_accel_intrinsic intrinsic, dt_error **error)
Configures sensor intrinsic calibration.
DT_EXPORT dt_gyro_full_scale_range dt_gyro_stream_profile_get_full_scale_range (const dt_stream_profile *profile, dt_error **error)
Retrieves full-scale angular range.
DT_EXPORT dt_gyro_sample_rate dt_gyro_stream_profile_get_sample_rate (const dt_stream_profile *profile, dt_error **error)
Retrieves data sampling rate.
DT_EXPORT dt_gyro_intrinsic dt_gyro_stream_get_intrinsic (const dt_stream_profile *profile, dt_error **error)
Retrieves sensor intrinsic calibration.
DT_EXPORT void dt_gyro_stream_set_intrinsic (dt_stream_profile *profile, dt_gyro_intrinsic intrinsic, dt_error **error)
Configures sensor intrinsic calibration.
DT_EXPORT uint32_t dt_stream_profile_list_get_count (const dt_stream_profile_list *profile_list, dt_error **error)
Retrieves number of profiles in a list.
DT_EXPORT dt_stream_profile * dt_stream_profile_list_get_profile (const dt_stream_profile_list *profile_list, int index, dt_error **error)
Retrieves profile by index.
DT_EXPORT dt_stream_profile * dt_stream_profile_list_get_video_stream_profile (const dt_stream_profile_list *profile_list, int width, int height, dt_format format, int fps, dt_error **error)
Finds matching video profile from a list.
DT_EXPORT dt_stream_profile * dt_stream_profile_list_get_accel_stream_profile (const dt_stream_profile_list *profile_list, dt_accel_full_scale_range full_scale_range, dt_accel_sample_rate sample_rate, dt_error **error)
Finds matching accelerometer profile from a list.
DT_EXPORT dt_stream_profile * dt_stream_profile_list_get_gyro_stream_profile (const dt_stream_profile_list *profile_list, dt_gyro_full_scale_range full_scale_range, dt_gyro_sample_rate sample_rate, dt_error **error)
Finds matching gyroscope profile from a list.
DT_EXPORT dt_stream_profile * dt_stream_profile_list_get_palm_stream_profile (const dt_stream_profile_list *profile_list, dt_error **error)
Finds matching palm profile from a list.
DT_EXPORT void dt_delete_stream_profile_list (const dt_stream_profile_list *profile_list)
Releases a stream profile list and all contained profiles.
Detailed Description
Defines stream profile types and operations for retrieving stream characteristics including dimensions, frame rates, and data formats.
Definition in file dt_stream_profile.h.
Function Documentation
DT_EXPORT dt_stream_profile* dt_create_stream_profile (dt_stream_type type, dt_format format, dt_error ** error)
Creates a generic stream profile object.
Parameters
[in] type Stream type identifier.
[in] format Stream data format.
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* New stream profile instance.
DT_EXPORT dt_stream_profile* dt_create_video_stream_profile (dt_stream_type type, dt_format format, uint32_t width, uint32_t height, uint32_t fps, dt_error ** error)
Creates a video-specific stream profile.
Parameters
[in] type Video stream type identifier.
[in] format Video pixel format.
[in] width Frame width in pixels.
[in] height Frame height in pixels.
[in] fps Frames per second.
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* New video stream profile instance.
DT_EXPORT dt_stream_profile* dt_create_accel_stream_profile (dt_accel_full_scale_range full_scale_range, dt_accel_sample_rate sample_rate, dt_error ** error)
Creates an accelerometer-specific stream profile.
Parameters
[in] full_scale_range Measurement range in g-units.
[in] sample_rate Data sampling rate in Hz.
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* New accelerometer stream profile instance.
DT_EXPORT dt_stream_profile* dt_create_gyro_stream_profile (dt_gyro_full_scale_range full_scale_range, dt_gyro_sample_rate sample_rate, dt_error ** error)
Creates a gyroscope-specific stream profile.
Parameters
[in] full_scale_range Angular measurement range in degrees per second.
[in] sample_rate Data sampling rate in Hz.
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* New gyroscope stream profile instance.
DT_EXPORT dt_stream_profile* dt_create_palm_stream_profile (dt_error ** error)
Creates a palm-specific stream profile.
Parameters
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* New palm stream profile instance.
DT_EXPORT dt_stream_profile* dt_create_stream_profile_from_other_stream_profile (const dt_stream_profile * src_profile, dt_error ** error)
Creates a stream profile by copying an existing profile.
Parameters
[in] src_profile Source profile to duplicate.
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* Cloned stream profile instance.
DT_EXPORT dt_stream_profile* dt_create_stream_profile_with_new_format (const dt_stream_profile * profile, dt_format new_format, dt_error ** error)
Creates a new stream profile by modifying the format of an existing profile.
Parameters
[in] profile Source profile to clone.
[in] new_format Target data format for new profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* New profile with updated format.
DT_EXPORT void dt_delete_stream_profile (const dt_stream_profile * profile)
Releases resources associated with a stream profile.
Parameters
[in] profile Target profile to destroy.
Referenced by dt::StreamProfile::operator=(), and dt::StreamProfile::~StreamProfile().
DT_EXPORT dt_format dt_stream_profile_get_format (const dt_stream_profile * profile, dt_error ** error)
Retrieves the data format of a stream profile.
Parameters
[in] profile Target stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_format Current data format.
Referenced by dt::StreamProfile::GetFormat().
DT_EXPORT void dt_stream_profile_set_format (dt_stream_profile * profile, dt_format format, dt_error ** error)
Updates the data format of a stream profile.
Parameters
[in] profile Target stream profile.
[in] format New data format.
[out] error Receives detailed error information if operation fails.
DT_EXPORT dt_stream_type dt_stream_profile_get_type (const dt_stream_profile * profile, dt_error ** error)
Retrieves the stream type identifier.
Parameters
[in] profile Target stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_type Current stream type.
Referenced by dt::StreamProfileFactory::Create(), and dt::StreamProfile::GetType().
DT_EXPORT void dt_stream_profile_set_type (const dt_stream_profile * profile, dt_stream_type type, dt_error ** error)
Updates the stream type identifier.
Parameters
[in] profile Target stream profile.
[in] type New stream type.
[out] error Receives detailed error information if operation fails.
DT_EXPORT dt_extrinsic dt_stream_profile_get_extrinsic_to (const dt_stream_profile * source, dt_stream_profile * target, dt_error ** error)
Retrieves the extrinsic transformation between two sensor streams.
Parameters
[in] source Source stream profile.
[in] target Target stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_extrinsic Transform matrix from source to target.
Referenced by dt::StreamProfile::GetExtrinsicTo().
DT_EXPORT void dt_stream_profile_set_extrinsic_to (dt_stream_profile * source, const dt_stream_profile * target, dt_extrinsic extrinsic, dt_error ** error)
Configures the extrinsic transformation between two sensor streams.
Parameters
[in] source Source stream profile.
[in] target Target stream profile.
[in] extrinsic Transform matrix from source to target.
[out] error Receives detailed error information if operation fails.
Referenced by dt::StreamProfile::BindExtrinsicTo().
DT_EXPORT void dt_stream_profile_set_extrinsic_to_type (dt_stream_profile * source, const dt_stream_type type, dt_extrinsic extrinsic, dt_error ** error)
Configures the extrinsic transformation to a stream type.
Parameters
[in] source Source stream profile.
[in] type Target stream type identifier.
[in] extrinsic Transform matrix to target type.
[out] error Receives detailed error information if operation fails.
Referenced by dt::StreamProfile::BindExtrinsicTo().
DT_EXPORT uint32_t dt_video_stream_profile_get_fps (const dt_stream_profile * profile, dt_error ** error)
Retrieves frame rate for video streams.
Parameters
[in] profile Target video stream profile.
[out] error Receives detailed error information if operation fails.
Returns
uint32_t Current frames per second.
Referenced by dt::VideoStreamProfile::GetFps().
DT_EXPORT uint32_t dt_video_stream_profile_get_width (const dt_stream_profile * profile, dt_error ** error)
Retrieves frame width for video streams.
Parameters
[in] profile Target video stream profile.
[out] error Receives detailed error information if operation fails.
Returns
uint32_t Current frame width in pixels.
Referenced by dt::VideoStreamProfile::GetWidth().
DT_EXPORT void dt_video_stream_profile_set_width (dt_stream_profile * profile, uint32_t width, dt_error ** error)
Updates frame width for video streams.
Parameters
[in] profile Target video stream profile.
[in] width New frame width in pixels.
[out] error Receives detailed error information if operation fails.
DT_EXPORT uint32_t dt_video_stream_profile_get_height (const dt_stream_profile * profile, dt_error ** error)
Retrieves frame height for video streams.
Parameters
[in] profile Target video stream profile.
[out] error Receives detailed error information if operation fails.
Returns
uint32_t Current frame height in pixels.
Referenced by dt::VideoStreamProfile::GetHeight().
DT_EXPORT void dt_video_stream_profile_set_height (dt_stream_profile * profile, uint32_t height, dt_error ** error)
Updates frame height for video streams.
Parameters
[in] profile Target video stream profile.
[in] height New frame height in pixels.
[out] error Receives detailed error information if operation fails.
DT_EXPORT dt_camera_intrinsic dt_video_stream_profile_get_intrinsic (const dt_stream_profile * profile, dt_error ** error)
Retrieves camera intrinsic parameters.
Parameters
[in] profile Target video stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_camera_intrinsic Camera intrinsic matrix.
Referenced by dt::VideoStreamProfile::GetIntrinsic().
DT_EXPORT void dt_video_stream_profile_set_intrinsic (dt_stream_profile * profile, dt_camera_intrinsic intrinsic, dt_error ** error)
Configures camera intrinsic parameters.
Parameters
[in] profile Target video stream profile.
[in] intrinsic New intrinsic matrix.
[out] error Receives detailed error information if operation fails.
Referenced by dt::VideoStreamProfile::SetIntrinsic().
DT_EXPORT dt_camera_distortion dt_video_stream_profile_get_distortion (const dt_stream_profile * profile, dt_error ** error)
Retrieves lens distortion parameters.
Parameters
[in] profile Target video stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_camera_distortion Distortion coefficients.
Referenced by dt::VideoStreamProfile::GetDistortion().
DT_EXPORT void dt_video_stream_profile_set_distortion (dt_stream_profile * profile, dt_camera_distortion distortion, dt_error ** error)
Configures lens distortion parameters.
Parameters
[in] profile Target video stream profile.
[in] distortion New distortion coefficients.
[out] error Receives detailed error information if operation fails.
Referenced by dt::VideoStreamProfile::SetDistortion().
DT_EXPORT dt_accel_full_scale_range dt_accel_stream_profile_get_full_scale_range (const dt_stream_profile * profile, dt_error ** error)
Retrieves full-scale measurement range.
Parameters
[in] profile Target accelerometer stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_accel_full_scale_range Current measurement range.
Referenced by dt::AccelStreamProfile::GetFullScaleRange().
DT_EXPORT dt_accel_sample_rate dt_accel_stream_profile_get_sample_rate (const dt_stream_profile * profile, dt_error ** error)
Retrieves data sampling rate.
Parameters
[in] profile Target accelerometer stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_accel_sample_rate Current sampling frequency (Hz).
Referenced by dt::AccelStreamProfile::GetSampleRate().
DT_EXPORT dt_accel_intrinsic dt_accel_stream_profile_get_intrinsic (const dt_stream_profile * profile, dt_error ** error)
Retrieves sensor intrinsic calibration.
Parameters
[in] profile Target accelerometer stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_accel_intrinsic Sensor calibration parameters.
Referenced by dt::AccelStreamProfile::GetIntrinsic().
DT_EXPORT void dt_accel_stream_profile_set_intrinsic (dt_stream_profile * profile, dt_accel_intrinsic intrinsic, dt_error ** error)
Configures sensor intrinsic calibration.
Parameters
[in] profile Target accelerometer stream profile.
[in] intrinsic New calibration parameters.
[out] error Receives detailed error information if operation fails.
DT_EXPORT dt_gyro_full_scale_range dt_gyro_stream_profile_get_full_scale_range (const dt_stream_profile * profile, dt_error ** error)
Retrieves full-scale angular range.
Parameters
[in] profile Target gyroscope stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_gyro_full_scale_range Current angular range.
Referenced by dt::GyroStreamProfile::GetFullScaleRange().
DT_EXPORT dt_gyro_sample_rate dt_gyro_stream_profile_get_sample_rate (const dt_stream_profile * profile, dt_error ** error)
Retrieves data sampling rate.
Parameters
[in] profile Target gyroscope stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_gyro_sample_rate Current sampling frequency (Hz).
Referenced by dt::GyroStreamProfile::GetSampleRate().
DT_EXPORT dt_gyro_intrinsic dt_gyro_stream_get_intrinsic (const dt_stream_profile * profile, dt_error ** error)
Retrieves sensor intrinsic calibration.
Parameters
[in] profile Target gyroscope stream profile.
[out] error Receives detailed error information if operation fails.
Returns
dt_gyro_intrinsic Sensor calibration parameters.
Referenced by dt::GyroStreamProfile::GetIntrinsic().
DT_EXPORT void dt_gyro_stream_set_intrinsic (dt_stream_profile * profile, dt_gyro_intrinsic intrinsic, dt_error ** error)
Configures sensor intrinsic calibration.
Parameters
[in] profile Target gyroscope stream profile.
[in] intrinsic New calibration parameters.
[out] error Receives detailed error information if operation fails.
DT_EXPORT uint32_t dt_stream_profile_list_get_count (const dt_stream_profile_list * profile_list, dt_error ** error)
Retrieves number of profiles in a list.
Parameters
[in] profile_list Target profile list.
[out] error Receives detailed error information if operation fails.
Returns
uint32_t Profile count.
Referenced by dt::StreamProfileList::GetCount().
DT_EXPORT dt_stream_profile* dt_stream_profile_list_get_profile (const dt_stream_profile_list * profile_list, int index, dt_error ** error)
Retrieves profile by index.
Note
Caller must release the returned profile using dt_delete_stream_profile().
Parameters
[in] profile_list Target profile list.
[in] index Zero-based profile index.
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* Retrieved profile instance.
Referenced by dt::StreamProfileList::GetProfile().
DT_EXPORT dt_stream_profile* dt_stream_profile_list_get_video_stream_profile (const dt_stream_profile_list * profile_list, int width, int height, dt_format format, int fps, dt_error ** error)
Finds matching video profile from a list.
Note
Caller must release the returned profile using dt_delete_stream_profile().
Parameters
[in] profile_list Target profile list.
[in] width Target width (kDtWidthAny for wildcard).
[in] height Target height (kDtHeightAny for wildcard).
[in] format Target format (kDtFormatAny for wildcard).
[in] fps Target frame rate (kDtFpsAny for wildcard).
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* First matching profile found.
Referenced by dt::StreamProfileList::GetVideoStreamProfile().
DT_EXPORT dt_stream_profile* dt_stream_profile_list_get_accel_stream_profile (const dt_stream_profile_list * profile_list, dt_accel_full_scale_range full_scale_range, dt_accel_sample_rate sample_rate, dt_error ** error)
Finds matching accelerometer profile from a list.
Note
Caller must release the returned profile using dt_delete_stream_profile().
Parameters
[in] profile_list Target profile list.
[in] full_scale_range Target range (0 for wildcard).
[in] sample_rate Target sample rate (0 for wildcard).
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* First matching profile found.
Referenced by dt::StreamProfileList::GetAccelStreamProfile().
DT_EXPORT dt_stream_profile* dt_stream_profile_list_get_gyro_stream_profile (const dt_stream_profile_list * profile_list, dt_gyro_full_scale_range full_scale_range, dt_gyro_sample_rate sample_rate, dt_error ** error)
Finds matching gyroscope profile from a list.
Note
Caller must release the returned profile using dt_delete_stream_profile().
Parameters
[in] profile_list Target profile list.
[in] full_scale_range Target range (0 for wildcard).
[in] sample_rate Target sample rate (0 for wildcard).
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* First matching profile found.
Referenced by dt::StreamProfileList::GetGyroStreamProfile().
DT_EXPORT dt_stream_profile* dt_stream_profile_list_get_palm_stream_profile (const dt_stream_profile_list * profile_list, dt_error ** error)
Finds matching palm profile from a list.
Note
Caller must release the returned profile using dt_delete_stream_profile().
Parameters
[in] profile_list Target profile list.
[out] error Receives detailed error information if operation fails.
Returns
dt_stream_profile* First matching profile found.
Referenced by dt::StreamProfileList::GetPalmStreamProfile().
DT_EXPORT void dt_delete_stream_profile_list (const dt_stream_profile_list * profile_list)
Releases a stream profile list and all contained profiles.
Parameters
[in] profile_list Target list to destroy.
Referenced by dt::StreamProfileList::~StreamProfileList().