deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_record_playback.h File Reference
dt_record_playback.h File Reference
Device recording and playback interfaces for capturing and replaying sensor data streams.
#include "dt_device.h"
Functions
DT_EXPORT dt_record_device * dt_create_record_device (dt_device *device, const char *file_path, bool compression_enabled, dt_error **error)
Creates a recording device bound to an existing device.
DT_EXPORT void dt_record_device_pause (dt_record_device *recorder, dt_error **error)
Pauses active recording session.
DT_EXPORT void dt_record_device_resume (dt_record_device *recorder, dt_error **error)
Resumes paused recording session.
DT_EXPORT void dt_delete_record_device (dt_record_device *recorder)
Releases resources associated with a recording device.
DT_EXPORT dt_device * dt_create_playback_device (const char *file_path, dt_error **error)
Creates a playback device from recorded file.
DT_EXPORT void dt_playback_device_pause (dt_device *player, dt_error **error)
Pauses active playback session.
DT_EXPORT void dt_playback_device_resume (dt_device *player, dt_error **error)
Resumes paused playback session.
DT_EXPORT void dt_playback_device_seek (dt_device *player, uint64_t timestamp, dt_error **error)
Sets playback position within recording.
DT_EXPORT void dt_playback_device_set_playback_rate (dt_device *player, float rate, dt_error **error)
Controls playback speed.
DT_EXPORT void dt_playback_device_set_playback_status_changed_callback (dt_device *player, dt_playback_status_changed_callback callback, void *user_data, dt_error **error)
Registers callback for playback status changes.
DT_EXPORT dt_playback_status dt_playback_device_get_current_playback_status (dt_device *player, dt_error **error)
Retrieves current playback status.
DT_EXPORT uint64_t dt_playback_device_get_position (dt_device *player, dt_error **error)
Retrieves current playback position.
DT_EXPORT uint64_t dt_playback_device_get_duration (dt_device *player, dt_error **error)
Retrieves total recording duration.
Detailed Description
Device recording and playback interfaces for capturing and replaying sensor data streams.
Provides functionality to record live device streams to files and replay recorded sessions. Supports compression, seeking, playback speed control, and status monitoring.
Definition in file dt_record_playback.h.
Function Documentation
DT_EXPORT dt_record_device* dt_create_record_device (dt_device * device, const char * file_path, bool compression_enabled, dt_error ** error)
Creates a recording device bound to an existing device.
Parameters
[in] device Source device to record from (must be valid and initialized).
[in] file_path Output file path for recording data.
[in] compression_enabled Enable compression to reduce file size.
[out] error Receives detailed error information if operation fails.
Returns
New recording device handle. Release with dt_delete_record_device().
Referenced by dt::RecordDevice::RecordDevice().
DT_EXPORT void dt_record_device_pause (dt_record_device * recorder, dt_error ** error)
Pauses active recording session.
Parameters
[in] recorder Recording device instance.
[out] error Receives detailed error information if operation fails.
Referenced by dt::RecordDevice::Pause().
DT_EXPORT void dt_record_device_resume (dt_record_device * recorder, dt_error ** error)
Resumes paused recording session.
Parameters
[in] recorder Recording device instance.
[out] error Receives detailed error information if operation fails.
Referenced by dt::RecordDevice::Resume().
DT_EXPORT void dt_delete_record_device (dt_record_device * recorder)
Releases resources associated with a recording device.
Parameters
[in] recorder Recording device instance to destroy.
Referenced by dt::RecordDevice::~RecordDevice().
DT_EXPORT dt_device* dt_create_playback_device (const char * file_path, dt_error ** error)
Creates a playback device from recorded file.
Parameters
[in] file_path Path to playback file (typically .bag format).
[out] error Receives detailed error information if operation fails.
Returns
New playback device handle. Release with dt_delete_device().
Referenced by dt::PlaybackDevice::PlaybackDevice().
DT_EXPORT void dt_playback_device_pause (dt_device * player, dt_error ** error)
Pauses active playback session.
Parameters
[in] player Playback device instance.
[out] error Receives detailed error information if operation fails.
Referenced by dt::PlaybackDevice::Pause().
DT_EXPORT void dt_playback_device_resume (dt_device * player, dt_error ** error)
Resumes paused playback session.
Parameters
[in] player Playback device instance.
[out] error Receives detailed error information if operation fails.
Referenced by dt::PlaybackDevice::Resume().
DT_EXPORT void dt_playback_device_seek (dt_device * player, uint64_t timestamp, dt_error ** error)
Sets playback position within recording.
Parameters
[in] player Playback device instance.
[in] timestamp Target position in milliseconds from recording start.
[out] error Receives detailed error information if operation fails.
Referenced by dt::PlaybackDevice::Seek().
DT_EXPORT void dt_playback_device_set_playback_rate (dt_device * player, float rate, dt_error ** error)
Controls playback speed.
Parameters
[in] player Playback device instance.
[in] rate Playback multiplier (1.0 = real-time, 2.0 = double speed).
[out] error Receives detailed error information if operation fails.
Referenced by dt::PlaybackDevice::SetPlaybackRate().
DT_EXPORT void dt_playback_device_set_playback_status_changed_callback (dt_device * player, dt_playback_status_changed_callback callback, void * user_data, dt_error ** error)
Registers callback for playback status changes.
Parameters
[in] player Playback device instance.
[in] callback Function to invoke on status changes.
[in] user_data Context pointer passed to callback (may be NULL).
[out] error Receives detailed error information if operation fails.
Referenced by dt::PlaybackDevice::SetPlaybackStatusChangeCallback().
DT_EXPORT dt_playback_status dt_playback_device_get_current_playback_status (dt_device * player, dt_error ** error)
Retrieves current playback status.
Parameters
[in] player Playback device instance.
[out] error Receives detailed error information if operation fails.
Returns
Current playback state (playing, paused, stopped).
Referenced by dt::PlaybackDevice::GetPlaybackStatus().
DT_EXPORT uint64_t dt_playback_device_get_position (dt_device * player, dt_error ** error)
Retrieves current playback position.
Parameters
[in] player Playback device instance.
[out] error Receives detailed error information if operation fails.
Returns
Current position in milliseconds from recording start.
Referenced by dt::PlaybackDevice::GetPosition().
DT_EXPORT uint64_t dt_playback_device_get_duration (dt_device * player, dt_error ** error)
Retrieves total recording duration.
Parameters
[in] player Playback device instance.
[out] error Receives detailed error information if operation fails.
Returns
Total duration in milliseconds of recording.
Referenced by dt::PlaybackDevice::GetDuration().