deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_config.h File Reference
dt_config.h File Reference
Manages pipeline configuration including stream selection, device filtering, and pre-streaming device configuration.
#include "dt_types.h"
Functions
DT_EXPORT dt_config * dt_create_config (dt_error **error)
Creates a pipeline configuration instance.
DT_EXPORT void dt_delete_config (dt_config *config)
Releases configuration resources.
DT_EXPORT dt_stream_profile_list * dt_config_get_enabled_stream_profile_list (const dt_config *config, dt_error **error)
Retrieves enabled stream profiles from configuration.
DT_EXPORT void dt_config_enable_all_stream (dt_config *config, dt_error **error)
Enables all streams defined in pipeline configuration.
DT_EXPORT void dt_config_enable_stream (dt_config *config, dt_stream_type stream_type, dt_error **error)
Enables a stream with default profile settings.
DT_EXPORT void dt_config_enable_stream_with_stream_profile (dt_config *config, const dt_stream_profile *profile, dt_error **error)
Enables a stream with specific profile parameters.
DT_EXPORT void dt_config_enable_video_stream (dt_config *config, dt_stream_type stream_type, uint32_t width, uint32_t height, uint32_t fps, dt_format format, dt_error **error)
Enables a video stream with explicit parameters.
DT_EXPORT void dt_config_enable_accel_stream (dt_config *config, dt_accel_full_scale_range full_scale_range, dt_accel_sample_rate sample_rate, dt_error **error)
Enables accelerometer stream with specified parameters.
DT_EXPORT void dt_config_enable_gyro_stream (dt_config *config, dt_gyro_full_scale_range full_scale_range, dt_gyro_sample_rate sample_rate, dt_error **error)
Enables gyroscope stream with specified parameters.
DT_EXPORT void dt_config_enable_palm_stream (dt_config *config, dt_error **error)
Enables palm stream with specified parameters.
DT_EXPORT void dt_config_disable_all_stream (dt_config *config, dt_error **error)
Disables all streams in configuration.
DT_EXPORT void dt_config_disable_stream (dt_config *config, dt_stream_type type, dt_error **error)
Disables specific stream type in configuration.
Detailed Description
Manages pipeline configuration including stream selection, device filtering, and pre-streaming device configuration.
Definition in file dt_config.h.
Function Documentation
DT_EXPORT dt_config* dt_create_config (dt_error ** error)
Creates a pipeline configuration instance.
Provides stream filtering and device validation capabilities. When absent, pipeline auto-resolves devices. Allows device selection and pre-configuration.
Parameters
[out] error Receives detailed error information if operation fails.
Returns
Pointer to new configuration instance. Returns NULL on failure.
Referenced by dt::Config::Config().
DT_EXPORT void dt_delete_config (dt_config * config)
Releases configuration resources.
Parameters
[in] config Target configuration instance to destroy. If NULL, no operation is performed.
Referenced by dt::Config::~Config().
DT_EXPORT dt_stream_profile_list* dt_config_get_enabled_stream_profile_list (const dt_config * config, dt_error ** error)
Retrieves enabled stream profiles from configuration.
Parameters
[in] config Initialized configuration instance.
[out] error Receives detailed error information if operation fails.
Returns
Pointer to stream profile list. Must be released by caller using dt_delete_stream_profile_list. Returns NULL on failure.
Referenced by dt::Config::GetEnabledStreamProfileList().
DT_EXPORT void dt_config_enable_all_stream (dt_config * config, dt_error ** error)
Enables all streams defined in pipeline configuration.
Parameters
[in] config Initialized configuration instance.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Config::EnableAllStream().
DT_EXPORT void dt_config_enable_stream (dt_config * config, dt_stream_type stream_type, dt_error ** error)
Enables a stream with default profile settings.
Parameters
[in] config Initialized configuration instance.
[in] stream_type Target stream type identifier.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Config::EnableStream().
DT_EXPORT void dt_config_enable_stream_with_stream_profile (dt_config * config, const dt_stream_profile * profile, dt_error ** error)
Enables a stream with specific profile parameters.
Parameters
[in] config Initialized configuration instance.
[in] profile Stream profile containing configuration parameters.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Config::EnableStream().
DT_EXPORT void dt_config_enable_video_stream (dt_config * config, dt_stream_type stream_type, uint32_t width, uint32_t height, uint32_t fps, dt_format format, dt_error ** error)
Enables a video stream with explicit parameters.
Attention
Restricted to video stream types (kDtStreamIr, kDtStreamColor, etc.).
Parameters
[in] config Initialized configuration instance.
[in] stream_type Video stream type identifier.
[in] width Frame width in pixels.
[in] height Frame height in pixels.
[in] fps Frame rate in frames per second.
[in] format Pixel data format.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Config::EnableVideoStream().
DT_EXPORT void dt_config_enable_accel_stream (dt_config * config, dt_accel_full_scale_range full_scale_range, dt_accel_sample_rate sample_rate, dt_error ** error)
Enables accelerometer stream with specified parameters.
Parameters
[in] config Initialized configuration instance.
[in] full_scale_range Accelerometer measurement range.
[in] sample_rate Sampling frequency in Hz.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Config::EnableAccelStream().
DT_EXPORT void dt_config_enable_gyro_stream (dt_config * config, dt_gyro_full_scale_range full_scale_range, dt_gyro_sample_rate sample_rate, dt_error ** error)
Enables gyroscope stream with specified parameters.
Parameters
[in] config Initialized configuration instance.
[in] full_scale_range Gyroscope measurement range.
[in] sample_rate Sampling frequency in Hz.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Config::EnableGyroStream().
DT_EXPORT void dt_config_enable_palm_stream (dt_config * config, dt_error ** error)
Enables palm stream with specified parameters.
Parameters
[in] config Initialized configuration instance.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Config::EnablePalmStream().
DT_EXPORT void dt_config_disable_all_stream (dt_config * config, dt_error ** error)
Disables all streams in configuration.
Parameters
[in] config Initialized configuration instance.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Config::DisableAllStream().
DT_EXPORT void dt_config_disable_stream (dt_config * config, dt_stream_type type, dt_error ** error)
Disables specific stream type in configuration.
Parameters
[in] config Initialized configuration instance.
[in] type Stream type identifier to disable.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Config::DisableStream().