deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_version.h File Reference
dt_version.h File Reference
SDK version information retrieval interface.
#include "dt_export.h"
Functions
DT_EXPORT int dt_get_version ()
Retrieves the composite SDK version number.
DT_EXPORT const char * dt_get_version_str ()
Retrieves the SDK version as a null-terminated string. The format is "major.minor.patch-stage". For example, "1.2.3-alpha". The returned string has static storage duration and should not be freed.
DT_EXPORT int dt_get_major_version ()
Retrieves the major component of the SDK version.
DT_EXPORT int dt_get_minor_version ()
Retrieves the minor component of the SDK version.
DT_EXPORT int dt_get_patch_version ()
Retrieves the patch component of the SDK version.
DT_EXPORT const char * dt_get_stage_version ()
Retrieves the development stage identifier.
Detailed Description
SDK version information retrieval interface.
Definition in file dt_version.h.
Function Documentation
DT_EXPORT int dt_get_version ()
Retrieves the composite SDK version number.
Returns
int Composite version value combining major, minor and patch components.
Note
The version format is: (major * 10000000) + (minor * 10000) + patch.
Referenced by dt::Version::GetVersion().
DT_EXPORT const char* dt_get_version_str ()
Retrieves the SDK version as a null-terminated string. The format is "major.minor.patch-stage". For example, "1.2.3-alpha". The returned string has static storage duration and should not be freed.
Returns
const char* Null-terminated string representing the SDK version.
Referenced by dt::Version::GetVersionStr().
DT_EXPORT int dt_get_major_version ()
Retrieves the major component of the SDK version.
Returns
int Major version number indicating breaking changes.
Referenced by dt::Version::GetMajor().
DT_EXPORT int dt_get_minor_version ()
Retrieves the minor component of the SDK version.
Returns
int Minor version number indicating feature additions.
Referenced by dt::Version::GetMinor().
DT_EXPORT int dt_get_patch_version ()
Retrieves the patch component of the SDK version.
Returns
int Patch version number indicating bug fixes.
Referenced by dt::Version::GetPatch().
DT_EXPORT const char* dt_get_stage_version ()
Retrieves the development stage identifier.
Returns
const char* Null-terminated string representing release stage (e.g., "alpha", "beta", "rc", "stable").
Note
The returned string has static storage duration and should not be freed.
Referenced by dt::Version::GetStageVersion().