deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_type_helper.h File Reference
dt_type_helper.h File Reference
Helper functions for converting type enumerations to strings.
#include "dt_option.h"
#include "dt_types.h"
Functions
DT_EXPORT const char * dt_camera_info_to_string (dt_camera_info camera_info)
Converts a camera info enumeration to its string representation.
DT_EXPORT const char * dt_breath_mode_to_string (dt_breath_mode breath_mode)
Converts a breath mode enumeration to its string representation.
DT_EXPORT const char * dt_dim_palm_mode_to_string (dt_dim_palm_mode dim_palm_mode)
Converts a dim palm mode enumeration to its string representation.
DT_EXPORT const char * dt_status_to_string (dt_status status)
Converts a status enumeration to its string representation.
DT_EXPORT const char * dt_log_severity_to_string (dt_log_severity log_severity)
Converts a log severity enumeration to its string representation.
DT_EXPORT const char * dt_sensor_type_to_string (dt_sensor_type sensor_type)
Converts a sensor type enumeration to its string representation.
DT_EXPORT const char * dt_stream_type_to_string (dt_stream_type stream_type)
Converts a stream type enumeration to its string representation.
DT_EXPORT const char * dt_frame_type_to_string (dt_frame_type frame_type)
Converts a frame type enumeration to its string representation.
DT_EXPORT const char * dt_format_to_string (dt_format format)
Converts a pixel format enumeration to its string representation.
DT_EXPORT const char * dt_convert_format_to_string (dt_convert_format convert_format)
Converts a convert format enumeration to its string representation.
DT_EXPORT const char * dt_imu_sample_rate_to_string (dt_imu_sample_rate imu_sample_rate)
Converts an IMU sample rate enumeration to its string representation.
DT_EXPORT const char * dt_gyro_full_scale_range_to_string (dt_gyro_full_scale_range gyro_full_scale_range)
Converts a gyroscope full scale range enumeration to its string representation.
DT_EXPORT const char * dt_accel_full_scale_range_to_string (dt_accel_full_scale_range accel_full_scale_range)
Converts an accelerometer full scale range enumeration to its string representation.
DT_EXPORT const char * dt_media_type_to_string (dt_media_type media_type)
Converts a media type enumeration to its string representation.
DT_EXPORT const char * dt_media_state_to_string (dt_media_state media_state)
Converts a media state enumeration to its string representation.
DT_EXPORT const char * dt_frame_metadata_type_to_string (dt_frame_metadata_type frame_metadata_type)
Converts a frame metadata type enumeration to its string representation.
DT_EXPORT const char * dt_exception_type_to_string (dt_exception_type exception_type)
Converts an exception type enumeration to its string representation.
DT_EXPORT const char * dt_option_id_to_string (dt_option_id option_id)
Converts an option ID enumeration to its string representation.
DT_EXPORT const char * dt_permission_type_to_string (dt_permission_type permission_type)
Converts a permission type enumeration to its string representation.
DT_EXPORT const char * dt_option_type_to_string (dt_option_type option_type)
Converts an option type enumeration to its string representation.
DT_EXPORT DtStreamType dt_sensor_type_to_stream_type (dt_sensor_type sensor_type)
Converts a sensor type enumeration to its corresponding stream type.
Detailed Description
Helper functions for converting type enumerations to strings.
Definition in file dt_type_helper.h.
Function Documentation
DT_EXPORT const char* dt_camera_info_to_string (dt_camera_info camera_info)
Converts a camera info enumeration to its string representation.
Parameters
[in] camera_info Camera info enumeration value.
Returns
const char* String representation of the camera info enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_breath_mode_to_string (dt_breath_mode breath_mode)
Converts a breath mode enumeration to its string representation.
Parameters
[in] breath_mode Breath mode enumeration value.
Returns
const char* String representation of the breath mode enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_dim_palm_mode_to_string (dt_dim_palm_mode dim_palm_mode)
Converts a dim palm mode enumeration to its string representation.
Parameters
[in] dim_palm_mode Dim palm mode enumeration value.
Returns
const char* String representation of the dim palm mode enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_status_to_string (dt_status status)
Converts a status enumeration to its string representation.
Parameters
[in] status Status enumeration value.
Returns
const char* String representation of the status enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_log_severity_to_string (dt_log_severity log_severity)
Converts a log severity enumeration to its string representation.
Parameters
[in] log_severity Log severity enumeration value.
Returns
const char* String representation of the log severity enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_sensor_type_to_string (dt_sensor_type sensor_type)
Converts a sensor type enumeration to its string representation.
Parameters
[in] sensor_type Sensor type enumeration value.
Returns
const char* String representation of the sensor type enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_stream_type_to_string (dt_stream_type stream_type)
Converts a stream type enumeration to its string representation.
Parameters
[in] stream_type Stream type enumeration value.
Returns
const char* String representation of the stream type enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_frame_type_to_string (dt_frame_type frame_type)
Converts a frame type enumeration to its string representation.
Parameters
[in] frame_type Frame type enumeration value.
Returns
const char* String representation of the frame type enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_format_to_string (dt_format format)
Converts a pixel format enumeration to its string representation.
Parameters
[in] format Pixel format enumeration value.
Returns
const char* String representation of the pixel format enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_convert_format_to_string (dt_convert_format convert_format)
Converts a convert format enumeration to its string representation.
Parameters
[in] convert_format Convert format enumeration value.
Returns
const char* String representation of the convert format enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_imu_sample_rate_to_string (dt_imu_sample_rate imu_sample_rate)
Converts an IMU sample rate enumeration to its string representation.
Parameters
[in] imu_sample_rate IMU sample rate enumeration value.
Returns
const char* String representation of the IMU sample rate enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_gyro_full_scale_range_to_string (dt_gyro_full_scale_range gyro_full_scale_range)
Converts a gyroscope full scale range enumeration to its string representation.
Parameters
[in] gyro_full_scale_range Gyroscope full scale range enumeration value.
Returns
const char* String representation of the gyroscope full scale range enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_accel_full_scale_range_to_string (dt_accel_full_scale_range accel_full_scale_range)
Converts an accelerometer full scale range enumeration to its string representation.
Parameters
[in] accel_full_scale_range Accelerometer full scale range enumeration value.
Returns
const char* String representation of the accelerometer full scale range enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_media_type_to_string (dt_media_type media_type)
Converts a media type enumeration to its string representation.
Parameters
[in] media_type Media type enumeration value.
Returns
const char* String representation of the media type enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_media_state_to_string (dt_media_state media_state)
Converts a media state enumeration to its string representation.
Parameters
[in] media_state Media state enumeration value.
Returns
const char* String representation of the media state enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_frame_metadata_type_to_string (dt_frame_metadata_type frame_metadata_type)
Converts a frame metadata type enumeration to its string representation.
Parameters
[in] frame_metadata_type Frame metadata type enumeration value.
Returns
const char* String representation of the frame metadata type enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_exception_type_to_string (dt_exception_type exception_type)
Converts an exception type enumeration to its string representation.
Parameters
[in] exception_type Exception type enumeration value.
Returns
const char* String representation of the exception type enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_option_id_to_string (dt_option_id option_id)
Converts an option ID enumeration to its string representation.
Parameters
[in] option_id Option ID enumeration value.
Returns
const char* String representation of the option ID enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_permission_type_to_string (dt_permission_type permission_type)
Converts a permission type enumeration to its string representation.
Parameters
[in] permission_type Permission type enumeration value.
Returns
const char* String representation of the permission type enumeration.
Referenced by operator<<().
DT_EXPORT const char* dt_option_type_to_string (dt_option_type option_type)
Converts an option type enumeration to its string representation.
Parameters
[in] option_type Option type enumeration value.
Returns
const char* String representation of the option type enumeration.
Referenced by operator<<().
DT_EXPORT DtStreamType dt_sensor_type_to_stream_type (dt_sensor_type sensor_type)
Converts a sensor type enumeration to its corresponding stream type.
Parameters
[in] sensor_type Source sensor type enumeration.
Returns
DtStreamType Corresponding stream type enumeration.
Referenced by dt::TypeHelper::ConvertSensorTypeToStreamType().