deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_filter.h File Reference
dt_filter.h File Reference
Defines processing units for point cloud generation, format conversion, and other data transformation operations.
#include "dt_types.h"
Functions
DT_EXPORT dt_filter * dt_create_filter (const char *name, dt_error **error)
Creates a new filter instance with the specified identifier.
DT_EXPORT void dt_delete_filter (dt_filter *filter)
Releases resources associated with a filter.
DT_EXPORT const char * dt_filter_get_config_schema (const dt_filter *filter, dt_error **error)
Retrieves the CSV-formatted configuration schema for the filter.
DT_EXPORT dt_filter_config_schema_list * dt_filter_get_config_schema_list (const dt_filter *filter, dt_error **error)
Retrieves structured configuration schema as a list of items.
DT_EXPORT void dt_filter_update_config (dt_filter *filter, uint8_t argc, const char **argv, dt_error **error)
Updates filter configuration using command-style arguments.
DT_EXPORT double dt_filter_get_config_value (const dt_filter *filter, const char *config_name, dt_error **error)
Retrieves a configuration parameter's value as double-precision.
DT_EXPORT void dt_filter_set_config_value (dt_filter *filter, const char *config_name, double value, dt_error **error)
Modifies a configuration parameter's value.
DT_EXPORT dt_frame * dt_filter_process (dt_filter *filter, const dt_frame *frame, dt_error **error)
Processes a frame synchronously and returns the result.
DT_EXPORT void dt_filter_set_callback (dt_filter *filter, dt_filter_callback callback, void *user_data, dt_error **error)
Sets the callback handler for asynchronous processing results.
DT_EXPORT void dt_filter_push_frame (dt_filter *filter, const dt_frame *frame, dt_error **error)
Submits a frame for asynchronous processing.
DT_EXPORT void dt_filter_reset (dt_filter *filter, dt_error **error)
Resets internal state and clears processing caches.
DT_EXPORT void dt_filter_enable (dt_filter *filter, bool enable, dt_error **error)
Enables or disables frame processing functionality.
DT_EXPORT bool dt_filter_is_enabled (const dt_filter *filter, dt_error **error)
Checks whether frame processing is currently enabled.
DT_EXPORT const char * dt_filter_get_name (const dt_filter *filter, dt_error **error)
Retrieves the unique identifier of a filter.
DT_EXPORT void dt_align_filter_set_align_to_stream_profile (dt_filter *filter, const dt_stream_profile *align_to_stream_profile, dt_error **error)
Configures alignment target stream profile for align filters.
DT_EXPORT uint32_t dt_filter_list_get_count (const dt_filter_list *filter_list, dt_error **error)
Retrieves the number of filters in a list.
DT_EXPORT dt_filter * dt_filter_list_get_filter (const dt_filter_list *filter_list, uint32_t index, dt_error **error)
Retrieves a filter by its index in a list.
DT_EXPORT void dt_delete_filter_list (dt_filter_list *filter_list)
Releases resources associated with a filter list.
DT_EXPORT uint32_t dt_filter_config_schema_list_get_count (const dt_filter_config_schema_list *config_schema_list, dt_error **error)
Retrieves the number of items in a configuration schema list.
DT_EXPORT dt_filter_config_schema_item dt_filter_config_schema_list_get_item (const dt_filter_config_schema_list *config_schema_list, uint32_t index, dt_error **error)
Retrieves a configuration schema item by index.
DT_EXPORT void dt_delete_filter_config_schema_list (dt_filter_config_schema_list *config_schema_list)
Releases resources associated with a configuration schema list.
Detailed Description
Defines processing units for point cloud generation, format conversion, and other data transformation operations.
Definition in file dt_filter.h.
Function Documentation
DT_EXPORT dt_filter* dt_create_filter (const char * name, dt_error ** error)
Creates a new filter instance with the specified identifier.
Attention
Returns NULL if the requested filter is private and its creator hasn't been activated.
Parameters
[in] name Unique identifier of the filter to create.
[out] error Receives detailed error information if operation fails.
Returns
Pointer to the created filter object. Returns NULL on failure.
Referenced by dt::Align::Align(), dt::FilterFactory::CreateFilter(), dt::DecimationFilter::DecimationFilter(), dt::FormatConvertFilter::FormatConvertFilter(), dt::PointCloudFilter::PointCloudFilter(), and dt::ThresholdFilter::ThresholdFilter().
DT_EXPORT void dt_delete_filter (dt_filter * filter)
Releases resources associated with a filter.
Parameters
[in] filter Target filter object to destroy.
Referenced by dt::Filter::~Filter().
DT_EXPORT const char* dt_filter_get_config_schema (const dt_filter * filter, dt_error ** error)
Retrieves the CSV-formatted configuration schema for the filter.
Format contains: Parameter name, type ("int"/"float"/"bool"), min value, max value, step size, default value, and description (comma-separated).
Parameters
[in] filter Target filter object to query.
[out] error Receives detailed error information if operation fails.
Returns
CSV-formatted string describing the filter's configuration schema.
Referenced by dt::Filter::GetConfigSchema().
DT_EXPORT dt_filter_config_schema_list* dt_filter_get_config_schema_list (const dt_filter * filter, dt_error ** error)
Retrieves structured configuration schema as a list of items.
Attention
Caller must release the list using dt_delete_filter_config_schema_list.
Parameters
[in] filter Target filter object to query.
[out] error Receives detailed error information if operation fails.
Returns
Pointer to the configuration schema list object.
Referenced by dt::Filter::Init().
DT_EXPORT void dt_filter_update_config (dt_filter * filter, uint8_t argc, const char ** argv, dt_error ** error)
Updates filter configuration using command-style arguments.
Attention
Arguments must match the schema from dt_filter_get_config_schema.
Parameters
[in] filter Target filter object to configure.
[in] argc Number of configuration arguments.
[in] argv Array of configuration values.
[out] error Receives detailed error information if operation fails.
DT_EXPORT double dt_filter_get_config_value (const dt_filter * filter, const char * config_name, dt_error ** error)
Retrieves a configuration parameter's value as double-precision.
Attention
Actual data type is determined by the filter's schema.
Parameters
[in] filter Target filter object to query.
[in] config_name Name of the configuration parameter.
[out] error Receives detailed error information if operation fails.
Returns
Current value of the parameter (automatically cast to double).
Referenced by dt::Filter::GetConfigValue().
DT_EXPORT void dt_filter_set_config_value (dt_filter * filter, const char * config_name, double value, dt_error ** error)
Modifies a configuration parameter's value.
Attention
Value will be cast to the type specified in the filter's schema.
Parameters
[in] filter Target filter object to configure.
[in] config_name Name of the configuration parameter.
[in] value New value to set (as double-precision).
[out] error Receives detailed error information if operation fails.
Referenced by dt::Filter::SetConfigValue().
DT_EXPORT dt_frame* dt_filter_process (dt_filter * filter, const dt_frame * frame, dt_error ** error)
Processes a frame synchronously and returns the result.
Parameters
[in] filter Target filter object to execute processing.
[in] frame Input frame data to process.
[out] error Receives detailed error information if operation fails.
Returns
Pointer to the processed output frame.
Referenced by dt::Filter::Process().
DT_EXPORT void dt_filter_set_callback (dt_filter * filter, dt_filter_callback callback, void * user_data, dt_error ** error)
Sets the callback handler for asynchronous processing results.
Parameters
[in] filter Target filter object to configure.
[in] callback Function to invoke when processing completes.
[in] user_data Custom context pointer passed to the callback.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Filter::SetCallBack().
DT_EXPORT void dt_filter_push_frame (dt_filter * filter, const dt_frame * frame, dt_error ** error)
Submits a frame for asynchronous processing.
Attention
Increases the frame's reference count; caller must still release original frame.
Parameters
[in] filter Target filter object to process frame.
[in] frame Input frame data to process.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Filter::PushFrame().
DT_EXPORT void dt_filter_reset (dt_filter * filter, dt_error ** error)
Resets internal state and clears processing caches.
Parameters
[in] filter Target filter object to reset.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Filter::Reset().
DT_EXPORT void dt_filter_enable (dt_filter * filter, bool enable, dt_error ** error)
Enables or disables frame processing functionality.
Note
When disabled, outputs direct clones of input frames without processing.
Parameters
[in] filter Target filter object to configure.
[in] enable true to enable processing, false to bypass.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Filter::Enable().
DT_EXPORT bool dt_filter_is_enabled (const dt_filter * filter, dt_error ** error)
Checks whether frame processing is currently enabled.
Parameters
[in] filter Target filter object to query.
[out] error Receives detailed error information if operation fails.
Returns
true if processing is active, false if bypassing.
Referenced by dt::Filter::IsEnabled().
DT_EXPORT const char* dt_filter_get_name (const dt_filter * filter, dt_error ** error)
Retrieves the unique identifier of a filter.
Parameters
[in] filter Target filter object to query.
[out] error Receives detailed error information if operation fails.
Returns
Null-terminated string containing the filter's name.
Referenced by dt::Filter::Init().
DT_EXPORT void dt_align_filter_set_align_to_stream_profile (dt_filter * filter, const dt_stream_profile * align_to_stream_profile, dt_error ** error)
Configures alignment target stream profile for align filters.
Note
Required when target stream isn't active (no frames to derive intrinsics/extrinsics).
Parameters
[in] filter Target align filter object to configure.
[in] align_to_stream_profile Reference stream profile for alignment operations.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Align::SetAlignToStreamProfile().
DT_EXPORT uint32_t dt_filter_list_get_count (const dt_filter_list * filter_list, dt_error ** error)
Retrieves the number of filters in a list.
Parameters
[in] filter_list Target filter list to query.
[out] error Receives detailed error information if operation fails.
Returns
Total count of filters in the list.
Referenced by dt::Sensor::CreateRecommendedFilters(), and dt::DtFilterList::GetCount().
DT_EXPORT dt_filter* dt_filter_list_get_filter (const dt_filter_list * filter_list, uint32_t index, dt_error ** error)
Retrieves a filter by its index in a list.
Parameters
[in] filter_list Target filter list to query.
[in] index Zero-based position of the filter to retrieve.
[out] error Receives detailed error information if operation fails.
Returns
Pointer to the filter at the specified index.
Referenced by dt::Sensor::CreateRecommendedFilters(), and dt::DtFilterList::GetFilter().
DT_EXPORT void dt_delete_filter_list (dt_filter_list * filter_list)
Releases resources associated with a filter list.
Parameters
[in] filter_list Target filter list to destroy.
Referenced by dt::Sensor::CreateRecommendedFilters(), and dt::DtFilterList::~DtFilterList().
DT_EXPORT uint32_t dt_filter_config_schema_list_get_count (const dt_filter_config_schema_list * config_schema_list, dt_error ** error)
Retrieves the number of items in a configuration schema list.
Parameters
[in] config_schema_list Target schema list to query.
[out] error Receives detailed error information if operation fails.
Returns
Total count of configuration items.
Referenced by dt::Filter::Init().
DT_EXPORT dt_filter_config_schema_item dt_filter_config_schema_list_get_item (const dt_filter_config_schema_list * config_schema_list, uint32_t index, dt_error ** error)
Retrieves a configuration schema item by index.
Parameters
[in] config_schema_list Target schema list to query.
[in] index Zero-based position of the item to retrieve.
[out] error Receives detailed error information if operation fails.
Returns
Configuration schema item at the specified index.
Referenced by dt::Filter::Init().
DT_EXPORT void dt_delete_filter_config_schema_list (dt_filter_config_schema_list * config_schema_list)
Releases resources associated with a configuration schema list.
Parameters
[in] config_schema_list Target schema list to destroy.
Referenced by dt::Filter::Init().