deptrum: /home/deptrum/deptrum-stream-v3/include/deptrum/h/dt_device.h File Reference
dt_device.h File Reference
Provides device management interfaces including device enumeration, configuration control, sensor access, firmware operations, and device state monitoring.
#include <stdint.h>
#include "dt_option.h"
#include "dt_types.h"
Functions
DT_EXPORT void dt_delete_device (dt_device *device)
Releases resources associated with a device instance.
DT_EXPORT void dt_delete_device_list (dt_device_list *list)
Releases device list resources.
DT_EXPORT uint32_t dt_device_list_get_count (const dt_device_list *list, dt_error **error)
Queries device count in a device list.
DT_EXPORT dt_device * dt_device_list_get_device (const dt_device_list *list, uint32_t index, dt_error **error)
Creates a device instance from device list.
DT_EXPORT dt_device * dt_device_list_get_device_by_serial_number (const dt_device_list *list, const char *serial_number, dt_error **error)
Create a device.
DT_EXPORT dt_device * dt_device_list_get_device_by_uid (const dt_device_list *list, const char *uid, dt_error **error)
Retrieves a device from the device list by its unique identifier.
DT_EXPORT const char * dt_device_list_get_device_info (const dt_device_list *list, uint32_t index, dt_camera_info info, dt_error **error)
Retrieves device information from list.
DT_EXPORT const char * dt_device_get_device_info (const dt_device *device, dt_camera_info info, dt_error **error)
Retrieves device information.
DT_EXPORT dt_device_state dt_device_get_device_state (const dt_device *device, dt_error **error)
Queries current operational state of device.
DT_EXPORT void dt_device_set_state_changed_callback (dt_device *device, dt_device_state_callback callback, void *user_data, dt_error **error)
Registers callback for device state changes.
DT_EXPORT void dt_device_reboot (dt_device *device, dt_error **error)
Reboots device hardware.
DT_EXPORT dt_sensor_list * dt_device_get_sensor_list (const dt_device *device, dt_error **error)
Retrieves all sensors associated with device.
DT_EXPORT dt_sensor * dt_device_get_sensor (dt_device *device, dt_sensor_type type, dt_error **error)
Retrieves specific sensor by type.
DT_EXPORT uint32_t dt_device_get_supported_option_count (const dt_device *device, dt_error **error)
Queries number of supported configuration options.
DT_EXPORT dt_option_item dt_device_get_supported_option_item (const dt_device *device, uint32_t index, dt_error **error)
Retrieves option metadata by index.
DT_EXPORT bool dt_device_is_option_supported (const dt_device *device, dt_option_id option_id, dt_permission_type permission, dt_error **error)
Checks option permission availability.
DT_EXPORT void dt_device_set_int_option (dt_device *device, dt_option_id option_id, int32_t value, dt_error **error)
Sets an integer type of device option.
DT_EXPORT int32_t dt_device_get_int_option (dt_device *device, dt_option_id option_id, dt_error **error)
Gets an integer type of device option.
DT_EXPORT dt_int_option_range dt_device_get_int_option_range (dt_device *device, dt_option_id option_id, dt_error **error)
Gets the integer type of device option range.
DT_EXPORT void dt_device_set_float_option (dt_device *device, dt_option_id option_id, float value, dt_error **error)
Sets a float type of device option.
DT_EXPORT float dt_device_get_float_option (dt_device *device, dt_option_id option_id, dt_error **error)
Gets a float type of device option.
DT_EXPORT dt_float_option_range dt_device_get_float_option_range (dt_device *device, dt_option_id option_id, dt_error **error)
Gets the float type of device option range.
DT_EXPORT void dt_device_set_bool_option (dt_device *device, dt_option_id option_id, bool value, dt_error **error)
Sets a boolean type of device option.
DT_EXPORT bool dt_device_get_bool_option (dt_device *device, dt_option_id option_id, dt_error **error)
Gets a boolean type of device option.
DT_EXPORT dt_bool_option_range dt_device_get_bool_option_range (dt_device *device, dt_option_id option_id, dt_error **error)
Gets the boolean type of device option range.
DT_EXPORT void dt_device_set_structured_data (dt_device *device, dt_option_id option_id, const uint8_t *data, uint32_t data_size, dt_error **error)
Sets structured data.
DT_EXPORT void dt_device_get_structured_data (dt_device *device, dt_option_id option_id, uint8_t *data, uint32_t *data_size, dt_error **error)
Gets structured data of a device option.
DT_EXPORT void dt_device_get_raw_data (dt_device *device, dt_option_id option_id, dt_get_data_callback cb, void *user_data, dt_error **error)
Gets raw data of a device option.
DT_EXPORT bool dt_device_is_global_timestamp_supported (const dt_device *device, dt_error **error)
Checks global timestamp support capability.
DT_EXPORT void dt_device_enable_global_timestamp (dt_device *device, bool enable, dt_error **error)
Enables/disables global timestamp synchronization.
DT_EXPORT void dt_device_send_file_to_device (dt_device *device, const char *src_file_path, const char *dst_file_path, dt_file_tran_callback callback, bool async, void *user_data, dt_error **error)
Transfers file from host to device storage.
DT_EXPORT void dt_device_receive_file_from_device (dt_device *device, const char *src_file_path, const char *dst_file_path, dt_file_tran_callback callback, bool async, void *user_data, dt_error **error)
Retrieves file from device storage to host.
DT_EXPORT void dt_device_update_firmware (dt_device *device, const char *path, dt_device_fw_update_callback callback, bool async, void *user_data, dt_error **error)
Updates device firmware from file.
DT_EXPORT void dt_device_update_firmware_from_data (dt_device *device, const uint8_t *data, uint32_t data_size, dt_device_fw_update_callback callback, bool async, void *user_data, dt_error **error)
Updates device firmware from memory buffer.
DT_EXPORT void dt_device_write_flash (dt_device *device, uint32_t offset, const void *data, uint32_t data_size, dt_set_data_callback callback, bool async, void *user_data, dt_error **error)
Writes data to device flash memory.
DT_EXPORT void dt_device_read_flash (dt_device *device, uint32_t offset, uint32_t data_size, dt_get_data_callback callback, bool async, void *user_data, dt_error **error)
Reads data from device flash memory.
DT_EXPORT void dt_device_enable_heartbeat (dt_device *device, bool enable, dt_error **error)
Controls device heartbeat monitoring.
DT_EXPORT void dt_device_send_and_receive_data (dt_device *device, const uint8_t *send_data, uint32_t send_data_size, uint8_t *receive_data, uint32_t *receive_data_size, dt_error **error)
Executes vendor-specific device command (factory use).
DT_EXPORT dt_camera_param_list * dt_device_get_calibration_camera_param_list (dt_device *device, dt_error **error)
Retrieves the original camera calibration parameters stored on the device.
DT_EXPORT uint32_t dt_camera_param_list_get_count (dt_camera_param_list *param_list, dt_error **error)
Retrieves the number of camera parameter sets in the collection.
DT_EXPORT dt_camera_param dt_camera_param_list_get_param (dt_camera_param_list *param_list, uint32_t index, dt_error **error)
Retrieves a specific camera parameter set by index.
DT_EXPORT void dt_delete_camera_param_list (dt_camera_param_list *param_list)
Releases resources associated with a camera parameter collection.
DT_EXPORT void dt_device_timer_sync_with_host (dt_device *device, dt_error **error)
Synchronizes the device's internal timer with the host system clock.
Detailed Description
Provides device management interfaces including device enumeration, configuration control, sensor access, firmware operations, and device state monitoring.
Definition in file dt_device.h.
Function Documentation
DT_EXPORT void dt_delete_device (dt_device * device)
Releases resources associated with a device instance.
Parameters
[in] device Target device instance to destroy. If NULL, no operation is performed.
Referenced by dt::Device::operator=(), and dt::Device::~Device().
DT_EXPORT void dt_delete_device_list (dt_device_list * list)
Releases device list resources.
Parameters
[in] list Target device list instance to destroy. If NULL, no operation is performed.
Referenced by dt::DeviceList::~DeviceList().
DT_EXPORT uint32_t dt_device_list_get_count (const dt_device_list * list, dt_error ** error)
Queries device count in a device list.
Parameters
[in] list Initialized device list instance.
[out] error Receives detailed error information if operation fails.
Returns
uint32_t Number of enumerated devices. Returns 0 on error.
Referenced by dt::DeviceList::GetCount().
DT_EXPORT dt_device* dt_device_list_get_device (const dt_device_list * list, uint32_t index, dt_error ** error)
Creates a device instance from device list.
Attention
Fails if device is already acquired elsewhere.
Parameters
[in] list Initialized device list instance.
[in] index Zero-based device index in list.
[out] error Receives detailed error information if operation fails.
Returns
dt_device* New device instance. Returns NULL on failure.
Referenced by dt::DeviceList::GetDevice().
DT_EXPORT dt_device* dt_device_list_get_device_by_serial_number (const dt_device_list * list, const char * serial_number, dt_error ** error)
Create a device.
Attention
If the device has already been acquired and created elsewhere, repeated acquisitions will return an error.
Parameters
[in] list Device list object.
[in] serial_number The serial number of the device to create.
[out] error Receives detailed error information if operation fails.
Returns
dt_device* The created device.
Referenced by dt::DeviceList::GetDeviceBySN().
DT_EXPORT dt_device* dt_device_list_get_device_by_uid (const dt_device_list * list, const char * uid, dt_error ** error)
Retrieves a device from the device list by its unique identifier.
On Linux platform, for usb device, the uid of the device is composed of bus-port-dev, for example 1-1.2-1. But the SDK will remove the dev number and only keep the bus-port as the uid to create the device, for example 1-1.2, so that we can create a device connected to the specified USB port. Similarly, users can also directly pass in bus-port as uid to create device.
Attention
If the device has already been acquired and created elsewhere, repeated acquisitions will return an error.
Parameters
[in] list Device list to search.
[in] uid Unique identifier of the target device.
[out] error Pointer to receive error details. Initialized to NULL before call, populated with error object on failure. Caller must release memory.
Returns
Pointer to the requested device instance, or NULL if not found.
Referenced by dt::DeviceList::GetDeviceByUid().
DT_EXPORT const char* dt_device_list_get_device_info (const dt_device_list * list, uint32_t index, dt_camera_info info, dt_error ** error)
Retrieves device information from list.
Parameters
[in] list Initialized device list instance.
[in] index Zero-based device index.
[in] info Type of information to retrieve.
[out] error Receives detailed error information if operation fails.
Returns
const char* Device name string. Lifetime tied to device list.
Referenced by dt::DeviceList::GetConnectionType(), dt::DeviceList::GetIpAddress(), dt::DeviceList::GetLocalMacAddress(), dt::DeviceList::GetName(), dt::DeviceList::GetPid(), dt::DeviceList::GetSerialNumber(), dt::DeviceList::GetUid(), and dt::DeviceList::GetVid().
DT_EXPORT const char* dt_device_get_device_info (const dt_device * device, dt_camera_info info, dt_error ** error)
Retrieves device information.
Parameters
[in] device Initialized device instance.
[in] info Type of information to retrieve.
[out] error Receives detailed error information if operation fails.
Returns
const char* Requested information. String lifetime tied to device.
Referenced by dt::DeviceInfo::GetAsicName(), dt::DeviceInfo::GetConnectionType(), dt::DeviceInfo::GetFirmwareVersion(), dt::DeviceInfo::GetHardwareVersion(), dt::DeviceInfo::GetIpAddress(), dt::DeviceInfo::GetMacAddress(), dt::DeviceInfo::GetName(), dt::DeviceInfo::GetPid(), dt::DeviceInfo::GetSerialNumber(), dt::DeviceInfo::GetSupportedMinSdkVersion(), dt::DeviceInfo::GetUid(), and dt::DeviceInfo::GetVid().
DT_EXPORT dt_device_state dt_device_get_device_state (const dt_device * device, dt_error ** error)
Queries current operational state of device.
Parameters
[in] device Initialized device instance.
[out] error Receives detailed error information if operation fails.
Returns
dt_device_state Current device state information.
Referenced by dt::Device::GetDeviceState().
DT_EXPORT void dt_device_set_state_changed_callback (dt_device * device, dt_device_state_callback callback, void * user_data, dt_error ** error)
Registers callback for device state changes.
Parameters
[in] device Initialized device instance.
[in] callback Function to invoke on state changes.
[in] user_data Custom user context passed to callback.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::SetDeviceStateChangedCallback().
DT_EXPORT void dt_device_reboot (dt_device * device, dt_error ** error)
Reboots device hardware.
Attention
Device disconnects during reboot. Accessing handle post-reboot causes undefined behavior - destroy handle with dt_delete_device and reacquire device.
Parameters
[in] device Target device to reboot.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::Reboot().
DT_EXPORT dt_sensor_list* dt_device_get_sensor_list (const dt_device * device, dt_error ** error)
Retrieves all sensors associated with device.
Parameters
[in] device Initialized device instance.
[out] error Receives detailed error information if operation fails.
Returns
dt_sensor_list* Sensor list instance. Must be released by caller. Returns NULL on failure.
Referenced by dt::Device::GetSensorList().
DT_EXPORT dt_sensor* dt_device_get_sensor (dt_device * device, dt_sensor_type type, dt_error ** error)
Retrieves specific sensor by type.
Parameters
[in] device Initialized device instance.
[in] type Sensor type identifier.
[out] error Receives detailed error information if operation fails.
Returns
dt_sensor* Requested sensor instance. Lifetime tied to device.
Referenced by dt::Device::GetSensor().
DT_EXPORT uint32_t dt_device_get_supported_option_count (const dt_device * device, dt_error ** error)
Queries number of supported configuration options.
Parameters
[in] device Initialized device instance.
[out] error Receives detailed error information if operation fails.
Returns
uint32_t Number of available options.
Referenced by dt::Device::GetSupportedOptionCount().
DT_EXPORT dt_option_item dt_device_get_supported_option_item (const dt_device * device, uint32_t index, dt_error ** error)
Retrieves option metadata by index.
Parameters
[in] device Initialized device instance.
[in] index Zero-based option index.
[out] error Receives detailed error information if operation fails.
Returns
dt_option_item Option metadata structure.
Referenced by dt::Device::GetSupportedOption().
DT_EXPORT bool dt_device_is_option_supported (const dt_device * device, dt_option_id option_id, dt_permission_type permission, dt_error ** error)
Checks option permission availability.
Parameters
[in] device Initialized device instance.
[in] option_id Target option identifier.
[in] permission Permission type to check.
[out] error Receives detailed error information if operation fails.
Returns
true Permission granted for specified option.
false Permission denied or option unavailable.
Referenced by dt::Device::IsOptionSupported().
DT_EXPORT void dt_device_set_int_option (dt_device * device, dt_option_id option_id, int32_t value, dt_error ** error)
Sets an integer type of device option.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be set.
[in] value Value of the option to be set.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::SetIntOption().
DT_EXPORT int32_t dt_device_get_int_option (dt_device * device, dt_option_id option_id, dt_error ** error)
Gets an integer type of device option.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be get.
[out] error Receives detailed error information if operation fails.
Returns
int32_t Value of the option.
Referenced by dt::Device::GetIntOption().
DT_EXPORT dt_int_option_range dt_device_get_int_option_range (dt_device * device, dt_option_id option_id, dt_error ** error)
Gets the integer type of device option range.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be get.
[out] error Receives detailed error information if operation fails.
Returns
dt_int_option_range Range of the option.
Referenced by dt::Device::GetIntOptionRange().
DT_EXPORT void dt_device_set_float_option (dt_device * device, dt_option_id option_id, float value, dt_error ** error)
Sets a float type of device option.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be set.
[in] value Value of the option to be set.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::SetFloatOption().
DT_EXPORT float dt_device_get_float_option (dt_device * device, dt_option_id option_id, dt_error ** error)
Gets a float type of device option.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be get.
[out] error Receives detailed error information if operation fails.
Returns
float Value of the option.
Referenced by dt::Device::GetFloatOption().
DT_EXPORT dt_float_option_range dt_device_get_float_option_range (dt_device * device, dt_option_id option_id, dt_error ** error)
Gets the float type of device option range.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be get.
[out] error Receives detailed error information if operation fails.
Returns
dt_float_option_range Range of the option.
Referenced by dt::Device::GetFloatOptionRange().
DT_EXPORT void dt_device_set_bool_option (dt_device * device, dt_option_id option_id, bool value, dt_error ** error)
Sets a boolean type of device option.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be set.
[in] value Value of the option to be set.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::SetBoolOption().
DT_EXPORT bool dt_device_get_bool_option (dt_device * device, dt_option_id option_id, dt_error ** error)
Gets a boolean type of device option.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be get.
[out] error Receives detailed error information if operation fails.
Returns
bool Value of the option.
Referenced by dt::Device::GetBoolOption().
DT_EXPORT dt_bool_option_range dt_device_get_bool_option_range (dt_device * device, dt_option_id option_id, dt_error ** error)
Gets the boolean type of device option range.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be get.
[out] error Receives detailed error information if operation fails.
Returns
dt_bool_option_range Range of the option.
Referenced by dt::Device::GetBoolOptionRange().
DT_EXPORT void dt_device_set_structured_data (dt_device * device, dt_option_id option_id, const uint8_t * data, uint32_t data_size, dt_error ** error)
Sets structured data.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be set.
[in] data The data to be set.
[in] data_size Size of the data.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::SetStructuredData().
DT_EXPORT void dt_device_get_structured_data (dt_device * device, dt_option_id option_id, uint8_t * data, uint32_t * data_size, dt_error ** error)
Gets structured data of a device option.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be get.
[out] data The obtained option data.
[out] data_size The size of the obtained option data.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::GetStructuredData().
DT_EXPORT void dt_device_get_raw_data (dt_device * device, dt_option_id option_id, dt_get_data_callback cb, void * user_data, dt_error ** error)
Gets raw data of a device option.
Parameters
[in] device Initialized device instance.
[in] option_id ID of the option to be get.
[out] cb The get data callback.
[out] user_data User-defined data that will be returned in the callback.
[out] error Receives detailed error information if operation fails.
DT_EXPORT bool dt_device_is_global_timestamp_supported (const dt_device * device, dt_error ** error)
Checks global timestamp support capability.
Parameters
[in] device Initialized device instance.
[out] error Receives detailed error information if operation fails.
Returns
true Device supports global timestamp synchronization.
false Feature unavailable.
Referenced by dt::Device::IsGlobalTimestampSupported().
DT_EXPORT void dt_device_enable_global_timestamp (dt_device * device, bool enable, dt_error ** error)
Enables/disables global timestamp synchronization.
Parameters
[in] device Initialized device instance.
[in] enable true to enable synchronization, false to disable.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::EnableGlobalTimestamp().
DT_EXPORT void dt_device_send_file_to_device (dt_device * device, const char * src_file_path, const char * dst_file_path, dt_file_tran_callback callback, bool async, void * user_data, dt_error ** error)
Transfers file from host to device storage.
Parameters
[in] device Initialized device instance.
[in] src_file_path Source file path on host system.
[in] dst_file_path Destination path on device storage.
[in] callback Progress and completion callback.
[in] async true for asynchronous operation (non-blocking).
[in] user_data Custom context passed to callback.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::SendFileToDevice().
DT_EXPORT void dt_device_receive_file_from_device (dt_device * device, const char * src_file_path, const char * dst_file_path, dt_file_tran_callback callback, bool async, void * user_data, dt_error ** error)
Retrieves file from device storage to host.
Parameters
[in] device Initialized device instance.
[in] src_file_path Source file path on device storage.
[in] dst_file_path Destination path on host system.
[in] callback Progress and completion callback.
[in] async true for asynchronous operation (non-blocking).
[in] user_data Custom context passed to callback.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::ReceiveFileFromDevice().
DT_EXPORT void dt_device_update_firmware (dt_device * device, const char * path, dt_device_fw_update_callback callback, bool async, void * user_data, dt_error ** error)
Updates device firmware from file.
Parameters
[in] device Initialized device instance.
[in] path Path to firmware image file on host.
[in] callback Firmware update progress callback.
[in] async true for asynchronous operation (non-blocking).
[in] user_data Custom context passed to callback.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::UpdateFirmware().
DT_EXPORT void dt_device_update_firmware_from_data (dt_device * device, const uint8_t * data, uint32_t data_size, dt_device_fw_update_callback callback, bool async, void * user_data, dt_error ** error)
Updates device firmware from memory buffer.
Parameters
[in] device Initialized device instance.
[in] data Firmware image data buffer.
[in] data_size Size of firmware data in bytes.
[in] callback Firmware update progress callback.
[in] async true for asynchronous operation (non-blocking).
[in] user_data Custom context passed to callback.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::UpdateFirmwareFromData().
DT_EXPORT void dt_device_write_flash (dt_device * device, uint32_t offset, const void * data, uint32_t data_size, dt_set_data_callback callback, bool async, void * user_data, dt_error ** error)
Writes data to device flash memory.
Parameters
[in] device Initialized device instance.
[in] offset Flash memory offset address.
[in] data Source data buffer to write.
[in] data_size Size of data in bytes.
[in] callback Completion status callback.
[in] async true for asynchronous operation (non-blocking).
[in] user_data Custom context passed to callback.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::WriteFlash().
DT_EXPORT void dt_device_read_flash (dt_device * device, uint32_t offset, uint32_t data_size, dt_get_data_callback callback, bool async, void * user_data, dt_error ** error)
Reads data from device flash memory.
Parameters
[in] device Initialized device instance.
[in] offset Flash memory offset address.
[in] data_size Number of bytes to read.
[in] callback Data reception and progress callback.
[in] async true for asynchronous operation (non-blocking).
[in] user_data Custom context passed to callback.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::ReadFlash().
DT_EXPORT void dt_device_enable_heartbeat (dt_device * device, bool enable, dt_error ** error)
Controls device heartbeat monitoring.
When enabled, SDK maintains 3-second heartbeat intervals.
Attention
Extended heartbeat absence triggers device disconnection and reboot.
Parameters
[in] device Initialized device instance.
[in] enable true to enable heartbeat, false to disable.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::EnableHeartbeat().
DT_EXPORT void dt_device_send_and_receive_data (dt_device * device, const uint8_t * send_data, uint32_t send_data_size, uint8_t * receive_data, uint32_t * receive_data_size, dt_error ** error)
Executes vendor-specific device command (factory use).
Parameters
[in] device Initialized device instance.
[in] send_data Command data buffer to transmit.
[in] send_data_size Size of transmit buffer in bytes.
[out] receive_data Response data buffer.
[in,out] receive_data_size Input: max capacity of receive buffer. Output: actual received byte count.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::SendAndReceiveData().
DT_EXPORT dt_camera_param_list* dt_device_get_calibration_camera_param_list (dt_device * device, dt_error ** error)
Retrieves the original camera calibration parameters stored on the device.
Provides factory-calibrated camera parameters not adjusted to current streaming configuration.
Note
Parameters may require scaling or mirroring for current usage. Non-expert users should prefer dt_pipeline_get_camera_param() for pre-processed parameters.
Parameters
[in] device Device instance to query.
[out] error Receives detailed error information if operation fails.
Returns
Handle to camera parameter collection. Caller must release with dt_delete_camera_param_list.
Referenced by dt::Device::GetCalibrationCameraParamList().
DT_EXPORT uint32_t dt_camera_param_list_get_count (dt_camera_param_list * param_list, dt_error ** error)
Retrieves the number of camera parameter sets in the collection.
Parameters
[in] param_list Camera parameter collection instance.
[out] error Receives detailed error information if operation fails.
Returns
Count of parameter sets in the collection.
Referenced by dt::CameraParamList::GetCount().
DT_EXPORT dt_camera_param dt_camera_param_list_get_param (dt_camera_param_list * param_list, uint32_t index, dt_error ** error)
Retrieves a specific camera parameter set by index.
Parameters
[in] param_list Camera parameter collection instance.
[in] index Zero-based index of the parameter set to retrieve.
[out] error Receives detailed error information if operation fails.
Returns
Camera parameter set. Returned structure is self-contained and requires no explicit deletion.
Referenced by dt::CameraParamList::GetCameraParam().
DT_EXPORT void dt_delete_camera_param_list (dt_camera_param_list * param_list)
Releases resources associated with a camera parameter collection.
Parameters
[in] param_list Camera parameter collection to destroy.
Referenced by dt::CameraParamList::~CameraParamList().
DT_EXPORT void dt_device_timer_sync_with_host (dt_device * device, dt_error ** error)
Synchronizes the device's internal timer with the host system clock.
Aligns device timekeeping with host time. Can be called concurrently on multiple devices for system-wide synchronization.
Note
May cause timestamp discontinuity in active streams during synchronization.
Periodic synchronization (recommended every 60 minutes) compensates for device timer drift.
Parameters
[in] device Device handle to synchronize.
[out] error Receives detailed error information if operation fails.
Referenced by dt::Device::TimerSyncWithHost().